### ISSUE TITLE
Decide on need for notification and event bus service

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#100]
As a development lead I want to understand the lnotification and event bus service, so that I am able to build the services according to the specifications.

Further description:

Currently there is uncertainty whether this service is still needed or if its planned functionality is part of another service.
The output of this issue should be a decision if the service is still needed.

- [x] Collect information about possible functionalities of this service
- [x] Decide if the service is still needed or if functionality is part of another service

---

**Acceptance Criteria:**
- [x] Decision about need for this service is documented within this issue

---

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
@hschmidthh any updates on this issue?

**Comment by hschmidthh** [comment]
I put a first description of the Message and Event Bus online:
https://github.com/openintegrationhub/Microservices/blob/MessageandEventBusConcept/MessageProcessing/MessageandEventBus.md
