### ISSUE TITLE
Snapshot service and IAM interaction

### ISSUE THREAD

**Issue by weberjm** [openintegrationhub/openintegrationhub#1001]
looks like if the component orchestrator handles a TON of traffic in rapid succession in its _handleMessage function it will effectively DDoS the Component Repository and the IAM service along with it (through token introspection requests when calling the Component Repo, and requests for the flow specific token). Will probably need some kind of caching on these object lookups inside of the component orchestrator in order to make that more efficient. Maybe capture the component object at the start of a Flow, store it somewhere, and reference that for the duration of the flow execution. Or use some kind of time based cache? confirmed. I implemented some really dumb caching in services/component-repository/src/dao/ComponentsDao.js , as well as pulling apiKey out of the orchestratorToken so we don't have to ask IAM for the flow-specific token anymore (since we already had it). It went better but IAM is still getting absolutely smashed to the point where the database pool goes down
ah, looks like IAM gets smashed through Snapshot Service token introspection. And the snapshot service eventually stops handling requests as well :grimacing:

**To Reproduce**
1. Setup ...
2. Start ...
3. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by heggert** [comment]
We added LRU caching to component orchestrator. See https://github.com/openintegrationhub/openintegrationhub/pull/1013
