### ISSUE TITLE
Resource descriptions

### ISSUE THREAD

**Issue by weberjm** [openintegrationhub/openintegrationhub#1002]
As a System Admin, I want to know the minimum necessary resources for my services so that my system runs effectively.

Further description:

Requested from user:
I wonder if that's a resource issue. My RabbitMQ pod has no resource requests/limits defined. I upped the Orchestrator from 0.1 / 512 to 0.5 / 1024 which sped things up. Are there recommended resource allocations for production clusters written down anywhere? I basically just deployed it with the defaults

---

**Acceptance Criteria:**
- [ ] Criteria 1
- [ ] Criteria 2
- [ ] Criteria N

---

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by blaggacao** [comment]
#1073 proposes to review (and probably code comment) resource requirements directly within the reference implementation.

**Comment by RobinBrinkmann** [comment]
Backlog clean-up. Closing of outdated issues.
