### ISSUE TITLE
Document external IDP - I want to use dex

### ISSUE THREAD

**Issue by blaggacao** [openintegrationhub/openintegrationhub#1007]
It is unclear how an external IDP would be plugged into OIH.
In our case, we plan to use https://github.com/dexidp/dex with LDAP backend.

**Comment by RobinBrinkmann** [comment]
Most partners use the Open Integration Hub IAM in their implementation, so I am afraid we don't have any helpful documentation to offer. We are happy to support where we can and also appreciate your feedback / leanings when you do implement dex ;)
