### ISSUE TITLE
Describe build process

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#102]
As a developer I want to know the build process, so that I can build my services according to the specifications.

Further description:

We need  a documented common built process for all oih services

---

**Acceptance Criteria:**
- [x] build process documented
- [x] exemplary service adjusted to regulations in build process

---

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by StephanPfeiffer** [comment]
@falkvoigt Please provide your feedback.

**Comment by falkvoigt** [comment]
Hi i believe that i can't give that information for Documentation. The only thing i could say is that the Ci/CD Pipeline calls yarn build at the moment. Whats behind that call i can't define. Could be the nodeJS has to be compiled (TypeScript, JSX or just compile scss to css). 

Or is that task related to 
        openintegrationhub/Guidelines/Build process documentation.md
@DennisCES

**Comment by DennisCES** [comment]
Hi @falkvoigt, yes, it's only about checking for completeness

**Comment by falkvoigt** [comment]
I'm fine with that
