### ISSUE TITLE
Describe Deployment Process

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#103]
As a developer I want to know the deployment process, so that I know how to deploy my services to the oih k8s cluster.

Further description:

We need a documented deployment process for all oih services

---

**Acceptance Criteria:**
- [x] deployment process documented

---

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by DennisCES** [comment]
Can be find in openintegrationhub/guidelines
