### ISSUE TITLE
`sudo rm` burried deep down within tooling

### ISSUE THREAD

**Issue by blaggacao** [openintegrationhub/openintegrationhub#1032]
https://github.com/openintegrationhub/openintegrationhub/blob/6995ded0b7ce63343b1e401227937c1797291971/dev-tools/docker-compose/src/packages/purge.js#L5

Ouch! &mdash; I would not trust this tooling out of principle ... :confused:

**Comment by RobinBrinkmann** [comment]
@heggert pls check.

**Comment by weberjm** [comment]
This is from a developer's own environment, providing it as-is for the benefit of other users. If it is possible to make any optimizations here, it will be done as time allows.

**Comment by heggert** [comment]
The dev-tools are prototypes for development. Currently, most tools are neither beautifully designed nor completely fail-safe. And yet they help us considerably in further development. Feel free to use and improve them :)
