### ISSUE TITLE
Design example case of new transformation functionality

### ISSUE THREAD

**Issue by SvenHoeffler** [openintegrationhub/openintegrationhub#1033]
In the course usage of the OIH, it became apparent that the current schema of distinct transformers and adapters causes significant resource usage overhead. Instead, it should be investigated whether the two functionalities could be merged into a single component, while still retaining the capability of custom mapping.

To that end, we require an example for this new structure to evaluate potential  issues with this new approach.

---

**Acceptance Criteria:**
- [x] New combined adapter/transformer component designed
- [x] Transformation allows for predefined mapping as defined by component creator
- [x] Transformation allows for application of custom external mapping schema
- [x] Transformation can be skipped entirely for the use of external transformers

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by blaggacao** [comment]
I also suspect that using a compiled language (e.g. go) might boost the responsivness further &mdash; probably also using grpc-http/2.

Are the results (dod) already public to have a quick look?

**Comment by SvenHoeffler** [comment]
@blaggacao 

Essentially, the overarching goal is to find a way to at least somewhat standardize transformation procedure and configuration, while at the same time still allowing connector developers to apply whichever transformation strategy they require. This way, you should be able to just drop any connector into a given flow and have it behave in an expected way, no matter whether you use its inbuilt hardcoded transformations (if present), wish to inject your own custom ones, or indeed skip transformation entirely.

Current state of things is that we've added a transformation function to the ferryman, which a connector can use as a simple interface to apply any transformations. An prototypical version was added yesterday: https://github.com/openintegrationhub/openintegrationhub/pull/1051, but of course it's still subject to change as development progresses.
