### ISSUE TITLE
IAM crashes after flooding MongoDB connection pool

### ISSUE THREAD

**Issue by heggert** [openintegrationhub/openintegrationhub#1035]
- investigate
- find solution
- implement a fix or create a follow-up issue

**Comment by mlb5000** [comment]
The ultimate issue here is that the MongoDB pool somehow gets into a `destroyed` state, which it never tries to recover from. Should it just try to recreate the pool and carry on if this happens?

**Comment by heggert** [comment]
Fixed by f95e27022bab91a5831e408ec1299191be9b18f2.

Problem was property *socketTimeoutMS* that was passed to mongoose

**Comment by mlb5000** [comment]
@heggert is this available in the latest version of the IAM service in Dockerhub?

**Comment by weberjm** [comment]
@mlb5000 Hi Matt, This fix should be present in all images on Docker Hub starting with [**1.0.0_36166**](https://hub.docker.com/layers/openintegrationhub/iam/1.0.0_36166/images/sha256-2fc5dd3129c521cabf7175da9978921dde6795804df172bbd1cb3d5ccc33a042?context=repo). 

It appears that the version of the Service should have been updated by this merge, but was not. We are working to improve our release processes to make this more clear for everyone. 

Please let us know if you see any additional issues here!
