### ISSUE TITLE
Add Flow Creation Guide

### ISSUE THREAD

**Issue by SvenHoeffler** [openintegrationhub/openintegrationhub#1036]
Although it's already partially covered by the local installation guide, it would be beneficial if there was a guide specifically detailing how to create a flow, how it is supposed to be formatted, and what options are available.

---

**Acceptance Criteria:**
- [ ] Guide created and added to the github io site

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by RobinBrinkmann** [comment]
could still be improved, but is generally covered [here](https://openintegrationhub.github.io/docs/3%20-%20GettingStarted/UserGuide.html).
