### ISSUE TITLE
SDF Component ID references in Deployment Scripts

### ISSUE THREAD

**Issue by blaggacao** [openintegrationhub/openintegrationhub#1040]
https://github.com/openintegrationhub/openintegrationhub/blob/6995ded0b7ce63343b1e401227937c1797291971/minikube/4-Services/dispatcher-service/k8s/deployment.yaml#L47

This seems to be a stale code instruction as it's not referenced or explained in the manual &mdash; `./services/../k8s/deployment.yaml` adopts `5d2484d2a422ca001bda5690` here.

Please resolve so that no discomforting stale code instruction is making me nervous :wink:

**Comment by weberjm** [comment]
This instruction is used by the Smart Data Framework for implementations of the OIH framework that utilize the "Hub and Spoke" model. The SDF_ID is used by the Dispatcher service when it creates target flows based on data sent to the Data Hub. The `52d48...` id is from an internal deployment. 

https://github.com/openintegrationhub/openintegrationhub/blob/2f362ae9cc664734341b9590431d4b91fd256b72/services/dispatcher-service/app/config/index.js#L14

This value is then used in the `makeFlow()` function in services/dispatcher-service/app/utils/flowCreator.js

The SDF_ID value is still expected to be provided to the dispatcher service, as any other implementation using the hardcoded "fallback" ID which you referenced would fail when testing the dispatcher.

Passing the component ID in the deployment scripts is probably not the best solution, however, as it forces a redeployment after the SDF component is instantiated in the database. I will update the issue to reflect this and tag it for when work resumes on the Hub and Spoke services.
