### ISSUE TITLE
Adapt REST-component to Ferryman

### ISSUE THREAD

**Issue by SvenHoeffler** [openintegrationhub/openintegrationhub#1047]
Likely just a matter of switching out sailor for ferryman
---

**Acceptance Criteria:**
- [ ] Criteria 1
- [ ] Criteria 2
- [ ] Criteria N

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by IoannisLafiotis** [comment]
https://github.com/openintegrationhub/REST-API-component 

First iteration from the REST-API adjusted to the Pipedrive component!!
