### ISSUE TITLE
Rename "LOGGING_LEVEL" env variables to "LOG_LEVEL"

### ISSUE THREAD

**Issue by heggert** [openintegrationhub/openintegrationhub#1050]

**Comment by weberjm** [comment]
This issue was raised in #1038, referring to secret service.

**Comment by blaggacao** [comment]
That sounds perfect! Other candidates are:
- `MONGODB_URI` | `MONGODB_URL` | `MONGODB_CONNECTION` | `IAM_MONGODB_CONNECTION`
- `QUEUE_URL` | `RABBITMQ_URI`

**Comment by IoannisLafiotis** [comment]
I changed the LOGGING_LEVEL references to LOG_LEVEL.

**Comment by blaggacao** [comment]
@IoannisLafiotis is there a PR that I could review? It would be relevant for my #1055 &mdash; most probably I'd have to rebase upon your changes. 🚀

**Comment by IoannisLafiotis** [comment]
@blaggacao I did the PR !!! Can you check it out??

**Comment by blaggacao** [comment]
#1058 for ref. Thanks!
