### ISSUE TITLE
Unit tests for services that lacks them

### ISSUE THREAD

**Issue by anton-kotenko** [openintegrationhub/openintegrationhub#106]
As a developer, I want all services to have unit tests according to #29 #30

At the moment services
* scheduler
* flows-operator
* communication-router
And library
* src/backendCommonsLib
does not have any unit tests. This should be fixed for obvious reasons. 

**Acceptance Criteria:**
- [ ] scheduler service should have tests as it's described in guideline
- [ ] flows-operator service should have tests as it's described in guideline
- [ ] communication router  service should have tests as it's described in guideline
- [ ] src/backendCommonsLib shoud have tests as it's described in guildeline

**Comment by philecs** [comment]
@anton-kotenko  is this one still up-to-date?
