### ISSUE TITLE
Optimize & Streamline Development Workflow with GitHub Actions

### ISSUE THREAD

**Issue by RobinBrinkmann** [openintegrationhub/openintegrationhub#1061]
We want to automate more steps in the development process and increase code quality by using GitHub Actions. In the process of implementing GitHub Actions we will reduce the amount of other tools used for parts of the workflow and cleanup old references to tools that are not actively used anymore (e.g. travis or lerna).

**Comment by blaggacao** [comment]
Related: I have good experiences with `pre-commit` git hooks. Those can catch a whole category of things early in the dev loop and thereby shorten the feedback loop &mdash; always a good thing. I usually enable only the push hook in order to not to discourage frequent `WIP` committing.

**Comment by RobinBrinkmann** [comment]
We are working this topic with more detailed issues (like #1136 or #1137) and are cleaning up old references as we go. So this very broad issue will be closed.
