### ISSUE TITLE
Services should not run  under root user

### ISSUE THREAD

**Issue by anton-kotenko** [openintegrationhub/openintegrationhub#108]
As a Ops, I don't want services to run under root user even inside docker container (see #29 #30).

To reduce risks of  privilege escalation and/or run from inside docker into host machine due to different docker/linux kernel bugs  it's safer not to use root user inside docker container.

At the moment scheduler, communication-router, flows-operator, iam and integration-content-repository
runs under root user in docker

**Acceptance Criteria:**
- [ ] scheduler runs under non-system user
- [ ] component orchestator runs under non-system user
- [ ] webhooks runs under non-system user
- [x] integration-content-repository runs under non-system user

**Comment by falkvoigt** [comment]
schould be possible via Kubernetes Yaml
https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

or did you mean the user Docker Deamon starts Container on OS level?

**Comment by sachmerz** [comment]
@anton-kotenko if the acceptance criteria refers to users used inside the Docker container, then there shouldn't be an issue with IAM. This service runs as *node* user with a user-id 1000 (see Dockerfile of iam).

**Comment by anton-kotenko** [comment]
O, you are right.
I've missed all that "chown's" and "USER" in Docker file.

**Comment by philecs** [comment]
How is the status for the 3 missing services mentioned in the issue description?

**Comment by anton-kotenko** [comment]
No changes.

**Comment by philecs** [comment]
@anton-kotenko  is this one still up-to-date?
