### ISSUE TITLE
Move logging service to seperate repo

### ISSUE THREAD

**Issue by RobinBrinkmann** [openintegrationhub/openintegrationhub#1080]
Our goal is to keep the services within the monorepo as generalized as possible, in order to ensure adoption for as many use cases as possible. We therefore want to reduce the amount of external tooling and services, that are tied to a specific platforms.

The current logging service is basically only usable for GCP and is deployed only for very specific use cases. The logging service shall be moved to its own repository, to still be available to the community, but be clearly separated from the core framework. 

All references, links and documentation has to be checked and adjusted accordingly. 

---

**Acceptance Criteria:**
- [x] logging service is moved to its own repository
- [x] references, links and documentation are updated
- [x] new readme describes the use of the service

---

**Comment by IoannisLafiotis** [comment]
https://github.com/openintegrationhub/Logging-service
