### ISSUE TITLE
Cannot add a component in the  WEB-UI

### ISSUE THREAD

**Issue by gittester12x** [openintegrationhub/openintegrationhub#1081]

**Comment by gittester12x** [comment]
Hi,
when im trying to adding a new component in the web-ui nothing happens and im getting the following error. Adding components in postman works fine. Could you help me fix it? Thanks in advance
 

![Screenshot from 2020-10-08 11-42-43](https://user-images.githubusercontent.com/26030007/95442644-ef83d380-095b-11eb-9792-bfb9a46a8c3b.png)

**Comment by RobinBrinkmann** [comment]
Hi @gittester12x 
thanks for opening the issues. Please provide some more information about your setup, i.e. if this is a local deployment with minikube (config?) and some more detailed error logs.
