### ISSUE TITLE
unable to run setup

### ISSUE THREAD

**Issue by remcohh** [openintegrationhub/openintegrationhub#1094]
Hello, I don't know if this is the right place to ask, but I am having issues to run the setup script and since I am very new to the framework I don't have a clue to solve.

After the service/webhooks is created I am getting 

"Waiting for http://skm.localoih.com/api/v1/secrets" forever

Any clue how to solve this?

**Comment by RobinBrinkmann** [comment]
Hi @remcohh, yes this is the right place and thanks for opening the issue ;)

Can you tell us a bit more about your which setup you are trying to do and what your system looks like? More detailed errorlogs are also helpful, if you have any.

**Comment by remcohh** [comment]
Hi @RobinBrinkmann thanks for your reply!
After a very long time, about 30 minutes suddenly the setup progressed and now everything is running.
Is this long setup time expected?

I am running it on a current macbook pro with 8 gigs of memory

**Comment by RobinBrinkmann** [comment]
Usually it does not take that long, no. But I am glad it went through now. I leave this issues open for now, in case you have further questions.

8GB is the minimum you need, but if you can, I recommend bumping this up a bit.

**Comment by heggert** [comment]
Hi @remcohh,

the first setup takes a relatively long time because all services are built from scratch. Any further setup is much faster.
