### ISSUE TITLE
Multiple Services contain invalid license references in package.json

### ISSUE THREAD

**Issue by weberjm** [openintegrationhub/openintegrationhub#1106]
A machine-readable license reference should be provided in the package.json file for each separately deployed library or service. 

In our framework, quite a few services and libraries refer to "APL-2.0," which is not an SPDX standard [license identifier](https://spdx.org/licenses/). This leads to warnings being triggered at runtime.

Update the following services to a valid license identifier:

- [ ] lib/backend-commons-lib
- [ ] lib/component-orchestrator
- [ ] lib/event-bus
- [ ] services/component-orchestrator
- [ ] services/webhooks

In addition, the following _package.json_ files are listed as "UNLICENSED," which should be updated if they are to be released with a license:
- [ ] lib/attachment-storage-service
- [ ] services/attachment-storage-service
- [ ] services/data-hub
- [ ] services/logging-service
- [ ] services/snapshot-service

**Comment by RobinBrinkmann** [comment]
Backlog clean-up. Closing of outdated issues.
