### ISSUE TITLE
Ensure correct request / response format

### ISSUE THREAD

**Issue by heggert** [openintegrationhub/openintegrationhub#1120]
The REST-API interfaces of the framework services do not always correspond to our standard specifications regarding the request/response format.

**1. The request JSON body format for GET / POST / PATCH / PUT / DELETE should not contain the "data" property. Examples that conform to this specification:**

**Request POST api/service/resource/**
body (application/json)
```
{
	"property1": "1",
	"property2": "abc"
	...
}
```
**Request PATCH api/service/resource/:id**
body (application/json)
```
{
	"property3": "1"
}
```

**2. The response JSON body format must contain at least the "data" property and should contain the "meta" property. Examples that conform to this specification:**

**Response GET api/service/resource**
body (application/json)
```
{
	"data": [
		{
			"property1": "1",
			"property2": "abc"
		},
		{
			"property1": "2",
			"property2": "abc"
		}
	],
	"meta": {
        	"page": 1,
        	"perPage": 2,
        	"total": 2,
    		"totalPages": 1
	}
}
```
**Response GET api/service/resource/123**
body (application/json)
```
{
	"data": {
		"property1": "123",
		"property2": "abc"
	}
}
```
All framework services within [/services](https://github.com/openintegrationhub/openintegrationhub/tree/master/services) must be examined and, if necessary, adjusted. **Communication between the services within the framework must not be impaired**.

- [x] app-directory
- [x] attachment-storage-service
- [x] audit-log
- [x] component-orchestrator
- [x] component-repository
- [x] data-hub
- [x] dispatcher-service
- [x] flow-repository
- [x] iam
- [x] ils
- [x] meta-data-repository
- [x] reports-analytics
- [x] scheduler
- [x] secret-service
- [x] snapshots-service
- [x] template-repository
- [x] webhooks

**Comment by weberjm** [comment]
Good description, thanks! The [JSON API](https://jsonapi.org/format/#document-top-level) spec also has some background on the need for the `data` field, and I think makes for a good review. 

I agree with you, though, that the `data` field is generally not required for the Request object, as you will never make a request with an `errors` or `meta` object.

**Comment by SvenHoeffler** [comment]
After a preliminary examination, it fortunately looks like the majority of services already adhere to the schema. The exceptions I have found so far are as follows:

- App Directory: Get Response does not contain data/meta
- Component Repository: Request body requires superfluous `data` key
- IAM: Get Responses do not contain data/meta
- Secret Service: Request bodies requires superfluous `data` key
- Webhook Service: Request bodies requires superfluous `body` key (this is related to #1201), response body does not have data/meta (less of an issue as webhook service cannot return meaningful data)
