### ISSUE TITLE
Update GCP Installation Documents for Healthcheck Behavior

### ISSUE THREAD

**Issue by weberjm** [openintegrationhub/openintegrationhub#1125]
When deploying to Google Cloud Platform, following the [GCP Installation Guide](https://openintegrationhub.github.io/docs/Getting%20Started/GCPInstallationGuide.html) from the Help Documentation will lead to an inability for the Kubernetes control plane and kubelet to mark services as healthy and route traffic to them.

### To Reproduce
1. Following the steps in the Installation guide, the Ingress description is applied to the cluster early in the process (https://openintegrationhub.github.io/docs/Getting%20Started/GCPInstallationGuide.html#basic-open-integration-hub-infrastructure-setup)
2. Later, when IAM is deployed (https://openintegrationhub.github.io/docs/Getting%20Started/GCPInstallationGuide.html#identity-and-access-management-deployment), it is not possible to proceed to the next step because traffic will not be routed to the IAM Pod
3. This situation repeats when deploying any other services to the cluster which have already been defined in the Ingress

### Expected behavior
It was expected that the Pods would become addressable upon launch.

### Context
The root cause of this issue comes down to the actions performed by Google Kubernetes Engine when you create an Ingress. It additionally creates a Load Balancer and its related Backend Services. Each Backend Service also has a Healthcheck created and assigned, which pings the root endpoint `/` of Pods to see if they are alive. This Healthcheck is used to determine if a pod is in a Healthy state and can have traffic sent to it.

When applying the Deployment configuration for each Service, Readiness and Liveness probes are described at the endpoint `/healthcheck`. The OIH Services do not reply to the root endpoint `/`, but return a 404 error. 

When a Healthcheck is created, it will use the Readiness and Liveness probes from applicable Deployments, but only if they have already been applied to the Cluster. After creation, the Healthcheck does not track any changes to Deployments, so will not pick up the probe values later.

### Proposed Solution
Once an Ingress has been created for a Service, the only way to change its healthcheck is by one of three methods:
- Delete and recreate the Ingress
- Apply the Ingress configuration without the Service, and then Apply the configuration again with the Service re-added
- Manually change the Healthcheck parameters

Therefore, it is proposed to handle this situation via education, and update the Help Documentation to apply the Ingress for each Service only after the Service and Deployment configurations have already been applied.

An alternate solution would be to use a [Backend Config CRD](https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#health_checks) to declaratively describe the Healthcheck values for each Service.

**Comment by jverce** [comment]
I think I'm experiencing the same issue while doing a [local installation](https://openintegrationhub.github.io/docs/Getting%20Started/LocalInstallationGuide.html#identity-and-access-management-deployment), since I see the IAM pod constantly getting restarted due to the readiness probe failing:
```
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  38m                    default-scheduler  Successfully assigned oih-dev-ns/iam-8494958c88-jxt55 to minikube-m02
  Normal   Pulled     33m                    kubelet            Successfully pulled image "openintegrationhub/iam:latest" in 4m50.69322049s
  Normal   Pulled     32m                    kubelet            Successfully pulled image "openintegrationhub/iam:latest" in 2.615347682s
  Normal   Pulling    32m (x3 over 38m)      kubelet            Pulling image "openintegrationhub/iam:latest"
  Normal   Created    32m (x3 over 33m)      kubelet            Created container iam
  Normal   Started    32m (x3 over 33m)      kubelet            Started container iam
  Normal   Pulled     32m                    kubelet            Successfully pulled image "openintegrationhub/iam:latest" in 1.967334902s
  Warning  Unhealthy  23m (x20 over 33m)     kubelet            Readiness probe failed: Get "http://172.17.0.3:3099/healthcheck": dial tcp 172.17.0.3:3099: connect: connection refused
  Warning  BackOff    3m20s (x117 over 32m)  kubelet            Back-off restarting failed container
```

**Comment by weberjm** [comment]
Hi @jverce, I believe that the problem described here is unique to the GCP implementation, but I am not positive. GCP attaches healthchecks to the Load Balancer when it is created, but minikube handles probes through the kubelet and calls whatever is listed in the deployment. 

For a local deployment, I would first check to see if the pod is not completely deployed by the time the readiness probe is running. Depending on system resources, sometimes this can take longer than expected. You can change the `initialDelaySeconds` value in your Deployment file to a higher number to see if this fixes the issue.

Another problem could be caused if there are any issues with the minikube IP address, or if it has changed on a redeployment. I see that your readiness probe is failing due to a "connection refused," so something in your routing is a likely source. See info here: https://github.com/openintegrationhub/openintegrationhub/tree/master/minikube#host-rules-setup

Happy to provide any other help. It might be useful to check the deployment logs through the minikube dashboard to see if it is failing before the service is completely deployed.

**Comment by RobinBrinkmann** [comment]
HI @jverce please also don't hesitate to join our [Slack Channel](https://join.slack.com/t/openintegrationhub/shared_invite/zt-jhw1e65c-6o1OsAtWjTRrpeoGz68YXQ), in case you need further support.

**Comment by jverce** [comment]
Thank you!
@weberjm the problem went away after re-starting the tutorial from scratch.

I also found a few minor issues until I got it running locally, so I'm going to be creating separate issues and PR's for those.
