### ISSUE TITLE
Secret Service Library uses deprecated Cipher functions

### ISSUE THREAD

**Issue by weberjm** [openintegrationhub/openintegrationhub#1127]
In:
- lib/secret-service/src/util/crypto.js
- lib/secret-service/src/adapter/key/tenant/index.spec.js
- lib/secret-service/src/adapter/key/global/index.spec.js

There are calls to `crypto.createCipher()` and `crypto.createDecipher()`, which are deprecated (https://nodejs.org/api/crypto.html#crypto_crypto_createcipher_algorithm_password_options). They should be updated to use the newer functions `createCipheriv()` and `createDecipheriv()`, as has already been done in the ferryman library

**Comment by weberjm** [comment]
It could also be beneficial to write the functionality in cryptoSecret() (lib/secret-service/src/dao/secret.js) or the encrypt()/decrypt() functions in lib/secret-service/src/util/crypto.js to permit more complex objects than just strings to be encrypted. The crypto library also accepts Buffers, TypedArrays, or DataViews.

This would allow for more complex data, or fields unknown at code time (i.e. input fields for Session Secrets), to be encrypted as Sensitive

**Comment by heggert** [comment]
The encryption methods used so far work under Node 16, hence there is no technical necessity to modernize them in the near future. 

However, it should be noted that updating the encryption procedures will increase the protection of sensitive data through a better methodology.
