### ISSUE TITLE
Research: Manage Events/Messages for Queues, even for non-deployed Services

### ISSUE THREAD

**Issue by weberjm** [openintegrationhub/openintegrationhub#1138]
Multiple Services and the Ferryman communicate via the Event Bus and Messaging Queues. Recently, additional feature sets have been added which are not required elements of the core framework. Based on the current state of the framework, it is believed that even optional messages must be ACKed by the Queue Manager and will be stored indefinitely in the Queues.

In order to prevent overloading the messaging queues,
- Determine the current behavior of the queues.
- Discuss options for managing "orphaned" or optional messages.
  - Use flags to prevent messages from being sent if a subscriber is not available
  - On optional events, set up the queue to have auto-ACKs and/or TTL settings to delete un-parsed messages
  - Other?

Discuss...

**Comment by jkopen** [comment]
1.) Messages send via Ferryman will currently not be sent if the Queue is not created. This might cause a error in Ferryman.

Possible solution: It would be simple to just log and discard such messages

2.) The Orchestrator is creating queues which do not exist, also all services using the event bus module might create queues if they do not exist.

Possible solution: Make event-bus not create queues that do not exist. Add settings to Orchestrator so it creates all desired Queues or add an option to detect which services exist and only then create the Queues.

3.) "Fail safe"

- Add messageTtl or maxLength to Queues and route exceeding messages to a deadLetterExchange

- Route all messages which are directed to a not existing exchange / Queue to an alternateExchange

- Provide a way to easily monitor all messages that end up in said exchanges

**Comment by weberjm** [comment]
As discussed on 24.02.2021, work will be planned to improve framework interaction with the messaging queues. This will be handled in follow-on tickets.
