### ISSUE TITLE
Unable to trigger flows from webhooks

### ISSUE THREAD

**Issue by mlb5000** [openintegrationhub/openintegrationhub#1159]
Using the latest `v1.1.0` image in Dockerhub, I am unable to trigger a flow using the webhook. I just get this error every time:

```
{
    "error": "Flow 5fff50f636b496001b4e29c5 either does not exist or is inactive."
}
```

I remembered that [I fixed this in my forked version](https://github.com/mlb5000/openintegrationhub/blob/3a4cca17ba2f8a535d2be2c86fd24cb76692f188/services/webhooks/src/FlowsDao.js#L14) a while ago. The issue is that the statuses used in the query are outdated. Webhooks is just looking for `'started'`, but the new status is actually called `'active'`

Webhooks logs

```
{"name":"webhooks","hostname":"webhooks-6cf77955b5-59xls","pid":27,"level":10,"event":{"headers":{"name":"flow.started","createdAt":1610575157045,"serviceName":"component-orchestrator"},"payload":{"id":"5fff50f636b496001b4e29c5"}},"msg":"Received event","time":"2021-01-13T21:59:17.045Z","v":0}
{"name":"webhooks","hostname":"webhooks-6cf77955b5-59xls","pid":27,"flowId":"5fff50f636b496001b4e29c5","level":30,"msg":"Retrieving flow","time":"2021-01-13T21:59:55.155Z","v":0}
{"name":"webhooks","hostname":"webhooks-6cf77955b5-59xls","pid":27,"flowId":"5fff50f636b496001b4e29c5","level":50,"err":{"message":"Flow 5fff50f636b496001b4e29c5 either does not exist or is inactive.","name":"Error","stack":"Error: Flow 5fff50f636b496001b4e29c5 either does not exist or is inactive.\n    at HttpApi.handleFlowIdParam (/usr/src/webhooks/lib/webhooks/src/http-api.js:146:29)"},"msg":"Sending 404 response","time":"2021-01-13T21:59:56.158Z","v":0}
```

**Comment by mlb5000** [comment]
Actually, this may have been due to me accidentally sharing databases between Services when I first deployed this. `FlowStarted.js` explicitly sets it to `started`, so that is the valid state. However it doesn't explain why it doesn't think it exists when I try to trigger it.

**Comment by heggert** [comment]
I mark this issue as resolved.
At the moment it is not possible to trigger a flow including "cron" property via the webhooks service
