### ISSUE TITLE
[SKM] External access token fetching and refreshing

### ISSUE THREAD

**Issue by sachmerz** [openintegrationhub/openintegrationhub#116]
As a user, I want to use the same OAuth credentials in multiple flows so that I can achieve horizontal scalability.

Further description:
In a token based flow where there is an access token and the provider allows only one access token at a time, multiple connectors must receive the same access token initially as well as a new access token, if it is being refreshed. As described in the [SKM concept](https://github.com/openintegrationhub/Microservices/blob/master/SecureAccessControl/SecureKeyManagementConcept.md) there should be a way for a all connectors, referencing the same credentials to receive the newest access token, e.g. through a singleton service within SKM, which is dedicated for this task.

---

**Acceptance Criteria:**
- [x] More than one connector use the same oauth credentials
- [x] Both connectors receive the same access token
- [x] if the access token expires, a new token is generated e.g. from the refresh token
- [x] both connectors receive the same new access token

---

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by heggert** [comment]
I have implemented a deadlockfree core algorithm for handling general token refreshment in a system with concurrently running SKM instances. Now we have to integrate him to the service itself
