### ISSUE TITLE
Update Ferryman library to execute transforms via flag

### ISSUE THREAD

**Issue by weberjm** [openintegrationhub/openintegrationhub#1172]
As a system user, I want transforms to be executable on any component so that I can execute templated or custom transforms without changing code in a Component.

Further description:
Currently, the Ferryman library supports JSONATA transforms using its built-in [transformer](https://github.com/openintegrationhub/openintegrationhub/blob/master/lib/ferryman/lib/transformer.js). However, the transform function will only be executed if it is coded into the actions of the component separately.

Other optional functions are now being implemented using a flag in the nodesettings config provided to the component from the Orchestrator. The `transform()` functionality should be provided in this way as well, to improve system consistency, and for expanded re-use of global components

---

**Acceptance Criteria:**
- [x] The `transform()` function should be called within the `processMessage()` function of the Ferryman
- [x] `transform()` should be confirmed to accept default transforms or custom transforms passed in with the message

---

**Comment by SvenHoeffler** [comment]
Ferryman is now capable of performing transformations independently of the underlying component. This can happen either before the message is passed into the component, or after it was emitted by the component. See the ferryman readme for details.
