### ISSUE TITLE
Modify open-source Component Generator to function with current OIH Framework Implementations

### ISSUE THREAD

**Issue by weberjm** [openintegrationhub/openintegrationhub#1173]
In order to more efficiently create Connectors which are compatible with the OIH Framework, the open-sourced [Component Generator](https://github.com/openintegrationhub/elasticio-openapi-component-generator) shall be updated to generate valid Connectors for the current versions of the Framework, including support for the new mapping functions.

Notes:
- Additional consideration will have to be given on whether/how to generate triggers programmatically, because currently only one generic trigger is made. 

  - This could be improved by supporting the newer "webhooks" models in OpenAPI
- The process-wrapper file will need to be removed/updated to emit OIH data

Based on #1142, and should also meet the standards of #957

---

**Acceptance Criteria:**
- [x] Dependencies are updated to support the latest versions of OpenAPI / Swagger specifications
- [x] Generator uses Ferryman library instead of Sailor
- [x] Generator creates global connectors, including the runGlobal function
- [x] Generate Actions for each API endpoint
- [x] Determine how to generate triggers (for any `GET` request?) and implement
- [x] Generate all Schemas (input and output) for each call
  - [ ] Include support for linked references, including "oneOf", "allOf", and other OpenAPI descriptors

---

**Comment by weberjm** [comment]
As discussed in #1174, one consideration for schema support: How should the component generator obtain and display schemas for APIs which allow for customization?
- Some APIs have a "free-form" field, such as _additionalFields_, which can be provided with an array or object for any user-customized parameters
- Other SaaS providers may have more complex support for more complex variations or custom objects, such as that [provided by Hubspot](https://developers.hubspot.com/docs/api/crm/crm-custom-objects)

**Comment by weberjm** [comment]
### Schemas
- The Generator shall build the schemas as provided for each API Request and Response into a set of _.json_ files to be found in the `/schemas/` folder. 
- Nested or referenced schemas should continue to be stored as reusable references inside the component, as opposed to following each reference and flattening the schema.
- To the extent possible (i.e. if provided separately in the API definition), schema models which belong to domain objects (not a specific Request or Response schema) should be stored in the `/schemas/models/` folder, and referenced directly by object name
- Request and Response schemas should be generated as _.in.json_ or _.out.json_ to maintain current terminology.

### Triggers
- For API definitions which follow the latest standard and include webhook information, it should be tested to see if triggers can be created from the webhook definitions
  - The final implementation of automated webhook support has yet to be determined, because it will also rely on internal implementation and provision of webhook endpoints.
  - Open to review: Event subscription modes, as APIs such as Slack have moved to (and away from outgoing webhooks)
- The majority of system triggers are "polling" triggers based on a `GET` call. For each `GET` call which obtains a list of items, the generator should attempt to build a trigger built off a predetermined list of potential "dateCreated" or "dateUpdated" fields. Should these fields not be found in the definition, these triggers will not be generated.

**Comment by weberjm** [comment]
In consideration of both the OpenAPI "webhooks" and "callbacks," we should also generate triggers from callbacks, although this may be covered by the generic "start flow" trigger, and handled externally through the webhook setup https://swagger.io/docs/specification/callbacks/

**Comment by IoannisLafiotis** [comment]
For the trigger part of the components we have to rely at least for some time on abstracting the most important triggers from the actions and add them to the triggers folder as well as changing the paths in the component.json file so it can find the trigger function at will.

**Comment by IoannisLafiotis** [comment]
- For the schema out json files I did add a recursive function that looks for props in the responses and abstracts the schema.
- Dereferencing works automatically by using the parse Swagger function
- It has not worked for some endpoints in the hubspot api spec. 
- Could improve by including a second level search in the embedded objects

**Comment by RobinBrinkmann** [comment]
Remaining potential enhancements will be worked in separate issues like #1284
