### ISSUE TITLE
Scheduler may become unresponsive after prolonged uptime

### ISSUE THREAD

**Issue by SvenHoeffler** [openintegrationhub/openintegrationhub#1184]
**Describe the bug**
When a single instance of the scheduler is running for a long time, it appears that some sort of overflow happens, causing it to become unresponsive and inactive. As a consequence, flows that are executed based on a cron expression no longer execute.

A screenshot of the resource consumption shortly before this error occured:
![image.png](https://images.zenhubusercontent.com/5bebf48756fb2c49b17a7d1f/fd664a16-6c91-4b37-ad45-0f6bb39acec1)

**Comment by heggert** [comment]
The behavior of some services is interesting.

After the full release on January 12th, the memory leaks of four services have disappeared (template repository, governance service, flow repository, and metadata repository).

I guess that the Mongoose versions used could be related to this. Each of the above-mentioned services got a new Mongoose version with the last release on the 12th either through the "^" versioning pattern or through explicit selection.
The scheduler, data hub, and snapshots service, however, have not received a new version and therefore still have a memory leak. Their Mongoose version is explicitly selected and wasn't updated between.
