### ISSUE TITLE
Enable passing webhook data into a flow

### ISSUE THREAD

**Issue by weberjm** [openintegrationhub/openintegrationhub#1201]
The system webhooks do not currently pass along the request content when used to trigger a flow. Webhook behavior should be updated to pass received data into any executed flows.

**Comment by heggert** [comment]
**POST** webhook request
- full body (only JSON supported) will be passed as "msg.data"

**GET** webhook request
- full query string will be passed as "msg.data"

In addition, any parameters sent, will be added to "msg.params".

**Comment by RobinBrinkmann** [comment]
Follow-up with docs: https://github.com/openintegrationhub/openintegrationhub.github.io/issues/57
