### ISSUE TITLE
How is OIH different from Microsoft CommonDataModel?

### ISSUE THREAD

**Issue by jugaadi** [openintegrationhub/openintegrationhub#122]
Refer https://github.com/Microsoft/CDM for more details.

**Comment by jugaadi** [comment]
Moreover, they have joined with Adobe and SAP to start an [Open Data Initiative](https://news.microsoft.com/2018/09/24/adobe-microsoft-and-sap-announce-the-open-data-initiative-to-empower-a-new-generation-of-customer-experiences/) based on a similar model.

**Comment by philecs** [comment]
@jugaadi thanks for your question. We'll provide  detailled feedback at the beginning of the next week.

**Comment by philecs** [comment]
@jugaadi we need some further investigation of the Open Data Initiative and CDM to provide a detailed answer. We'll reply to you asap.

**Comment by fdegenhr** [comment]
@jugaadi Thank you for your question.
The general approach of the Microsoft CDM and the OIH data model have a lot in common, e.g. collaborating with partners to evolve the data models and supporting customization. While the Microsoft CDM focusses on the mutual customers of MS, Adobe and SAP, the OIH aims at a high compatibility to existing data models. German medium-sized companies and their usecases are currently in the focus of the OIH.
The OIH datamodel addresses some usecases where traditional data models are limited. The relationship modeling capabilities for example allows the linking of duplicate entities. Such duplicates might be neccassary to model different roles of the same entity.

**Comment by jugaadi** [comment]
Thanks @philecs  and @fdegenhr  for your inputs.
