### ISSUE TITLE
How does an application communicate with a connector?

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#123]
As a product manager I want to know how applications can communicate with a certain connector.

Further description:

As we currently use e.io as our testing platform for connectors, it is not specified how applications will communicate with an open integration hub connector.

- [x] Describe how does application communicates with the connector, once the connector is deployed as a component of a platform using the Open Integration Hub Framework
- [ ] Describe how the connector itself communicates with the rest of the framework e.g. in case data was published by another connected solution or when the connector has to push new data from the application.

---

**Acceptance Criteria:**
- [ ] Communication concepts documented and published on GitHub within the connectors repository

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
No updates yet

**Comment by philecs** [comment]
No updates.

**Comment by jhorbulyk** [comment]
The short answer is that a connector initiates a connection to the application, not the other way around.  There is an exception where the application can push data over an HTTP connection to the platform using the webhooks functionality.

**Comment by philecs** [comment]
Examples for webhook functionality:
https://github.com/elasticio/webhook-component
