### ISSUE TITLE
question about demo installation

### ISSUE THREAD

**Issue by Mars-2030** [openintegrationhub/openintegrationhub#1237]
Hi,

do you have a demo that is available online for testing and trial purposes 
I want to do some testing before starting the installation and deployment I want to make sure if its fits my needs

regards

**Comment by RobinBrinkmann** [comment]
Hi @Mars-2030 thanks for reaching out. Unfortunately there is no online demo account. The Open Integration Hub is a framework, which is always set up individually and run by each person / company themselves. If you do have questions already, please join our [Slack Channel](https://join.slack.com/t/openintegrationhub/shared_invite/zt-mba97vn9-xus3ZbVxnMr2oQwGegIk5Q). We are also happy to jump on a quick call to chat about your use cases.
