### ISSUE TITLE
Deposite necessary secrets for ICR service in k8 cluster 

### ISSUE THREAD

**Issue by DennisCES** [openintegrationhub/openintegrationhub#124]
In order to run all services on the kubernetes cluster, we need deposited secrets for the first inital deploy of the docker images

**Further description:**

Create the necessary secrets for the service for the kubernetes cluster, add them, then deploy your service 
 
---

**Acceptance Criteria:**
- [x] Created and added secrets in k8 cluster
- [x] Service deployed on cluster

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
@DennisCES are there specific todo's what needs to be done here?

**Comment by SvenHoeffler** [comment]
Dennis and I have set the appropriate credentials for the MongoDB, and the secret has now been deployed as "mongosecret-oih-icr"
