### ISSUE TITLE
Document CRUD-Monitoring Service

### ISSUE THREAD

**Issue by hschmidthh** [openintegrationhub/openintegrationhub#125]
Create a concept which describes the CRUD-Monitoring Service

Further description:
Right now, we have a general description of the CRUD-Monitoring Service. For development and deployment we need a more in deep concept.

---

**Acceptance Criteria:**
- [x] Create Document

**Comment by hschmidthh** [comment]
First draft of the concept can be found in the Microservice-Repo:
https://github.com/openintegrationhub/Microservices/blob/crudmonitoringconcept/ManagementServices/CRUDMonitoringConcept.md

**Comment by philecs** [comment]
@hschmidthh can you please create a pull request and assign **one** reviewer?
