### ISSUE TITLE
Logic Gateways

### ISSUE THREAD

**Issue by sachmerz** [openintegrationhub/openintegrationhub#1272]
A new global component for OIH should allow to execute a user defined rule consisting of a set of operations. The operations should be applied to the emitted data from previous steps. As result, the Logic Gateway component can instruct the orchestrator to execute specific node(s), e.g. conditional branching, repeat steps, goto, etc.

**Comment by RobinBrinkmann** [comment]
Added separate documentation [issue](https://github.com/openintegrationhub/openintegrationhub.github.io/issues/56)
