### ISSUE TITLE
Support linked references in Component Generator

### ISSUE THREAD

**Issue by RobinBrinkmann** [openintegrationhub/openintegrationhub#1284]
This is a follow-up issue to #1173

Include support for linked references, including "oneOf", "allOf", and other OpenAPI descriptors

**Comment by IoannisLafiotis** [comment]
As for the time being the component generator is picking the whole schema and it is placing it in the out or in file. Therefore there is no urging need for dereferencing the above descriptors and adding another layer of complexity in the generator.
