### ISSUE TITLE
Remove `responseBody` from Snazzy and Wice Adapter Schemas

### ISSUE THREAD

**Issue by weberjm** [openintegrationhub/openintegrationhub#1314]
In schemas provided in the Wice and Snazzy Contacts adapters, each schema starts with a root object called `responseBody`. This does not appear in current components generated from the component generator, nor is it a standard key in OpenAPI 3.x or 2.x (Swagger) documents.

For efficient interaction with schemas in flows, these root keys should be removed and replaced with whatever the "true" schema is which would be included under the `schema` key in an [OpenAPI / JSON Schema document](https://swagger.io/docs/specification/describing-responses/).

**Comment by jkopen** [comment]
Schemas changed as discussed with james
