### ISSUE TITLE
Allow update fields of the different auth types

### ISSUE THREAD

**Issue by russojrv-zz** [openintegrationhub/openintegrationhub#1334]
**In the OIH framework, right now, it only allows you to update the auth client basic fields from its schema. In case, you want to update some no common fields you cannot**

- Allow update fields from different types of auth types
- One limitation is that you have to be sure that you send the auth type in the body

**Solution Proposal**

`const result = await AuthClient[data.type].findOneAndUpdate({
            _id: id,
        }, updateOperation, {
            new: true,
        }).lean();`

**Comment by heggert** [comment]
Please checkout https://github.com/openintegrationhub/openintegrationhub/pull/1336
