### ISSUE TITLE
Initial master admin password in IAM

### ISSUE THREAD

**Issue by sachmerz** [openintegrationhub/openintegrationhub#134]
As an operator of IAM I do not want to risk forgetting to change my master admin password, which is why it should be auto generated on setup and printed to stdout.

**Acceptance Criteria:**
- [x] master admin and default service account passwords are dynamically generated on initial setup
- [x] jwt secret is dynamically generated on initial setup if no env var with a secret value is provided
- [x] passwords are printed to stdout on startup
- [x] password is valid and the admin/service account can log into IAM

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
By whom do you need feedback @sachmerz ?

**Comment by philecs** [comment]
who do you need feedback from @sachmerz ?

**Comment by sachmerz** [comment]
@philecs we will review this issue internally, but any additional reviewers willing to look into this are welcomed.
