### ISSUE TITLE
Component/Connector LOG_LEVEL configuration too verbose

### ISSUE THREAD

**Issue by winklerj** [openintegrationhub/openintegrationhub#1344]
**Description**
The component LOG_LEVEL environment variable is hard coded to `trace` in the component orchestrator https://github.com/openintegrationhub/openintegrationhub/blob/master/services/component-orchestrator/src/drivers/kubernetes/KubernetesDriver.js#L380.  This is a too verbose setting for production environments.

**Solution Proposal**

Ideally this LOG_LEVEL is configurable or uses the component orchestrator LOG_LEVEL environment. At a minimum not setting the LOG_LEVEL environment variable will return it to the default `info` level set in ferryman.

I'm open to other solutions as well. If there is another setting available to do this, I may just be missing it in the code.

**Comment by weberjm** [comment]
This issue is fixed by #1345.
