### ISSUE TITLE
Update Snazzy and Wice Components to support OIH Secrets

### ISSUE THREAD

**Issue by weberjm** [openintegrationhub/openintegrationhub#1369]
Currently, the Snazzy and Wice components use their own authentication methods which are required to be passed in the node configuration for a flow. The variable names which have been chosen to pass in the flow do not match those which would be returned by our secret types from the Secret Service. Please update the two components to integrate with the naming conventions of the rest of the framework, and to accept secrets which are loaded through the standard "credentials id" lookup.

- [x] Change basic secrets to support "username" and "passphrase" in the secret value
- [x] Change API Key authorization to support passing "key" instead of "apiKey" to the component
- [x] Update component to use the secret as passed in from ferryman, not just through direct configuration

**Comment by SvenHoeffler** [comment]
The components will now use any provided `key` apiKey
