### ISSUE TITLE
[SKM] Configure, build and deploy the service in cluster

### ISSUE THREAD

**Issue by sachmerz** [openintegrationhub/openintegrationhub#137]
As a OIH operator I want SKM to be deployed in the OIH k8s cluster.

---

**Acceptance Criteria:**
- [x] Dockerfile and k8s files exist
- [x] SKM service is deployed into OIH k8s cluster

**Comment by philecs** [comment]
How is the status here?

**Comment by philecs** [comment]
@heggert how is the status here?
