### ISSUE TITLE
Finalize Flow Repository Specification

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#138]
As a _user type_, I want to _task_ so that _goal_.

**Further description:**

Current status of specification : [flow repo concept](https://app.swaggerhub.com/apis/drobiazko/flows-repository/0.0.3)

- [ ] Make sure service is matching services guidelines

---

**Acceptance Criteria:**
- [ ] Specifications meet service guidelines

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
See #144

**Comment by philecs** [comment]
In the current version of [flow repo concept](https://app.swaggerhub.com/apis/drobiazko/flows-repository/0.0.3) :
- There is no [error status code for `flows`](https://github.com/openintegrationhub/openintegrationhub/blob/master/Guidelines/ServiceAPIGuidelines.md#may-any-object-may-have-many-owners) specified. Only 200 is specified.
- Status code 410 is not defined for **delete** `flows/{flowId}`

**Comment by drobiazko** [comment]
thank you for comments. will apply them in 0.0.5

btw the most recent version is 0.0.4: https://app.swaggerhub.com/apis/drobiazko/flows-repository/0.0.4

**Comment by drobiazko** [comment]
I think we should remove the requirement for returning 410 on delete requests. If the resource has been deleted we don't really know if it ever existed.

Which resource exactly do you mean by?

> There is no error status code for flows specified. Only 200 is specified.

**Comment by philecs** [comment]
Agree with the 410 suggestion - I had similar thoughts.

> Which resource exactly do you mean by?

I'm talking about this one:
https://app.swaggerhub.com/apis/drobiazko/flows-repository/0.0.4#/flows/getFlows

There is only status code ´200´ defined. According to the guidelines we need to define a 404 for collections, in case the collection is missing.

**Comment by drobiazko** [comment]
404 makes only sense for GET resources that retrieve entities by concrete IDs. We need to make it more clear in the guidelines. Can you create an issue for the 2 changes please and assign it to me?

**Comment by philecs** [comment]
I already created a pull request to delete 410. We can use this PR to incorporate all changes.
Will add another issue for the GET status codes.

**Comment by philecs** [comment]
https://app.swaggerhub.com/apis/drobiazko/flows-repository/0.0.5 current version

**Comment by philecs** [comment]
@drobiazko we have the `MISC` API here but not enpoints defined (https://app.swaggerhub.com/apis/drobiazko/flows-repository/0.0.5#/Misc). Do we need this one?

**Comment by drobiazko** [comment]
Fixed: https://app.swaggerhub.com/apis/drobiazko/flows-repository/0.0.6#/

**Comment by philecs** [comment]
@drobiazko do we need to further specify this API or is it finalized?
