### ISSUE TITLE
Implement MVP of Resource Coordinator

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#140]
As a _user type_, I want to _task_ so that _goal_.

**Further description:**

---

**Acceptance Criteria:**
- [ ] Resource Coordinator is published as first developer release
- [ ] Service is able to start flows on demand (does not necessarily stop the flow)

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by pnedelko** [comment]
Closing in favour of #177 and #178.
