### ISSUE TITLE
Discuss Scope of CRUD Monitoring

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#141]
As a _user type_, I want to _task_ so that _goal_.

**Further description:**

The need for a CRUD Monitoring service needs to be clarified. It is possible that an audit log is needed instead of a CRUD Monitoring.

- [x] Discuss need and scope the service
- [ ] Document a possible service for audit logging

---

**Acceptance Criteria:**
- [ ] First documentation of scope of the service

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by sachmerz** [comment]
We will discuss this issue with @hschmidthh in the beginning of upcoming week.

**Comment by hschmidthh** [comment]
We did have a call on Monday and clarified the scope and the requirements for audit logging. Next up we will describe the outcome from our call

**Comment by hschmidthh** [comment]
You can read the concept of the "Audit Log"-Service in the Microservice-Repo:
https://github.com/openintegrationhub/Microservices/blob/AuditLogConcept/ManagementServices/AuditLog.md

**Comment by philecs** [comment]
What is the status here? I know there was an ongoing discussion about the CRUD monitoring between Jürgen and Falk last week.

**Comment by hschmidthh** [comment]
> What is the status here? I know there was an ongoing discussion about the CRUD monitoring between Jürgen and Falk last week.

I need a feedback to the audit log concept.

**Comment by philecs** [comment]
Falk already provided feedback to Jürgen. Currently we do not have it documented but he should be able to provide you insights. If additional feedback is needed I would suggest to talk to @falkvoigt

**Comment by falkvoigt** [comment]
Hi we should have a call for that to discuss the Problems related to that?

**Comment by hschmidthh** [comment]
> Hi we should have a call for that to discuss the Problems related to that?

We will have a call tomorrow and then update the concept.

**Comment by jschuesslerhh** [comment]
In the workgroup privacy & security last week we talked about the Auditlog. I presented the actual concept of CRUD and we talked about that there is an actual discussion to change the CRUD into an Auditlog. We talked about some questions:

- do we need a central Auditlog or should every service manage their own logs
- is it necessary to store raw data in the Auditlog and what does it mean for privacy & security aspects.

The workgroup suggested:

1. An Auditlog is an usefull feature for privacy an security aspects.
2. Storing of raw data shoud be temporarely limited.

**Comment by hschmidthh** [comment]
We did have a call on friday and agreed to broaden the scope from user audit only to a general logging and monitoring scope. An update on the concept and testing of the tools is on its way.

**Comment by hschmidthh** [comment]
Please have a look at the extended concept for Logging & Monitoring. Feedback is appreciated ;-)
https://github.com/openintegrationhub/Microservices/blob/AuditLogConcept/ManagementServices/AuditLog.md

**Comment by philecs** [comment]
@hschmidthh Thanks for the concept. Was this concept already discussed with all main implementation partners? If not, I would ask you to proactively contact all partners and maybe setup a call to discuss the concept. This way you will get feedback a lot faster.

**Comment by hschmidthh** [comment]
As discussed, we deployed the ELK-Stack and evaluated it. So now we can provided some pro and cons of both, an audit logging service based on the CRUD-Monitoring prototype and with the tools from the ELK-Stack. You can find it here:
https://github.com/openintegrationhub/Microservices/blob/AuditLogConcept/ManagementServices/ComparisonELKStackCRUDMonitoring.md
Next we should consider how to move on.
