### ISSUE TITLE
Webhooks HMAC Auth Not Working

### ISSUE THREAD

**Issue by BirdHighway** [openintegrationhub/openintegrationhub#1452]
**Describe the bug**
When using HMAC auth for a flow all requests sent to the webhooks services return a `500 Internal Server Error` error.

**Expected behavior**
When using HMAC auth for a flow:
- requests sent to webhook service should be rejected if they lack a valid HMAC header
- requests sent to webhook service should be accepted if they have a valid HMAC header

**To Reproduce**

- Create an API Key secret with a value of `12345`
- Create a flow that uses HMAC auth, specifying the id of the secret created above
- Start flow
- Send message to flow
  - Create message body `{"abc":123}`
  - Calculate HMAC for body using key created above, SHA-256 hash function, output to base64
    - [calculate hmac online](https://www.devglan.com/online-tools/hmac-sha256-online)
    - expected value `gHPCbdbiBH+2TbRx+jM9UC6snDdDxBrw9Bck4h7zewo=`
    - set as value under request header `X-Hmac-SHA256`
-  The request will be rejected

Secret Data (abbreviated)
```json
{
  "value": {
    "key": "12345"
  },
  "_id": "62dffbe8f1ed67f9eac3f9ca",
  "name": "HMAC Key",
  "type": "API_KEY"
}
```

Flow Data (abbreviated)
```json
{
  "name": "HMAC Example Flow",
  "graph": {
    "removed for brevity":"..."
  },
  "flowSettings": {
    "webhooks": {
      "hmacAuthSecret": "62dffbe8f1ed67f9eac3f9ca",
      "requireWebhookAuth": true,
      "hmacHeaderKey": "X-Hmac-SHA256"
    }
  }
}
```

Request:
```sh
curl --location --request POST 'http://webhooks.example.com/hook/62dffc6d667ffa180c1c86c0' \
  --header 'X-Hmac-SHA256: gHPCbdbiBH+2TbRx+jM9UC6snDdDxBrw9Bck4h7zewo=' \
  --header 'Content-Type: application/json' \
  --data-raw '{"abc":123}'
```

Response:
```http
HTTP/1.1 500 Internal Server Error
Date: Tue, 26 Jul 2022 15:51:54 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 57
Connection: keep-alive
Vary: Origin
Access-Control-Allow-Credentials: true
ETag: W/"39-IvvnrLrqcQqmyk4cnGNn3OG58x4"

{"error":"Request with GET/HEAD method cannot have body"}
```

Response if the HMAC header is left off:
```http
HTTP/1.1 403 Forbidden
Date: Tue, 26 Jul 2022 15:56:33 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 24
Connection: keep-alive
Vary: Origin
Access-Control-Allow-Credentials: true
ETag: W/"18-XPDV80vbMk4yY1/PADG4jYM4rSI"

{"error":"Unauthorized"}
```

**Your OIH Setup Information**
- Environment: minikube
- Secret Service Image: openintegrationhub/secret-service:22.1.0
- Webhooks Service Image: openintegrationhub/webhooks:22.1.0

**Additional context**
I had previously stated that I had tested the HMAC auth functionality and verified that it was working, but I believe that I was mistaken.

**Comment by weberjm** [comment]
Fixed through PR #1453
