### ISSUE TITLE
Using the workflow builder in web-ui does not properly create a new flow to work on

### ISSUE THREAD

**Issue by weberjm** [openintegrationhub/openintegrationhub#1457]
While researching #1455, I discovered that launching the visual builder for flows does not correctly instantiate a new flow to work on. The UI appears to:
- Create a new flow in the system using the "basic" initial flow data
https://github.com/openintegrationhub/openintegrationhub/blob/cc6969ab25db22dc3a2e4b148c834a730dfd3e51/services/web-ui/src/component/flows/index.js#L91-L109
- Then sets the flow id to the last flow in its array. I always end up on flow 5f7479c90694fc001bc34775, but the loading script uses 
https://github.com/openintegrationhub/openintegrationhub/blob/cc6969ab25db22dc3a2e4b148c834a730dfd3e51/services/web-ui/src/component/flows/index.js#L120
which *might* give a different result for each user.

Therefore, every time I try to "add a flow" using the visual builder button, I create a "dummy" flow, then work on the flow listed above, never editing the new flow.

The behavior here should be changed in the following ways:
- The flow should not be "created" until saving the visual builder; it currently creates a flow on launching the builder, and even if the user then exits out without saving, the flow is persisted
- Load the correct flow into the visual builder when launched: the referenced flow when launched from an existing flow, or a set of "dummy" data that does NOT include an ID when launched to create a new flow
- All "initial" and "dummy" data should match, so that the user sees and saves the same data (see the presence of both `dummyData` and `initialFlow` in https://github.com/openintegrationhub/openintegrationhub/blob/master/services/web-ui/src/component/flows/index.js

**Comment by sachmerz** [comment]
Fixed
