### ISSUE TITLE
Allow passing configurable environment variables to a component

### ISSUE THREAD

**Issue by winklerj** [openintegrationhub/openintegrationhub#1474]
Currently the KubernetesDriver has full control over what Environment variables are added to a component deployment in Kubernetes.  You can currently only provide per flow configurations to the component. There are times when a component requires configuration which is specific to the environment in which it resides and you want it to be configured across flows without
duplicating in the flow configuration.

What open problem requires a solution?

As a SaaS provider, I want to create a custom component and inject configuration into a component through environment variables so that I don't have to configure the value on every single flow and expect flow creators to remember to enter it every time.

**Benefits of the new feature**

**Possible Solutions**

Allowing to specify an environment variable in the component repository definition. This could be `{"MYVAR": "static value"}`. You would then leave it to the component as to what you want to do with it. Examples could be a URI or JSONata expression which the component uses.

**Comment by weberjm** [comment]
This seems a reasonable request. Currently, we get a few properties out of the 'component.descriptor' section of the component object. 

https://github.com/openintegrationhub/openintegrationhub/blob/ad22eb4d4962983e19e379903f07e63a3a0faf86/services/component-orchestrator/src/drivers/kubernetes/KubernetesDriver.js#L270-L274

Something similar could be implemented, or something like in the __prepareResourcesDefinition()_ function, which can pull from the component, node, flow, or base config

https://github.com/openintegrationhub/openintegrationhub/blob/ad22eb4d4962983e19e379903f07e63a3a0faf86/services/component-orchestrator/src/drivers/kubernetes/KubernetesDriver.js#L404

**Comment by winklerj** [comment]
I'm going to take a stab at implementing this
