### ISSUE TITLE
Component Orchestrator is publishing directly to component queues instead of the exchange

### ISSUE THREAD

**Issue by winklerj** [openintegrationhub/openintegrationhub#1491]
**Describe the bug**
While trying to subscribe to the `component-events-collector` exchange topic or a component-specific topic, I noticed there were no messages put into the queues bound to the topic.  After investigating I discovered that while the topic(s) exists and is setup to route messages appropriately, the component specific topics are not used to publish events.  Instead the messages are published directly to the component queue.

This prevents the messages from being fanned out and can only be consumed by the component container.  It appears there was intention to be able to fan out the messages, but are just incorrectly published.  Or this is possibly left over from the move from local to global components?

The relevant component-orchestrator code is located here: https://github.com/openintegrationhub/openintegrationhub/blob/master/lib/component-orchestrator/src/ComponentOrchestrator.js#L555

**Expected behavior**
When subscribing to the component-specific topic in the RabbitMQ exchange, which is created by the component-orchestrator in the format of `component-1234567890abcdef` or `flow-1234567890abcdef`, you should receive the messages sent from the component-orchestrator to the component which will execute the task.

**To Reproduce**

1. Subscribe to the RabbitMQ component-specific topic (Ex. `component-1234567890abcdef` or `flow-1234567890abcdef`)
2. Start a flow in the OIH flow repository (if using global components, make sure they are started as well)
3. Execute the flow
4. Notice that no messages are received

**Screenshots**
Exchange topics created by OIH. This example is for global components. The component or flow specific topics are not used
![Screenshot 2023-09-18 at 10 54 59 AM](https://github.com/openintegrationhub/openintegrationhub/assets/1112493/0b7129e8-1a9c-4ed9-a4a4-de99943fe42b)

The component-specific topic bindings:
![Screenshot 2023-09-18 at 10 55 53 AM](https://github.com/openintegrationhub/openintegrationhub/assets/1112493/3786a943-9def-4b3d-96c7-440c24353922)

**Your OIH Setup Information**
I see the problem in the current version 23.0.0 referenced in the code link above.

**Additional context**
I would appreciate any insight into whether this was done intentionally because of some constraint or whether this is something that can be easily fixed.  My concern is that there are some known side effects from publishing to the topic instead of the queue directly.

**Comment by weberjm** [comment]
Hi @winklerj, from reviewing the relevant file history, the specific implementation you are talking about was indeed added during the shift to global components. It is possible that this was copied over from the previous implementation from local components. I think that it should work to update to exchange routing, as intended by _amqp_. 

@SvenHoeffler might be the only person active in the project who could have any further insights into these decisions. Anything to add?
