### ISSUE TITLE
Review Webhooks and Communication Router

### ISSUE THREAD

**Issue by sachmerz** [openintegrationhub/openintegrationhub#170]
Review the service, bootstrap them and provide feedback.

---

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
Added feedback:

https://github.com/openintegrationhub/openintegrationhub/issues/206
https://github.com/openintegrationhub/openintegrationhub/issues/205
https://github.com/openintegrationhub/openintegrationhub/issues/204
https://github.com/openintegrationhub/openintegrationhub/issues/203
https://github.com/openintegrationhub/openintegrationhub/issues/195
https://github.com/openintegrationhub/openintegrationhub/issues/8

**Comment by sachmerz** [comment]
Similar to the Feedback von @fdegenhr in #260, the services require a reference implementation and need to be connected to other services. @drobiazko has already created the corresponding epic #262
