### ISSUE TITLE
Test integration content repository

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#173]
The current ICR needs to be tested to secure that it is working properly.

- [x] Define Use Cases for ICR
- [x] Derive Test Cases from Use Cases
- [x] Perform tests for ICR
- [x] Check specifications according to [API Service Guidelines](https://github.com/openintegrationhub/openintegrationhub/blob/master/Guidelines/ServiceAPIGuidelines.md)

---

**Acceptance Criteria:**
- [x] API specs reviewed
- [x] Use Cases described
- [x] Test Cases described
- [x] Test Report created

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by DennisCES** [comment]
Currently, there are some issues to be solved first, like: "Access to fetch at 'http://icr.openintegrationhub.comicr.openintegrationhub.com/healthcheck' from origin 'http://icr.openintegrationhub.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."

**Comment by philecs** [comment]
Test Case Template:

|Test Case ID|Test Scenario|Test Steps|Test Data|Expected Results|Actual Results|Pass/Fail|
|---|---|---|---|---|---|---|
||||||||

**Comment by philecs** [comment]
Use Cases: 

| Name |Get all flows|
| --- | --- |
| Purpose/Goal | As a user I want to retrieve all my own flows |
| Category | Primary |
| Pre-condition | User login was successful and is authorized |
| Post-condition (success) | User can see all flows |
| Post-condition (failure) | User cannot see flows |
| Actors | User |
| Triggering Event | User wants to see flows |
| Description/Workflow |1. Call function „Get all flows" <br> 2. All flows will be displayed/listed (200)|
| Extensions | 1a. Call function with parameter |
| Alternatives (optional) | 1a.1 Parameter invalid <br>2a. Flow(s) not found (404) |

| Name |Add a new flow|
| --- | --- |
| Purpose/Goal | As a user I want to add a new flow |
| Category | Primary |
| Pre-condition | User login was successful and is authorized |
| Post-condition (success) | A new flow is created |
| Post-condition (failure) | No flow could be created |
| Actors | User |
| Triggering Event | User wants to add a new flow |
| Description/Workflow |1. Call function „Add a new flow to the repository" <br> 2. A new flow is added (201)|
| Alternatives (optional) | 5a. Flow already exists<br> 5b. Flow is not added |

| Name |Find a flow by its id|
| --- | --- |
| Purpose/Goal | As a user I want to find a flow by its id |
| Category | Primary |
| Pre-condition | User login was successful and is authorized |
| Post-condition (success) | Flow was found |
| Post-condition (failure) | Not found |
| Actors | User |
| Triggering Event | User wants to find a flow by its id |
| Description/Workflow |1. Call function "Find flow by ID" <br> 2.Flow was found (200)|
| Alternatives (optional) | 2a. Flow not found (404) |

| Name |Delete a flow by its id|
| --- | --- |
| Purpose/Goal | As a user I want to delete a flow by its id |
| Category | Primary |
| Pre-condition | User login was successful and is authorized |
| Post-condition (success) | Flow is deleted |
| Post-condition (failure) | Flow is not deleted |
| Actors | User |
| Triggering Event | User wants to delete a flow by its id |
| Description/Workflow |1. Call function "Delete" <br> 2. Flow is deleted (200)|
| Alternatives (optional) | 2a. Flow id is invalid (400) <br> 2b. Flow not found (404) |

| Name |Patch a flow by its id|
| --- | --- |
| Purpose/Goal | As a user I want update a flow by its id |
| Category | Primary |
| Pre-condition | User login was successful and is authorized |
| Post-condition (success) | Flow is updated |
| Post-condition (failure) | Flow not updated |
| Actors | User |
| Triggering Event | User wants to update a flow by its id |
| Description/Workflow |1. Call function "Patch" <br> 2. Flow is updated (200) |
| Alternatives (optional) | 2a. Flow not found (404) |

**Comment by philecs** [comment]
@SvenHoeffler according to the serviceAPIGuidelines some changes are needed (issue with change requests will be created afterwards):

- root structure must have `data` and `meta`
- Schema definition for `flows` must be redefined. See [current version of definition](https://github.com/openintegrationhub/openintegrationhub/blob/master/services/integration-content-repository/app/api/swagger/swagger.json#L123) vs.  [guideline: schemas for collection of objects](https://github.com/openintegrationhub/openintegrationhub/blob/master/Guidelines/ServiceAPIGuidelines.md#must-not-to-contribute-to-schema-explosion-by-defining-schemas-for-collections-of-objects)
- Default sort order (parameter for `/flows`) should be ascending. Currently its descending.

**Comment by DennisCES** [comment]
Test Cases:

| Test Case ID | Test Scenario | Test Steps | Test Data | Expected Result | Actual Result | Pass/Fail |
| --- | --- | --- | --- | --- | --- | --- |
| 1 | Get all flows |- Call http://icr.openintegrationhub.com/flows | 3 created flows | All flows for user displayed | 3 flows  | PASS |
| 2 | |- Call http://icr.openintegrationhub.com/flows?page[size]=1 |   | All flows for user displayed |   | PASS  |
| 3|   |- Call [http://icr.openintegrationhub.com/flows?page[size]=n](http://icr.openintegrationhub.com/flows?page%5bsize%5d=n) |   | Invalid param. | invalid param.  | PASS  |
|   4|   |- Call http://icr.openintegrationhub.com/flows?page[number]=1 |   |   |  all flows | PASS   |
|   5|   |- Call [http://icr.openintegrationhub.com/flows?page[number]=n](http://icr.openintegrationhub.com/flows?page%5bnumber%5d=n) |   | Invalid param. |  Invalid param. |  PASS  |
|   6|   |- Call [http://icr.openintegrationhub.com/flows?page[has\_draft]=1](http://icr.openintegrationhub.com/flows?page%5bhas_draft%5d=1) |   |   |   | OPEN  |
|  7 |   |- Call [http://icr.openintegrationhub.com/flows?page[has\_draft]=n](http://icr.openintegrationhub.com/flows?page%5bhas_draft%5d=n) |   | Invalid param. |   | PASS  |
|8   |   |- Call [http://icr.openintegrationhub.com/flows?page[status]=1](http://icr.openintegrationhub.com/flows?page%5bstatus%5d=1) |   |   |   |  OPEN |
|  9 |   |- Call [http://icr.openintegrationhub.com/flows?page[status]=n](http://icr.openintegrationhub.com/flows?page%5bstatus%5d=n) |   | Invalid param. |   |  PASS |
|   10|   |- Call [http://icr.openintegrationhub.com/flows?page[type]=1](http://icr.openintegrationhub.com/flows?page%5btype%5d=1) |   |   |  ordinary | PASS  |
|   10|   |- Call [http://icr.openintegrationhub.com/flows?page[type]=1](http://icr.openintegrationhub.com/flows?page%5btype%5d=1) |   |   | long_running  | OPEN  |
|   11|   |- Call [http://icr.openintegrationhub.com/flows?page[type]=n] |   | Invalid param. |   | PASS |
|   12|   |- Call [http://icr.openintegrationhub.com/flows?page[user]=1](http://icr.openintegrationhub.com/flows?page%5buser%5d=1) |  User from 3 flows above |   |   |  PASS |
|  13 |   |- Call [http://icr.openintegrationhub.com/flows?page[user]=n](http://icr.openintegrationhub.com/flows?page%5buser%5d=n) |   | Invalid param. |   | PASS  |
|   14|   |- Call [http://icr.openintegrationhub.com/flows?sort=1](http://icr.openintegrationhub.com/flows?sort=1) |   | Invalid param. |   |  PASS |
|   15|   |- Call [http://icr.openintegrationhub.com/flows?sort=name](http://icr.openintegrationhub.com/flows?sort=name) |   | Sorted by name(asc) |   | PASS |
|   16|   |- Call [http://icr.openintegrationhub.com/flows?sort=createdAt](http://icr.openintegrationhub.com/flows?sort=createdAt) |   | Sorted by createdAt |   | PASS |
|   17|   |- Call http://icr.openintegrationhub.com/flows?sort=updatedAt |   | Sorted by updatedAt |   |   |
|   18|   |- Call [http://icr.openintegrationhub.com/flows?sort=-name](http://icr.openintegrationhub.com/flows?sort=-name) |   | Sorted by name(desc) |   | OPEN  |
|   19|   |- Call [http://icr.openintegrationhub.com/flows?sort=-createdAt](http://icr.openintegrationhub.com/flows?sort=-createdAt) |   | Sorted by name(desc) |   |   |
|   20|   |- Call http://icr.openintegrationhub.com/flows?sort=-updatedAt |   | Sorted by name(desc) |   |  OPEN |
|   21|   |- Call http://icr.openintegrationhub.com/flows?search=flow | "My Flow"  | Flows with &quot;flow&quot; in name or description |   | PASS  |
| 22 | Add a new flow |- Call http://icr.openintegrationhub.com/flows | Valid request body | Request body |   |  PASS |
|  23 |   |- Call http://icr.openintegrationhub.com/flows | Invalid request body |   | Invalid request body  | PASS  |
| 24 |  Find a flow flow by its id |- Call http://icr.openintegrationhub.com/flows/1 |  5c6fc0d86208ac569e3fa255 | Flow with id1 |   | PASS  |
| 25 | Delete a flow by its id |- Call http://icr.openintegrationhub.com/flows/1 |  5c6fc0d86208ac569e3fa255 | Flow 1 deleted |   | PASS  |
| 26 | Patch a flow by its id |- Call http://icr.openintegrationhub.com/flows/1 | Valid updated request body | Updatedrequested body | Updatedrequested body  |  PASS |

**Comment by DennisCES** [comment]
* Perform tests for ICR : not possible because of `Token invalid. Error: JsonWebTokenError. Details: jwt issuer invalid. expected: https://www.example.com` as response body @SvenHoeffler @falkvoigt
