### ISSUE TITLE
Define and setup pipeline

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#174]
As a quality manager I want to have a defined pipeline so that services are automatically built and deployed.

**Further description:**
We need to setup circleCi and our pipeline.

- [x] Setup CircleCI
- [x] Setup Build & Deployment Pipeline
- [x] Setup status checks for pull requests

---

**Acceptance Criteria:**
- [x] CircleCi integrated
- [x] Pipeline was set up
- [x] Status checks created

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
Dennis added circleci folder and sample config.yml : https://github.com/openintegrationhub/openintegrationhub/tree/DennisCES-circleCi/.circleci

**Comment by DennisCES** [comment]
config.yaml is added initially. @pnedelko will start to contribute elastic.io specific code (pipeline jobs etc), afterwards, Wice/Basaas can add and adapt this code with their service-specific build/test stages

**Comment by DennisCES** [comment]
@falkvoigt and @pnedelko told me, that they are totally fine with travis atm, hence, @hschmidthh: circleCI is ready and connected to github. In order to you help getting started; code stub from elastic.io is added and you just have to replace it with your service specific test code

**Comment by DennisCES** [comment]
Update: tbd: add build and deploy stages to the pipeline

**Comment by DennisCES** [comment]
As discussed with @falkvoigt, @SvenHoeffler and @pnedelko, we agreed on using a centralized pipeline, which means that every dev partner will provide their own ENV for their own test stage but build- and deploy stage will be used commonly by all

**Comment by DennisCES** [comment]
Decision(s) regarding this and former agreements can be found in the guidelines: https://github.com/openintegrationhub/openintegrationhub/blob/master/Guidelines/Build%20and%20deploy%20process%20documentation.md

**Comment by philecs** [comment]
Pipeline works now. Test stages for services that lack them need to be defined.
