### ISSUE TITLE
Remove elasticio rest API client usage from node.js sdk

### ISSUE THREAD

**Issue by pnedelko** [openintegrationhub/openintegrationhub#179]
As of now the `component-sdk-nodejs` is bound to the e.io rest client (`elasticio-rest-node`). Therefore the `sdk` is quite tightly coupled to a certain environment, because you need to make sure, that components have access to the `elastic.io`-like API to function properly ([see in code](https://github.com/openintegrationhub/component-sdk-nodejs/blob/master/lib/sailor.js#L38)).

Possible solutions:
1. Replace `elasticio-rest-node` usages by calls to some well defined API.
2. Provide `sdk` with a needed data in some other way.

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by jhorbulyk** [comment]
One possible way to do this is through [interfaces](https://en.wikipedia.org/wiki/Protocol_(object-oriented_programming)) and [dependency injection](https://en.wikipedia.org/wiki/Dependency_injection).  The diagram below demonstrates the idea.

![oih interface pattern](https://user-images.githubusercontent.com/5710732/49721202-feb37080-fc61-11e8-813d-21ce4bd88cf2.png)

The idea is that the logic is broken down into 4 parts:
1. There is a libary which describes the interfaces but contains no logic. (Interfaces include things like *publishMessage()* and *retreiveFlowDefinition()*)
2. There is a component which references the interface library and interacts with the platform through the interfaces while being platform agnostic.
3. For every platform, there is a library which implements the OIH defined interfaces in a platform specific way.
4. For every platform, there is an executable *sailor* which references both the component and the platform specific implementation and injects the platform specific implementation into the component library.

JavaScript unfortunately doesn't have native implementation of interfaces but the following options are possible:
* Use an interface construction such as [Implement.js](https://github.com/Jahans3/implement.js)
* Use a base class full of No-ops using JavaScripts built in class support
* Describe the interfaces only in human readible from and not machine readable form

**Comment by RobinBrinkmann** [comment]
With the use of ferryman this issue has been solved for OIH setups.
