### ISSUE TITLE
REST API webhooks

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#180]
As a product manger I want to have specifications for each service that should expose an REST API, so that it can be documented on swaggerhub.

**Further description:**

Had a talk with @drobiazko a few weeks ago who said that there will be a REST API for communication router.

- [ ] Publish API docs on github

---

**Acceptance Criteria:**
- [ ] API docs published on github

---

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by RobinBrinkmann** [comment]
all services that need to be accessed via an api do have an api description by now.
