### ISSUE TITLE
Create technical documentation for component orchestrator

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#186]
As product manager I want a technical documentation of the service, so that others are able to use and deploy it.

---

**Acceptance Criteria:**
- [x] Documentation of features and functions of the service
- [x] Deployment and operation guidelines
- [ ] API documentation (Swagger/OpenAPI)

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
@pnedelko please set an estimate for this issue

**Comment by pnedelko** [comment]
There are 2 endpoints:

1. Internal one, which is not supposed to be exposed to the outside of the cluster. This endpoint is for running containers with flow nodes.
2. /healthcheck - also just internal one.

Do we need Swagger docs for them?

**Comment by philecs** [comment]
I guess we need a swagger doch but I also think we should discuss this point on Wednesday. I wrote a reminder for myself.

**Comment by SvenHoeffler** [comment]
When we were attempting to deploy our SnazzyContacts adapter in our local OIH cluster, our greatest challenge was configuring the dockerfile to the point where the Flow Node/Orchestrator could properly recognise the adapter, initialise it, and call its triggers/actions when necessary. 

For posterity, the solution was to have the entrypoint of the dockerfile point towards the elasticio sailor in the dependencies (e.g. `ENTRYPOINT ["node", "./node_modules/elasticio-sailor-nodejs/run.js"]`), and to call the trigger/action as part of the `command` field in the flow definition (i.e. `command: [IMAGE NAME]:[ACTION/TRIGGER]@[IMAGE TAG]`).

In the long term these steps will likely be automated through the use of the component repository, but until then it could be useful to have a documentation on how to build and use your own adapter docker images for the purposes of further development.
