### ISSUE TITLE
Move ICR build pipeline to CircleCi

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#189]
As a OIH dev, I want to have an individual pipeline for my services.

Further description:
To solve the conflict with build and deployment, we plan to create a single pipeline for each service in the monorepo so that each partner can define and use an individual pipeline for her service.

---

**Acceptance Criteria:**
- [ ] ICR build pipeline is moved to CircleCi

---

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
What is the status here?

**Comment by SvenHoeffler** [comment]
> What is the status here?

Tests ought to work now (the issue was an outdated dependency), building/pushing the image and deploying the service on k8s are yet to be added.

**Comment by SvenHoeffler** [comment]
All steps in the pipeline now ought to be functional for the ICR. Falk did the heavy lifting, anyway. :smile:
