### ISSUE TITLE
SetUp Build/Deploy Pipeline for Webhooks & Scheduler on CircleCi

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#190]
As a OIH dev, I want to have an individual pipeline for my services.

Further description:
To solve the conflict with build and deployment, we plan to create a single pipeline for each service in the monorepo so that each partner can define and use an individual pipeline for her service.

---

**Acceptance Criteria:**
- [x] Scheduler and communication router build pipeline is moved to CircleCi

---

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by pnedelko** [comment]
Initial pipeline has been set up. It runs only tests, doesn't build & deploy docker containers so far.
