### ISSUE TITLE
Communication Router/Webhooks should fetch flows from ICR

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#202]
**Further description:**

Currently Communication Router/Webhooks isn't independent of K8s CRD. See [FlowsDao.js](https://github.com/openintegrationhub/openintegrationhub/blob/master/services/communication-router/src/FlowsDao.js) It fetches flows from K8s CRD instead of integration content repository.

---

**Acceptance Criteria:**
- [ ] Communication Router/Webhooks is independent of K8s CRD and fetches flows from ICR

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by pnedelko** [comment]
@philecs this one will be solved by this: https://github.com/openintegrationhub/openintegrationhub/issues/288. Could we close this issue?
