### ISSUE TITLE
Add IAM_UTILS as dependency

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#208]
**Further description:**

Add IAM_UTILS as dependency.

Currently the IAM_UTILS code is fully inserted into the ICR. Instead it should be added as a dependency.

---

**Acceptance Criteria:**
- [x] IAM_UTILS has been added as dependency and additional  IAM_UTILS relating code has been removed from ICR service

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by SvenHoeffler** [comment]
Done.
