### ISSUE TITLE
Use IOC container to instantiate classes

### ISSUE THREAD

**Issue by pnedelko** [openintegrationhub/openintegrationhub#217]
As a developer, I want to use some IOC container so that I don't need to provide a long list of dependencies for each constructor.

---

**Acceptance Criteria:**
- [ ] New tests added
- [ ] All tests pass

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
What about this one @pnedelko ? I saw you added tests and you merged the PR. Is there anything left to do?

**Comment by pnedelko** [comment]
@philecs no. Sorry, forgot to close the issue.
