### ISSUE TITLE
Component orchestrator does not handle task failure

### ISSUE THREAD

**Issue by drobiazko** [openintegrationhub/openintegrationhub#22]
If component fails and k8s failed to start it within retries defined by standard restart policy, than component will be broken, and the whole flow will be broken

**Comment by anton-kotenko** [comment]
What to do:
- [ ] attach flow operator to k8s event stream
- [ ] watch for failed pods in loop to guarantee no event lost
- [ ] Implement flow  suspend if step failed to start after some amount of retires. Options: 1) implement restart backoff strategy in flow operator. 2) Use k8s pod auto restart mechanism. Option 1 is more flexible. Option 2 looks easier to implement
- [ ] flow suspension should be visible to end user in some way (e. g. add status  into crd)
- [ ] queues should not be deleted,  service accounts and docker secrets should not be deleted also.

**Comment by philecs** [comment]
@anton-kotenko  any updates here?

**Comment by anton-kotenko** [comment]
Hi @philecs
There are no updates, because this task is blocked by #32 and partially #28 And now i'm working on those blocker tasks.

**Comment by philecs** [comment]
Do we have an update for this issue?
