### ISSUE TITLE
Create  data hub specs

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#224]
**Further description:**

The requirement that were consolidated in #69  must be reviewed in regard to future implementation. 

- [ ] Create functionality description
- [ ] Create Swagger API specs

---

**Acceptance Criteria:**
- [ ] Master data service specs created incl. Swagger Specification

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
Very first draft: https://app.swaggerhub.com/apis/drobiazko/masterdata-service/0.0.1

**Comment by drobiazko** [comment]
Why is this one closed?

**Comment by philecs** [comment]
@drobiazko closed in favor of #397
