### ISSUE TITLE
Provide data hub requirements

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#237]
As a product manager I want to collect requirements from all stakeholder, so that a decision about the future implementation of the master data service can be made.

**Further description:**

- [ ] Provide requirements for master data service

---

**Acceptance Criteria:**
- [ ] Requirements communicated to @pnedelko 

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by pnedelko** [comment]
@hschmidthh I post the requirements you gave me to this issue as well.

## Wice GmbH – Data Hub Requirements
- Data Hub must be an optional feature of the OIH
- Data Hub should store the data in the Master Data Models provided from the different workgroups
- The Data Models are stored in the MetaData Repository
- Each entry in the Data Hub should be reachable by its OIH-DataRecord
- It should be possible to retrieve metadata informations without getting the whole record
- Nice to have would be integrated snapshot backup mechanisms
