### ISSUE TITLE
How does resource coordinator fetch flows?

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#244]
As oih operator I want to understand how the oih services interact to properly operate the framework.

**Further description:**

Imagine the following scenario:
1. Scheduler service knows that flow with id=3 should be started every 2 minutes
2. Scheduler pushed event/notfication that flow with id=3 should be started (e.g. to a bus)
3. Resource coordinator receive the message and will start the containers (flow nodes) specified in the information of the flow with id=3

**Question:** Where does the resource coordinator fetches the information about the flow (needed in step 3) from?

_Option 1:_ It hands over the id to integration content repository (icr) and gets the information from icr
_Option 2:_ Resource coordinator holds information about flows in his own database (duplicated because also existing in icr) 

- [ ] Create proposal with an answer to this question
- [ ] Discuss proposal with wice, basaas and ces
- [ ] Decide on how the resource coordinator fetches flows

---

**Acceptance Criteria:**
- [ ] Decision how rc fetches flows is made and documented

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by pnedelko** [comment]
@philecs this issue is going to be solved in the scope of this: https://github.com/openintegrationhub/openintegrationhub/issues/291. Lets close this one?
