### ISSUE TITLE
Service naming

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#245]
**Further description:**

Currently we have several names for one service. Therefore we need to agree upon only **one** name for each service.

- [x] Create an overview of all services incl. synonyms
- [ ] Discuss naming with partners
- [ ] Document final list of service names 

---

**Acceptance Criteria:**
- [ ] Workgroup agreed upon service names

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
Initial document:

https://github.com/openintegrationhub/Microservices/blob/serviceNaming/serviceNames.md

**Comment by philecs** [comment]
@sachmerz @drobiazko @hschmidthh please have a look at the service names so that we can shortly discuss them within this sprint

**Comment by philecs** [comment]
WIP: https://docs.google.com/spreadsheets/d/1eOsPSqIbt9wZweNFgUPBFzNRBKAkzAHyNWvgEXTXtgo/edit?usp=sharing

**Comment by hschmidthh** [comment]
We should regard the discussions about naming things in the other workgroups.

**Comment by philecs** [comment]
![servicenames](https://user-images.githubusercontent.com/29949654/53012644-dd31ea80-3443-11e9-8aa5-918861a4bc27.png)

**Comment by philecs** [comment]
Sercrets-Service should be Secret-Service. Wrong name in the graphic
