### ISSUE TITLE
Flow operator is using the same RabbitMQ credentials for itself and for flows

### ISSUE THREAD

**Issue by drobiazko** [openintegrationhub/openintegrationhub#25]
The flow operator requires privileges to create queues and exchanges in the virtual host. These component needs to read and push data only

**Comment by anton-kotenko** [comment]
- [x] Flow operator should use it's own credentials, provided in configuration.
- [x]  Fix installation descriptors for rabbitmq to ensure that 1. account for flow operator has privileges to create accounts 2. rabbitmq server has enabled management plugin and flow operator can connect and use it's api
- [ ] Flow operator should ensure account in rabbitmq for flow. Flow operator should use that account while creating descriptors for flow step jobs. Flow operator should remember that credentials inside of flow definition, to make possible to reuse them.

**Comment by philecs** [comment]
@anton-kotenko  any updates here?

**Comment by anton-kotenko** [comment]
Hi @philecs
There are no updates, because this task is blocked by #32 and partially #28 And now i'm working on those blocker tasks.
