### ISSUE TITLE
Audit Log Service needs Message Format

### ISSUE THREAD

**Issue by hschmidthh** [openintegrationhub/openintegrationhub#255]
For the Audit Log Service we need a definition of a message format

**Further description:**

Each microservice should deliver its own messages to the audit log service. Theses messages must have a common json-message. 

---

**Acceptance Criteria:**
- [x] Proposal for Message Format
- [ ] Proposal accepted

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
Fits better here (removed from other issue):
https://cloud.google.com/logging/docs/reference/audit/auditlog/rest/Shared.Types/AuditLog?hl=de

**Comment by hschmidthh** [comment]
We provided a first draft of a message format:
https://github.com/openintegrationhub/Microservices/blob/audit-requirements/ManagementServices/MessageFormat.md

**Comment by fdegenhr** [comment]
* I would prefer to use the timestamp instead of the MessageCount as a base for ordering

**Comment by philecs** [comment]
For clarification: What do you exactly mean with `EventLevel`?

**Comment by hschmidthh** [comment]
Added some example messages

**Comment by philecs** [comment]
In the ServiceAPIGuidelines we defined that date must be formatted according to [RFC 3339](https://github.com/openintegrationhub/openintegrationhub/blob/master/Guidelines/ServiceAPIGuidelines.md#should-date-property-values-should-conform-to-rfc-3339).In the documented is mentioned that **ISO 8601**. I'm currently not completely sure how this two formats overlap but we should consider to unify the format.

**Comment by hschmidthh** [comment]
> In the ServiceAPIGuidelines we defined that date must be formatted according to [RFC 3339](https://github.com/openintegrationhub/openintegrationhub/blob/master/Guidelines/ServiceAPIGuidelines.md#should-date-property-values-should-conform-to-rfc-3339).In the documented is mentioned that **ISO 8601**.

It means the same

**Comment by philecs** [comment]
@hschmidthh perfect, thanks

**Comment by philecs** [comment]
@hschmidthh is feedback missing here? Or is the message format accepted by the rest of the team?
