### ISSUE TITLE
Provide API-Specs for Audit Log

### ISSUE THREAD

**Issue by hschmidthh** [openintegrationhub/openintegrationhub#258]
We need an API-Spec for the Audit Log Service to establish the Audit Log Service.

**Further description:**

Before we move on with the next revision of the crud monitoring service, we need an API-Description in Swagger. 

---

**Acceptance Criteria:**
- [x] Swagger API-Description provided
- [ ] API-Description is accepted  by workgroup

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by hschmidthh** [comment]
Here is a first draft of the API-Specs. Please have a view
https://app.swaggerhub.com/apis/SvenHoeffler/AuditLogProposal/0.0.1#/logs/get_api_logs

**Comment by philecs** [comment]
@drobiazko @pnedelko @sachmerz FYI

**Comment by philecs** [comment]
According to guidelines: JSON property names must be [camelCase starting with a lower case letter](https://github.com/openintegrationhub/openintegrationhub/blob/master/Guidelines/ServiceAPIGuidelines.md#must-property-names-must-be-always-camelcase).

**Comment by philecs** [comment]
Should be `/logs` not `api/logs`

**Comment by philecs** [comment]
As timestamp is a date it should follow [RFC 3339](https://tools.ietf.org/html/rfc3339#section-5.6)

**Comment by philecs** [comment]
Payload root must contain [data & meta](https://github.com/openintegrationhub/openintegrationhub/blob/master/Guidelines/ServiceAPIGuidelines.md#must-root-object-may-contain-data-and-meta-only)

**Comment by philecs** [comment]
Not sure but I guess we need an owner array as well 

Additional acceptance criteria: 
- [ ] API Specs compliant with [ServiceAPIGuidelines](https://github.com/openintegrationhub/openintegrationhub/blob/master/Guidelines/ServiceAPIGuidelines.md)

**Comment by SvenHoeffler** [comment]
Adjusted the API according to the Guidelines, new version:
https://app.swaggerhub.com/apis/SvenHoeffler/AuditLogProposal/0.0.2#/

**Comment by philecs** [comment]
Structure of payload should be:

```JSON
{
    "data": {}
```
or
```JSON
{
    "data": []
```

Current structure:

```JSON
[
  {
    "data": {
```

**Comment by SvenHoeffler** [comment]
Fixed.
