### ISSUE TITLE
Remove copy & paste of CRD definition and creation

### ISSUE THREAD

**Issue by drobiazko** [openintegrationhub/openintegrationhub#26]
There are multiple services with a copy & paste for Flow CRD definition and creation in k8s.

# Flow operator

[CRD definition](https://github.com/openintegrationhub/openintegrationhub/blob/master/services/flows-operator/index.js#L15-L33) and [CRD creation](https://github.com/openintegrationhub/openintegrationhub/blob/master/services/flows-operator/index.js#L283).

# Scheduler

[CRD definition](https://github.com/openintegrationhub/openintegrationhub/blob/master/services/scheduler/index.js#L14-L32) and [CRD creation](https://github.com/openintegrationhub/openintegrationhub/blob/master/services/scheduler/index.js#L175).

# Communication Router

[CRD definition](https://github.com/openintegrationhub/openintegrationhub/blob/master/services/communication-router/index.js#L15-L33) and [CRD creation](https://github.com/openintegrationhub/openintegrationhub/blob/master/services/communication-router/index.js#L192).

**Comment by philecs** [comment]
Statement copied from discussion in #33 :

#26 is implemented in "draft mode". So I've unblocked myself for work on #32
