### ISSUE TITLE
Provide feedback regarding to scope of framework

### ISSUE THREAD

**Issue by fdegenhr** [openintegrationhub/openintegrationhub#260]
**Further description:**
Provide feedback for the framework deliverable regarding the usability as a framework.

---

**Acceptance Criteria:**
- [x] Feedback provided
---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by fdegenhr** [comment]
While the framework covers most of the logic flow of the services, there are many interface-like components containing only function stubs. e.g. https://github.com/openintegrationhub/openintegrationhub/blob/master/lib/resource-coordinator/src/InfrastructureManager.js

This possibility to change implementation details easily is good. 
The necessity to implement a lot of components to use the framework does not encourage a fast start with the framework.
A serious reference implementation for those parts should be part of the deliverable.

**Comment by philecs** [comment]
@pnedelko @drobiazko FYI
