### ISSUE TITLE
Integration Services Collaboration

### ISSUE THREAD

**Issue by drobiazko** [openintegrationhub/openintegrationhub#262]
At the moment we have following services ready and functional:

* `Scheduler`
* `Webhooks`
* `Flow Repository`
* `Resource Coordinator`

However, these services are not yet integrated. The scope of this epic is to provide integration between these services. 

The goal is to let services collaborate with each other without sending requests when some data is needed. Instead the services raise events when things change. The other services listen to these events and react appropriately. This style of collaboration is called [Event Collaboration](https://martinfowler.com/eaaDev/EventCollaboration.html). Now let's have a look at the following diagram showing the collaboration between the services mentioned above.

![oih_integration_events 1](https://user-images.githubusercontent.com/464220/51745965-df06c900-20a4-11e9-9093-1a94dd8e448b.png)

Now let's discuss the diagram above in a bit more details:

1. Client starts a flow using flow repository's REST API
2. `Flow Repository` sets the flow's `status` to `starting` and raises the event `flow.starting` 
3. There are 3 services listening to the event `flow.starting`:  Webhooks, Scheduler and Resource Coordinator. `Webhooks` and `Scheduler` examine the event's payload and decide if they need to react appropriately. We will discuss the exact reaction of both services later in this document.
4. Upon receiving `flow.starting` event the `Resource Coordinator` starts deploying the containers. Once all containers were deployed, `Resource Coordinator` raises the `flow.started` event.
5. `Flow Repository` receives the `flow.started` event and switches flow's `status` property from `starting` to `started`.
6. `Webhooks` receives the `flow.started` event and starts receiving incoming HTTP calls for the given flow.
7. `Scheduler` receives the `flow.started` event and starts scheduling the flow, according to it's cron property.
8. When a client stops a running flow using flow repository's REST API, the event `flow.stopping` is raised which is causing an inverse reaction chain of events.

Now let's discuss the individual services in details.

## Flow repository

We need to extend the API by the following resources:

* `POST /flows/{id}/start`: Used to start a flow
* `POST /flows/{id}/stop`: Used to stop a flow

Starting a flow means setting flow's `status` to `active` and raising `flow.starting` event. Stopping a flow means setting flow's `status` to `inactive` and raising `flow.stopping` event. The schema of the event payload is shown below.

```yaml
Event:
  type: object
  required:
    - headers
    - payload
  properties:
    headers:
      type: object
       required:
         - name
         - createdAt
      properties:
        name:
          type: string
        createdAt:
          type: string
          format: date-time
    payload:
      type: object
```

The `payload` property is an arbitrary object to be sent with the event. Flow repository will send the entire flow as `payload`. 

We also need to extend the `flow` model in the API by the following properties:

* ` id`: required
* `cron`: required for polling flows and defaults to `*/3 * * * *` if not set for a polling flow. Must not be set for a webhook flow.

## Webhooks

Upon receiving `flow.starting` event the service checks if the `isWebhook` property is set. If so, the service persist a data record in his local DB but **doesn't start receiving HTTP requests** for the given flow yet. The following table demonstrates an example of such records.

| flowId        | queue           | 
| ------------- |:-------------:|
| 58b41f5da9ee9d0018194bf3      | queue_58b41f5da9ee9d0018194bf3 | 
| 5b62c91afd98ea00112d5404      | queue_5b62c91afd98ea00112d5404      | 

After receiving the `flow.started` event, the service starts accepting incoming messages from the flow's webhook URL and sends them to the corresponding queues to be handled by flow nodes. This is actually how it is accomplished today. The only difference is that webhooks service is retrieving all the required data about a webhook flow from its local DB.

Please note that the webhooks service ignores the event if at least one of the following conditions is met:

*  `cron` property is present in the event

Upon receiving the `flow.stopping` event, the service deletes the record for the given flow and stops accepting requests.

## Scheduler

Upon receiving `flow.starting` event the service checks if the `cron` property is set. If so, the service persist a data record in his local DB, but **doesn't start scheduling** the given flow yet. The following table demonstrates an example of such records.

| flowId        | cron           |  dueExecution |
| ------------- |:-------------:|:-------------:|
| 58b41f5da9ee9d0018194bf3      | */3 * * * * | 2019-01-25T13:39:28.172 |
| 5b62c91afd98ea00112d5404      | 15 14 * * 1-5      |  2019-01-27T14:15:00.00 |

Upon receiving the `flow.started` event the service starts scheduling the flow executions by retrieving the flow data from its local DB.

Please note that the scheduler service ignores the event if at least one of the following conditions is met:

*  `cron` property is **not** present in the event

Upon receiving the `flow.stopping` event, the service deletes the record for the given flow and stops scheduling flow executions.

---------------

## Client library
All microservices will use the same Node.js client library, if they want to.

## Event publishing
Events are published to the common RabbitMQ exchange with a certain routing key. The type of the exchange should be `topic`.

### Routing key format
Routing key should have an optional prefix (so that we could have additional flexibility for partial subscriptions):
Example: [prefix.]flows.created

## Event subscription
Each microservice is able to subscribe to multiple topics.

### Subscription process
1. Create a queue.
2. Bind this queue to the EventBus exchange with a certain routing key.
3. Start consuming messages from the queue.

### Queues
Since each of the microservices will keep it's own copy of needed data, we can't afford loosing it.
Therefore the queues have to be permanent and keep messages on disk in order to survive after restarts of RabbitMQ as well as microservices.

**Comment by philecs** [comment]
@pnedelko you're already working on this epic? Which issues belong to this one?

**Comment by SvenHoeffler** [comment]
Where should the Flow Repository draw the content of the `cron` and `isWebhook` properties in the event from? Are they part of the content of the POST request, or derived from stored data?

**Comment by drobiazko** [comment]
@SvenHoeffler thank you for your question. We need to extend the Flow Repository API with the `cron` property to be used to define the CRON expression for the flow execution intervals. It looks like Flow Repo will not be able to compute the `isWebhook` property as it has no knowledge about the typ of the trigger in the flow - in contract to how it is done in elastic.io. I think we could simplify it in the 1st iteration: if `cron` is set => scheduling, if not => webhook. Let's discuss it tomorrow in the sprint planning.

**Comment by philecs** [comment]
![eventcollaborationexample](https://user-images.githubusercontent.com/29949654/53477609-58fbea80-3a75-11e9-80ce-04869278ab34.png)


Service names updated

**Comment by pnedelko** [comment]
Finished all subissues. Closing.
