### ISSUE TITLE
Adjust ICR according to guidelines

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#277]
As a product manager, I want consistent API specs to ensure quality across all specifications.

Further description:

Currently the ICR API Specs do not match the specifications of the guidelines in some points:

- root structure must have `data` and `meta`
- Schema definition for `flows` must be redefined. See [current version of definition](https://github.com/openintegrationhub/openintegrationhub/blob/master/services/integration-content-repository/app/api/swagger/swagger.json#L123) vs.  [guideline: schemas for collection of objects](https://github.com/openintegrationhub/openintegrationhub/blob/master/Guidelines/ServiceAPIGuidelines.md#must-not-to-contribute-to-schema-explosion-by-defining-schemas-for-collections-of-objects)
- Default sort order (parameter for `/flows`) should be ascending. Currently its descending.

---

**Acceptance Criteria:**
- [x] API Documentation adjusted according to changes

---

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by SvenHoeffler** [comment]
The API has been adjusted according to the guidelines.
