### ISSUE TITLE
Test ICR according to test cases

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#278]
**Further description:**

In [#173](https://github.com/openintegrationhub/openintegrationhub/issues/173) several [test cases](https://github.com/openintegrationhub/openintegrationhub/issues/173#issuecomment-460668074) were ellaborated. As testing is currently blocked because of the reported issue: `Token invalid. Error: JsonWebTokenError. Details: jwt issuer invalid. expected: https://www.example.com`. Once the issue is resolved the tests must be performed.

---

**Acceptance Criteria:**
- [x] Tests performed and test report created

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by DennisCES** [comment]
Tests were performed, report is pending yet and will be provided tomorrow or ASAP
