### ISSUE TITLE
Update iam-utils library to support new IAM tokens and permissions

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#279]
**Further description:**

While testing the ICR @DennisCES discovered an authorization issue: `Token invalid. Error: JsonWebTokenError. Details: jwt issuer invalid. expected: https://www.example.com`.

---

**Acceptance Criteria:**
- [ ] Bug resolved - authorization possible

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by falkvoigt** [comment]
That Problem is related to old version of the Middleware. Selim will Provide the needed Version to fix that. Some Config will not be needed anymore.

**Comment by DennisCES** [comment]
The bug/error is still appearing in the ICR, even when I'm already "authorized" and try to "get all flows". Healthcheck is okay at the same time.

**Comment by DennisCES** [comment]
Update: issue re-opened. Selim already provided a new fix on the branch, after that, there are still some minor fixes in the ICR to make authorization work. @SvenHoeffler, @sachmerz wil help you doing so
