### ISSUE TITLE
There may be a race condition between scheduler and flow operator

### ISSUE THREAD

**Issue by drobiazko** [openintegrationhub/openintegrationhub#28]
When the scheduler schedules a trigger execution, it does not know if the job is already ready to run (e.g. if the queues are created by the operator). Due to this race condition it may happen that the 1st scheduler tick is lost

**Comment by philecs** [comment]
Statement copied from discussion in #33 :

#32 is in progress, but It's quite complex task so It will take some time to solve the issue.
#28 is convenient to solve along with #32 so it's also in progress
