### ISSUE TITLE
Discuss and integrate IAM authorization in existing services

### ISSUE THREAD

**Issue by sachmerz** [openintegrationhub/openintegrationhub#281]
As a OIH operator, I want all existing services that require some sort of authorization to be integrated with IAM service.

For each service, we have to create a service account and a persistent token in IAM. The service accounts can also have the following permissions, depending on requirements:
`iam.token.introspect`
`iam.token.create`

---

**Acceptance Criteria:**
- [x] ICR / Flow repository
- [x] Secrets-Service
- [x] other services affected?

---

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
From what I understood communication router and scheduler are not affected as flow is sent with the event once the flow is started. So no further affected services right now.
