### ISSUE TITLE
Metadata service schema referencing

### ISSUE THREAD

**Issue by sachmerz** [openintegrationhub/openintegrationhub#282]
Schemas can reference other schemas via Uri. Define and implement how such references are created and resolved.
---

**Acceptance Criteria:**
- [ ] A schema can have a custom uri, where the fully qualified uri is unique
- [ ] When updating a schema, check if all references schemas exist (integrity). Analogue with delete.

---

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by drobiazko** [comment]
Summary of our discussion today:

- Domain.visibility: public/private
- Domain.owners
- `#` in urls does not work on serverside
- POST schemas/import expects self-contained and valid schemas set
- new POST /schemas to add schemas gradually
- introduce `data` attribute in response payload, as defined in guidelines
- for request content type `application/schema+json` no `data` attribute in response. Just JSON schema as stored in DB

**Comment by drobiazko** [comment]
Open questions:

- `/domains/{id}/schemas` vs. `/schemas?domainId`

**Comment by sachmerz** [comment]
https://app.swaggerhub.com/apis/elasticio/metadata-service/0.0.2
https://app.swaggerhub.com/apis/basaas5/metadata-service/0.0.2
