### ISSUE TITLE
Extends flow nodes with secret reference

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#290]
**Further description:**

Flows must be extended so that each node in the flow can have a secret which is provided by the owner during flow creation / modification.

---

**Acceptance Criteria:**
- [ ] Flow structure extended

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by SvenHoeffler** [comment]
The Flow Repository now supports the field `credentials_id` in each node to serve as a reference to a secret. Has been merged as part of #491

**Comment by philecs** [comment]
@sachmerz anything left to do from you pov?

**Comment by sachmerz** [comment]
@philecs no, we're fine. As long as it possible to add a secret reference into that `credentials_id` during flow creation/modification.

**Comment by philecs** [comment]
@SvenHoeffler from what I understood it is possible to do so. Correct?
