### ISSUE TITLE
Provide Requirements for Notification & Event Bus

### ISSUE THREAD

**Issue by hschmidthh** [openintegrationhub/openintegrationhub#292]
For Service Collaboration we need the requirements for the Notification and Event Bus

**Further description:**

---

**Acceptance Criteria:**
- [ ] Requirements delivered
- [ ] Requirements accepted

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by pnedelko** [comment]
Some of the ideas have been already described in [this epic](https://github.com/openintegrationhub/openintegrationhub/issues/262) (section Client library and below).

## Further ideas

- each service should have it's own RabbitMQ queue, which is named by the name of the service (and maybe some prefix / postfix / etc.). Example: `events_communication-router`.
- client library should have an interface, that allows you to `nack` messages. Therefore `EventEmitter`  class seems to be not that suitable for this purpose.
- exchange and queue names logic should be hardcoded into the library (not configurable). If it requires changes, then it will require significant changes/migrations/etc.
- each message *must* contain it's unique ID
- each message *may* contain emitter name (who has emitted it)
- each message *may* contain some kind of trace ID and/or parent ID for debug purposes (to be able to track chains of messages)
