### ISSUE TITLE
Provide base implementation of Audit Log Service

### ISSUE THREAD

**Issue by hschmidthh** [openintegrationhub/openintegrationhub#295]
As an admin of an OIH-Tenant, i want to collect the user activities in one single service, so that i can inspect these activities.

**Further description:**

We want to establish an audit log service is capable of tracking the user activity, the user interactions with components and API functionalities and administrative actions (like create a tenant, add user).

---

**Acceptance Criteria:**
- [ ] prototype implementation of audit log service 

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by SvenHoeffler** [comment]
Initial implementation has been added with https://github.com/openintegrationhub/openintegrationhub/commit/e1b4ba043401ed9ec6dd36273df639936a98d639 . Integration into the k8s cluster to follow once queue has been set up.

**Comment by SvenHoeffler** [comment]
Audit Log has been deployed and is capable of connecting to the queue as of https://github.com/openintegrationhub/openintegrationhub/commit/e14d455e1f22f3526d321d786705e68504a3ed4e
