### ISSUE TITLE
Integrate ICR in IAM

### ISSUE THREAD

**Issue by hschmidthh** [openintegrationhub/openintegrationhub#296]
As a OIH operator, I want authorization of the ICR to be integrated with IAM service.

**Further description:**

---

**Acceptance Criteria:**
- [ ] ICR is integrated in IAM

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by SvenHoeffler** [comment]
The ICR has been adjusted to make use of the new version of the IAM middleware in #303

**Comment by philecs** [comment]
@SvenHoeffler what needs to be done here? Is it finished or do we have anything left to integrate both services?
