### ISSUE TITLE
Abstract all programmatic access to Kubernetes API using a facade

### ISSUE THREAD

**Issue by sachmerz** [openintegrationhub/openintegrationhub#3]
The OIH might make heavy use of Kubernetes API to create and manage containers & resources.
Although currently Kubernetes provides a lot of advantages, we should consider abstracting the access to the underlying infrastructure/orchestrator e.g. using a facade. The aim is to allow others to use an older version of Kubernetes if there are breaking API changes or even use other orchestrators entirely.

**Comment by philecs** [comment]
@sachmerz is this one still up-to-date?

**Comment by sachmerz** [comment]
We agreed to use DAOs and abstractions for all new services. The way the access to Kubernetes API is abstracted via `driver` in `resource-coordinator` is ok with us.
