### ISSUE TITLE
Use external RabbitMQ 

### ISSUE THREAD

**Issue by drobiazko** [openintegrationhub/openintegrationhub#31]
At the moment RabbitMQ is [installed into k8s cluster](https://github.com/openintegrationhub/openintegrationhub/blob/master/platform/platform.json#L468-L555) as a `Deployment` with `replicas=1` which is quite nice for running the platform locally. However for a production use we need to rely on high availability. Is it better to rely on an RabbitMQ cluster outside of the k8s cluster?

**Comment by anton-kotenko** [comment]
What to do:
Create separate descriptors  for platform, that uses external rabbitmq service.
It's assumed that
1. Rabbitmq service/cluster installation and maintenance  are out of scope of this repo, and  platform installer is responsible for this
2. It's assumed that Rabbitmq server has appropriate accounts for platform. It's also assumed that ip addresses rabbitmq servers and account credentials is known at the  moment of platform installation

- [ ] create separate folder with platform descriptors, that uses secret, that contains rabbitmq server address and account's credentials
- [ ] create template for secret
- [ ] Add into documentation how all this should be installed

**Comment by philecs** [comment]
@anton-kotenko any updates here?

**Comment by anton-kotenko** [comment]
At the moment, no changes related to this issue: but it's actually its not question of platform development, it is ops question that related to some exact installation. So here we should do some recommendation how to install whole platform. 
AFAIK now we are in "development" phase, without production and even testing installations.  And because of this,  I think that priority of this task is small. 
@philecs your opinion about this?

**Comment by falkvoigt** [comment]
Hi All,
in my opinion all Services using RabbitMQ / Message Queue what ever. Needs to be able to be configured (Connection Endpoint as ENV Var of OIH service) what to use. 

**Where the RabbitMQ is running makes no big differences.** 

I would recommend if RabbitMQ is running in our Cluster we should use HELM Shard for it. And have  min 3 replicas on production Installation. On Dev environment i would say 1 ist totally fine.

**Comment by philecs** [comment]
@anton-kotenko is falks comment sufficient or do you need more information?

**Comment by anton-kotenko** [comment]
Hi.
It's already configurable using ENV variables for services. So to use some external rabbitmq service it's required only to change ENV var's (RABBITMQ_URI) in platform/platform.json. 
So this task is only to document this fact and create example json/yaml files. 
If we are speaking about docs examples -- I have not done this yet.

**Comment by falkvoigt** [comment]
That sounds fine for me. Please stick with YAML because the Kubernetes Community ist mostly related to that. I know they are using json internal. But we should represent us to the Community.
