### ISSUE TITLE
How shall the initial sync of all application data work? 

### ISSUE THREAD

**Issue by ealtendorf** [openintegrationhub/openintegrationhub#310]
Consider the following szenario:
**A new application shall be connected to OIH.**

1. How could be achieved by OIH, that all data of the new application will be initially synchronized?  (APP --> OIH)

The application (resp. its connector) itself could use the POST data of REST API for this purpose, but this must be initiated by the application and cannot be somehow triggered by OIH. 

2.  How could be achieved, that the new application gets all data from other applications already contained in OIH? (OIH --> APP)

The webhook subscription of REST API only guarantees, that the new application is notified if data is *changed* by other applications.

**Comment by RobinBrinkmann** [comment]
This issue is being tackled by a new Data Import and Merge service: #1158
