### ISSUE TITLE
Flow repository should not allow changes to running flows

### ISSUE THREAD

**Issue by pnedelko** [openintegrationhub/openintegrationhub#313]
When a flow is running, Flow repository should reject any changes to the flow. In order to change the flow, you need to stop it first.

---

**Acceptance Criteria:**
- [x] Flow repo rejects changes to running flows

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by SvenHoeffler** [comment]
Done. The Flow Repository will now refuse update and delete operations on flows that are not currently inactive. Additionally, start/stop operations are now also only valid on flows that are inactive/active, respectively. In case of such a conflict, the Flow Repository will respond with a code 409 error.
