### ISSUE TITLE
Operator should detect changes on Flow CDRs

### ISSUE THREAD

**Issue by drobiazko** [openintegrationhub/openintegrationhub#32]
Imagine you created a new version of your flow definition which you want to deploy via `kubctl`, REST API or a frontent. It may happen that the `flow operator` will not notice the update at all. This can be easily reproduced by executing the following command for an existing flow.

`kubctl delete flow $FLOW_ID  && kubectl create flow -f $FLOW_JSON_FILE`

The changes will not be applied to the flow as the flow operator is not detecting the changes on existing `Flow` CRDs. Perfectly the flow operator checks the `metadata.resourceVersion` of the CDRs to detect changes.

Please check the paragraph **Efficient detection of changes** in the [k8s API Concepts](https://kubernetes.io/docs/reference/using-api/api-concepts/) document. Here is some extract:

> To enable clients to build a model of the current state of a cluster, all Kubernetes object resource types are required to support consistent lists and an incremental change notification feed called a watch. Every Kubernetes object has a resourceVersion field representing the version of that resource as stored in the underlying database. When retrieving a collection of resources (either namespace or cluster scoped), the response from the server will contain a resourceVersion value that can be used to initiate a watch against the server. The server will return all changes (creates, deletes, and updates) that occur after the supplied resourceVersion. This allows a client to fetch the current state and then watch for changes without missing any updates. If the client watch is disconnected they can restart a new watch from the last returned resourceVersion, or perform a new collection request and begin again.

**Comment by anton-kotenko** [comment]
Requires additional investigation:
Idea: there should be flow definition crd. There also additional information should be stored for internals of platform (rabbimq accounts for flows, current state, started/stopped/running)
This additional information should be used to find out changes. To understand that flow  should be killed and all related things are deleted.
Options: 
1. add some read-only properties in flow definition crd. Need to find out how to protect them from external user
2. add "shadow" crd that is used only by platform internally. 

Need also understand how to handle crd removal for both options and trigger cleaning on it.

**Comment by philecs** [comment]
Statement copied from discussion in #33 :

#32 is in progress, but It's quite complex task so It will take some time to solve the issue.

**Comment by philecs** [comment]
@anton-kotenko as stated with merge of pr #104 this issue as well as  #24 #26 and #28 can be moved to "done", right? If yes, I'll put them in the right lane.

**Comment by anton-kotenko** [comment]
@philecs 
You are right. Thank you.
