### ISSUE TITLE
Flow operator does not define resource limits on components

### ISSUE THREAD

**Issue by drobiazko** [openintegrationhub/openintegrationhub#33]
This confuses k8s' distribution mechanisms, and in worst case all components may be started at same node, and overload it.

**Comment by anton-kotenko** [comment]
- [ ]  Define format how limits should be configured in  flow definition, document it
- [ ] Implement transformation from flow format into k8s job format

**Comment by philecs** [comment]
@anton-kotenko any updates here?

**Comment by anton-kotenko** [comment]
Hi @philecs
There are no updates, because this task is blocked by #32 and partially #28 And now i'm working on those blocker tasks.

**Comment by philecs** [comment]
@anton-kotenko thanks for replying. I'll only answer within this issue.

Are there updates for #32 and #28 ? And I saw that #32 is blocked by #26. Did you and your team already manage to work on this one?

**Comment by anton-kotenko** [comment]
#26 is implemented in  "draft mode". So I've unblocked myself for work on #32 
#32 is in progress, but It's quite complex task so It will take some time to solve the issue. 
#28 is convenient to solve along with #32 so it's also in progress

**Comment by philecs** [comment]
Thanks for the update :+1:
