### ISSUE TITLE
Data Hub base implementation

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#333]
As a _user type_, I want to _task_ so that _goal_.

**Further description:**

- [ ] Implemented data hub base implementation according to specs

---

**Acceptance Criteria:**
- [ ] Base implementation finished

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by pnedelko** [comment]
Specs: https://app.swaggerhub.com/apis/basaas/master-data/0.0.1#/
