### ISSUE TITLE
Define Message Format for Service Collaboration

### ISSUE THREAD

**Issue by hschmidthh** [openintegrationhub/openintegrationhub#345]
As a Developer i need a message format for event collaboration

**Further description:**

---

**Acceptance Criteria:**
- [x] Message Format provided
- [ ] Message Format accepted

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by SvenHoeffler** [comment]
The currently used Event format provided by the Event Bus library has shown itself to be sufficient and can be adopted for overall use. The schema is:

```json
{
  "headers": {
    "serviceName": "string",
    "createdAt": "date",
    "name": "string",
  },
  "payload": {
    "user": "string",
    "tenant": "string"
  }
} 
```

The field contents are:
- `headers`: An object containing metadata about the event itself
    - `serviceName`: The name of the spawning service. If using the event-bus module, this will be filled in automatically
    - `createdAt`: A timestamp of the event's creation. If using the event-bus module, this will be filled in automatically.
    - `name`: The name of the event. Also doubles as its routing key.
- `payload`: An arbitrary JSON object, containing the content of the event. Two optional fields are reserved for logging purposes:
    - `user`: The IAM-ID of a user who spawned the event
    - `tenant`: The IAM-ID of a tenant in which this event occurred
