### ISSUE TITLE
Expand Audit Log for service collaboration

### ISSUE THREAD

**Issue by hschmidthh** [openintegrationhub/openintegrationhub#346]
As a User, i want the audit log used by the other services to build an audit log

**Further description:**

---

**Acceptance Criteria:**
- [x] Audit log receives audit events from other services

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
Service is ready to receive events from other services. Currently only flow repository sends logs - other services must be expanded.
