### ISSUE TITLE
Create a specification for attachments storage

### ISSUE THREAD

**Issue by pnedelko** [openintegrationhub/openintegrationhub#349]
We need a specification for the attachments storage service, so that we could start implementing it.

---

**Acceptance Criteria:**
- [x] Specification is created and shared

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
@drobiazko any progress here?

**Comment by drobiazko** [comment]
https://app.swaggerhub.com/apis/drobiazko/attachment-storage/0.0.1
