### ISSUE TITLE
Issues after testing of Flow Repository

### ISSUE THREAD

**Issue by pnedelko** [openintegrationhub/openintegrationhub#351]
Here I'm going to collect all the issues/questions which I find during Event Collaboration testing.

---

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by pnedelko** [comment]
# GET /flows problems

![image](https://user-images.githubusercontent.com/2523461/54605769-52480e00-4a4a-11e9-92e5-9ffd6e037430.png)

![image](https://user-images.githubusercontent.com/2523461/54605794-5c6a0c80-4a4a-11e9-829c-14323fc48d6c.png)

**Comment by pnedelko** [comment]
# GET /flows/:id problems

<img width="772" alt="Postman 2019-03-19 13-25-28" src="https://user-images.githubusercontent.com/2523461/54605992-e023f900-4a4a-11e9-9993-edde7c96e57d.png">

**Comment by SvenHoeffler** [comment]
I have just merged in fixes for these issues. The only one that escapes me at the moment is the format of the `createdAt` and `updatedAt` timestamps. All internal functions already format those to the appropriate format via the `toISOString()` method, and unit tests return the correct format. Is this perhaps an issue of old flows from an older flow repo version still existing in the DB? If so, do newly created flows share that issue?

**Comment by pnedelko** [comment]
# /flows/:id/start & /flows/:id/stop problems

**The responses don't match to what is written in the API docs**

<img width="689" alt="Postman 2019-03-19 15-44-22" src="https://user-images.githubusercontent.com/2523461/54615695-d5735f00-4a5e-11e9-8281-0f3dace07282.png">


<img width="689" alt="Postman 2019-03-19 15-52-41" src="https://user-images.githubusercontent.com/2523461/54615838-0bb0de80-4a5f-11e9-99a0-ad6e842a381e.png">

**Comment by pnedelko** [comment]
@SvenHoeffler regarding date format issues: it's because you use `String` for `createdAt` and `updatedAt`, but they should have a `Date` type. I recommend you using this built-in mongoose approach instead: https://mongoosejs.com/docs/guide.html#timestamps.

**Comment by SvenHoeffler** [comment]
@pnedelko Ah, that's a good find, thanks. Fixes have been merged.

**Comment by pnedelko** [comment]
@SvenHoeffler 

`RabbitMqTransport` requires logger and doesn't get it: https://github.com/openintegrationhub/openintegrationhub/blob/d52bf0c64502678692cd969d1c7cca61280d73a4/services/flow-repository/app/utils/eventBus.js#L15

I added asserts here in order to get errors faster: https://github.com/openintegrationhub/openintegrationhub/pull/357

**Comment by philecs** [comment]
@pnedelko and @SvenHoeffler  is everything done here?

**Comment by SvenHoeffler** [comment]
@philecs The issues that have been listed here so far have been resolved. Unless @pnedelko has noticed something else in the meantime it should be done for now.
