### ISSUE TITLE
Expand Flow Repository for Service Collaboration

### ISSUE THREAD

**Issue by hschmidthh** [openintegrationhub/openintegrationhub#353]
As a User i want the Flow Repository to send messages to the Audit Log Services

**Further description:**

---

**Acceptance Criteria:**
- [x] Flow Repository accepts commands for flow starting
- [x] Flow Repository sends events to queue
- [x] Flow Repository receives events from queue

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by SvenHoeffler** [comment]
Done from the perspective of the Flow Repository. @pnedelko do you have any further requirements here for the Flow Repo from the perspective of the other involved services?

**Comment by pnedelko** [comment]
@SvenHoeffler  Does Audit Log receive events or http calls?

**Comment by philecs** [comment]
@pnedelko from what I understood Audit log receives events with topic `audit.*`

**Comment by SvenHoeffler** [comment]
@pnedelko The intended primary way to store logs is through publishing events with the topic `audit.*`, just as Phillip mentioned. There is an http endpoint as well, but for now that exists primarily for the purposes of demonstration and debugging.

**Comment by pnedelko** [comment]
Ok. Then from my side there are no more specific requirements.
