### ISSUE TITLE
Collect requirements for Attachments Storage

### ISSUE THREAD

**Issue by pnedelko** [openintegrationhub/openintegrationhub#382]
As basis for further implementation we need to collect requirements from all implementation partners.

This task contains all activities to gather these requirements.

- [x] Collect requirements from wice
- [x] Collect requirements from basaas
- [x] Collect requirements from ces

---

- [x] All requirements collected, aggregated and documented

**Comment by pnedelko** [comment]
From Wice: https://app.zenhub.com/workspaces/openintegrationhub-5b45d1643756796fbbab988b/issues/openintegrationhub/openintegrationhub/380#issuecomment-482012450

From Basaas: https://app.zenhub.com/workspaces/openintegrationhub-5b45d1643756796fbbab988b/issues/openintegrationhub/openintegrationhub/381#issuecomment-481618188

**Comment by philecs** [comment]
CES: https://github.com/openintegrationhub/openintegrationhub/issues/408#issuecomment-484089854

**Comment by philecs** [comment]
@pnedelko can you post the links to this issue within #383 once this one is finished?
Makes it easier to know where the requirements were coming from.
