### ISSUE TITLE
Provide requirements for the Component Repository

### ISSUE THREAD

**Issue by pnedelko** [openintegrationhub/openintegrationhub#387]

**Comment by philecs** [comment]
From discussion based on the provided [**specs**](https://app.swaggerhub.com/apis/drobiazko/component-repository/0.0.6#/) - Basaas requirements:

- flag for public components
- will the design of this service allow to add custom distributions, e.g. Basaas uses the Google Cloud Container Registry and not DockerHub
  - This could also mean, that each distribution could potentially have some custom logic to authentication and data fetching etc.
