### ISSUE TITLE
Provide requirements for hierarchy & relationship management

### ISSUE THREAD

**Issue by sachmerz** [openintegrationhub/openintegrationhub#390]
Provide Wice requirements for the hierarchy & relationship management services.

These requirements function as the basis for the subsequent development of the service.

---

**Acceptance Criteria:**

- [ ] Requirements provided

---

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
@sachmerz and @hschmidthh as far as I remember were the requirements provided. Correct?
Can you post them here for tracking purposes?
