### ISSUE TITLE
Define audit log relevant events

### ISSUE THREAD

**Issue by sachmerz** [openintegrationhub/openintegrationhub#391]
IAM, Secret-Service and Metadata-Repository should all fire events via event-bus library. The audit log service can subscribe to these events.

- [x] Define a list of events for each service

---

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by sachmerz** [comment]
Current idea:

**Global Events**

Event-Bus topic name: '_common_'

* IAM
    * User created
        * _iam.user.created_
    * User removed
        * _iam.user.deleted_
    * Tenant created
        * _iam.tenant.created_
    * Tenant removed
        * _iam.tenant.deleted_
* Flow
    * Started (e.g. _flow-repo.flow.created_?)
    * Stopped
    * Deleted (flow-repo.flow.deleted?)



**AuditLog Events**

* IAM
    * User
        * Created, modified, deleted, assigned/removed to/from tenant, failed login attempt
        * e.g. _iam.user.[operation]_
    * Tenant
        * Created, modified, deleted
        * e.g. _iam.tenant.[operation]_
    * Token / Roles / Permissions
        * Created, modified, deleted
        * e.g. _iam.role.[operation]_
    * 
* Secret-Service
    * Secret
        * Created, deleted
            * e.g. _secret-service.secret.[operation], secret-service.auth-client.[operation]_
        * Access Token requested by Account
            * e.g. _secret-service.token.get_
* Metadata
    * Domain / Schema
        * Created, modified, deleted
        * E.g. _metadata.schema.[operation]_

**Comment by philecs** [comment]
@sachmerz and @heggert is it ready for review/qa or still in progress?

**Comment by philecs** [comment]
As discussed yesterday there are no objections.
Proposal accepted.
