### ISSUE TITLE
Metadata-repository should fetch external schemas and store them internally

### ISSUE THREAD

**Issue by sachmerz** [openintegrationhub/openintegrationhub#395]
External schema references (e.g. on GitHub) should be fetched automatically when processing a model and stored internally in the metadata repository. The references should be rewritten accordingly and point to internal schemas.

---

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by sachmerz** [comment]
Currently the external schemas are fetched and validated, but not persisted internally.

**Comment by RobinBrinkmann** [comment]
In the process of streamlining the framework, the Meta Data Repository will soon be moved out of the monorepo. It will be kept in a separate repository as a reference and for anyone who wants to continue work on it. There will not be any maintenance by the core dev team.
