### ISSUE TITLE
Add custom authorization to service accounts

### ISSUE THREAD

**Issue by sachmerz** [openintegrationhub/openintegrationhub#4]
IAM Service Accounts should have a scoped access, e.g. read-only access to all tenants for a token introspection. See [IAM utils](https://github.com/openintegrationhub/iam-utils) for usage scenario.

---

- [ ] Service Accounts can be created
- [ ] Service Accounts have scoped permissions

**Comment by philecs** [comment]
@sachmerz who should review this issue as it is in _review/qa_?
