### ISSUE TITLE
Provide requirements for Attachments Storage

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#408]
As a user I want to synchronize attachments, so that I am able to use the same documents in different systems.

**Further description:**

- [x] Provide requirements for attachments storage service

---

**Acceptance Criteria:**
- [x] Requirements provided

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
- Service should be able to store different versions of an attachment
- Service should be able to store different types of attachments (documents, pictures, folders)
- It should be possible to pass on multiple attachments when executing a flow (bulk upload)
- It should be possible to store relations between different documents to be able to resolve them in the target system

**Comment by philecs** [comment]
@pnedelko FYI

**Comment by pnedelko** [comment]
> Service should be able to store different versions of an attachment

Why to do versioning? You could upload a new version as a separate file. What is the use case?

> Service should be able to store different types of attachments (documents, pictures, folders)

Folders packed as a zip archive would be enough?

> It should be possible to pass on multiple attachments when executing a flow (bulk upload)

You can upload multiple files during the component execution. Or what do you mean?

> It should be possible to store relations between different documents to be able to resolve them 
in the target system

What kind of relations?

**Comment by philecs** [comment]
@pnedelko 

> > Service should be able to store different versions of an attachment
> 
> Why to do versioning? You could upload a new version as a separate file. What is the use case?

Correct. The use case is e.g. A file can have multiple versions as it was edited multiple times. But this use case is solved with uploading a new version. So no further functionality needed.

> > Service should be able to store different types of attachments (documents, pictures, folders)
> 
> Folders packed as a zip archive would be enough?

Yes - that's sufficient.

> 
> > It should be possible to pass on multiple attachments when executing a flow (bulk upload)
> 
> You can upload multiple files during the component execution. Or what do you mean?

This is I exactly what I meant :+1: 

> > It should be possible to store relations between different documents to be able to resolve them
> > in the target system
> 
> What kind of relations?

Relations such as "same object different version" or "parent folder". But I'm currently not sure if this is a use case that must be covered by attachments storage service. I think its more a document domain specific requirements and relations should later be stored in Data Hub, not by attachment storage service.

**Comment by pnedelko** [comment]
Ok. Seems like we are on the same page.
