### ISSUE TITLE
Secret Service doesn't support arbitrary owners configuration

### ISSUE THREAD

**Issue by pnedelko** [openintegrationhub/openintegrationhub#413]
## The use case
At elastic.io secrets (credentials) belong to a workspace, not to the user. Therefore, when somebody is joining a workspace, he gets an access to all credentials created by others in this workspace.

## The problem
It seems like in the current implementation of Secrets Service the only option for sharing is to [add another user](https://github.com/openintegrationhub/openintegrationhub/blob/master/lib/secret-service/src/middleware/auth/index.js#L19) into the list of secret's `owners`. For elastic.io it means, that when a new user is added to a workspace, we would need to add him to the all credentials which exist in that workspace. Or, on the other hand, when a new credential is added, we would need to add all the users of the workspace to the owners list.

## What is desired
It would be nice if we could set a workspace as the only owner of a secret and Secret Service would allow access to all workspace members.

**Comment by drobiazko** [comment]
@pnedelko does it mean that it is impossible to define such an owner for a secret and later retrieve it for the workspace with id 123?

```json
{
     "type": "workspace",
     "id": 123
}
```
