### ISSUE TITLE
Coding integration tests for flow repository

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#415]
As a quality manager I want working integration tests so that I can ensure the plattform is running properly.

Writing the integration tests for the Flow Repository

**Further description:**

Tests needed for

- [x] Getting all flows for authenticated user
- [x] Getting a flow by id for authenticated user
- [x] Posting a flow as an authenticated user
- [x] Patching a flow by Id for authenticated user
- [x] Starting a specific flow for an authenticated user
- [x] Sopping a specific flow for an authenticated user
- [x] Deleting a flow by id for an authenticated user

---

**Acceptance Criteria:**
- [x] All tests written and working 

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by DennisCES** [comment]
Everything works just fine
