### ISSUE TITLE
Coding integration tests for audit log

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#416]
As a quality manager I want working integration tests so that I can ensure the plattform is running properly.

Writing the integration tests for the audit log

**Further description:**

Tests needed for

- [x] Getting all logs for authenticated user
- [x] Posting a log for an authenticated user
- [x] Test if events thrown by other services (e.g. Flow repsitory) are propely logged in audit log 

---

**Acceptance Criteria:**
- [x] All tests written and working 

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by DennisCES** [comment]
Tests are written and working - postponed since further mid-steps tests aren't working and blocking at the very moment
