### ISSUE TITLE
Add description fields for flow attributes

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#417]
As a user I want description for each attibute in an object (unless it's obvious) so that I am able to post/patch flows properly.

**Further description:**

The current api docs do not include descriptions for the flow attributes. See: [flow repo docs](http://flow-repository.openintegrationhub.com/api-docs/).

- [x] Add descriptions

---

**Acceptance Criteria:**
- [x] Flow attributes described

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by SvenHoeffler** [comment]
Done, to the degree that the fields are currently defined and in use, based on the example flow in https://github.com/openintegrationhub/openintegrationhub/blob/master/docs/example-flows/timer-to-nodejs-code.json

**Comment by philecs** [comment]
Is it already merged into master branch?

**Comment by SvenHoeffler** [comment]
Has been merged, yes.
