### ISSUE TITLE
Add description field for audit log attributes

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#418]
As a user I want description for each attibute in an object (unless it's obvious) so that I am able post logs.

**Further description:**

The current api docs do not include descriptions for the palyoad attributes. See: [auditlog docs](http://auditlog.openintegrationhub.com/api-docs/#/tenant/createTenant).

- [x] Add descriptions

---

**Acceptance Criteria:**
- [x] Audit log payload object attributes described

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by SvenHoeffler** [comment]
Done

**Comment by philecs** [comment]
Is it already merged into master branch?

**Comment by SvenHoeffler** [comment]
Has been merged, yes
