### ISSUE TITLE
Update IAM Specs according to guidelines

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#422]
IAM API docs are currently not in line with the service api guidelines.

**Further description:**

- [ ] Adjust payload structure and add `data` & `meta`

---

**Acceptance Criteria:**
- [ ] Guidelines adjusted

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by RobinBrinkmann** [comment]
Done with #1120
