### ISSUE TITLE
Local framework setup

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#430]
As a user I want to easily install and run the framework (reference implementations) locally so that I am quickly able to use/testit. 

**Further description:**

Currently the services are deployed and managed on a central cluster. In order for 3rd parties to quickly use the framework an easy way to install and use the plattform is needed.

---

**Acceptance Criteria:**
- [ ] Framework can be used locally
- [ ] Downloadable version includes sample data

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
In collaboration with @SvenHoeffler

**Comment by philecs** [comment]
currently checking technical requirements for local installation

**Comment by philecs** [comment]
Notes from @SvenHoeffler :

```markdown
##### Things that the user needs to start the cluster:
- internet access (for minikube and service images)
- minikube installed
- kubectl installed
- minikube started
- kubectl using minikube as context
- OIH repository downloaded to access all the k8s .yaml files

##### Things that might have to be adjusted within the individual service k8s configs:
- The image field should probably point to a particular version, instead of latest
- Ingress service might have to use different host rules depending on minikube requirements
- Various URLs pointing towards other services must match with the chosen namespace
- Resource limits might have to be lowered

##### Things that need to happen within the cluster once active, in order:
- Basic infrastructure has to be established (as per platform folder):
-- create namespace
-- create a MongoDB
-- create a RabbitMQ queue
-- create an ingress

- Secrets with necessary values have to be deployed:
-- iam: `mongourl`, `IAM_JWT_SECRET`, `IAM_ACC_ADMIN_PASSWORD`
-- oidc-certs: First create the keystore json, then: `kubectl create secret generic oidc-certs --from-file=./keystore.json --namespace=oih-dev-ns`
-- meta-data-repository: `mongourl`, `iamtoken`
-- audit-log: `mongoUrl`, `iamtoken`
-- component-repository: `MONGODB_URI`, `IAM_TOKEN`
-- component-orchestrator: `IAM_TOKEN`, `MONGODB_URI`
-- flow-repository: `mongourl`, `iamtoken`
-- scheduler: `MONGODB_URI`
-- secret-service: `mongourl`, `iamtoken`
-- webhooks: `MONGODB_URI`
- Microservice Deployments and Services have to be deployed:
-- Essentially just `kubectl apply -f ./k8s` for every subfolder within the services folder
- IAM must create a token for each microservice using the middleware (can be a single shared one if security is not relevant)
- Component repository should create necessary components
- Flow Repository should create an example flow

##### Overall workflow for local installation:
1. Ensure minikube and kubectl functionality (Could be left up to the user)
2. Create secrets, deployments, and services (Can be automated fairly easily)
3. Expose minikube ingress somehow
4. Set up example content such as flows and components (Can likely be automated depending on minikube i/o)

##### Various notes:
- Performance will be an issue. The current OIH takes up almost the entire capacity of three GCE vCPUs (approx. 2 Ghz each on a mid-line architechture). Memory could also be an issue, but appears to be less critical. Running this locally (including minikube overhead) would require a rather beefy physical machine.
- How to best connect to the minikube ingress has not yet been determined
```

**Comment by falkvoigt** [comment]
Question : Why don't use Docker-Compose ? That saves the overhead of K8S which is not needed vor a local ENV. You also get rid of the Problem of Ingress and Connection issues.

**Comment by SvenHoeffler** [comment]
Status update: After initial difficulties, I managed to set up a full OIH instance within a local Minikube. The following functionalities were successfully tested:
- Create a new User within the IAM
- Add a new component to the Component Repository
- Add a new flow to the Flow Repository
- Start that flow
- Component Orchestrator creates the necessary Jobs
- Scheduler executes those Jobs
- Jobs/Components can connect to external APIs (such as requestbin)

Which means the principal core functionality of the OIH is confirmed to be supported by Minikube.

**Comment by SvenHoeffler** [comment]
Update: Issues with persisting data throughout minikube VM restarts have been fixed, data can now be persistently saved. Additionally, I have created a step-by-step documentation on the necessary actions to create a minikube instance from scratch, which can serve as the basis of further automation:

```
As a step towards automation, this is a full list of the individual steps that need to be taken to deploy the OIH locally using Minikube. Any steps that require that files in the current monorepo to be modified are marked with a `!`, with an elaboration on the changes inside parentheses.

### Minikube setup
First, the minikube virtual machine itself has to be set up. This requires a fairly powerful host machine.
- Create a new Minikube instance. Make certain it has sufficient resources allocated to it, the default values are not sufficient. One configuration that was shown to work was `minikube start --memory 10240 --cpus 6` (assuming sufficient available memory and cpus on the host machine). This step tends to take a rather long time (3+ minutes). This will automatically set the `kubectl` context to minikube.
- Optional: Verify correct startup using `minikube dashboard`

### OIH infrastructure
Next, the basic infrastructure required by the services has to be set up. This must happen in a particular order, as otherwise kubernetes will attempt to access resources that do not yet exit. This largely uses the files found in the `/platform` folder.
- Create namespaces
- Create rabbitmq
- **!** Create Persistent Volume (new yaml file)
- **!** Create Persistent Volume Claim (new yaml file)
- **!** Create local mongodb (needs to have reference to volume claim added)
- **!** Create ingress (Requires different host and rules)
- Create host entry on the host machine pointing towards the ingress
- Alternatively: Forego ingress and access services via `kubectl proxy` instead.

### IAM and secrets
As multiple services require a service account and token to be able to authenticate themselves and their users, the IAM needs to be deployed and configured before any further services can be deployed.
- **!** Deploy IAM secret `iam` (new yaml file; needs to contain mongodb url and admin username/pass)
- Deploy IAM secret `oidc-certs` using procedure documented in IAM readme
- **!** Deploy IAM (`IAM_ORIGINWHITELIST` in k8s deployment needs to contain localhost and host entry)
- Access IAM and log in using default admin account
- Create an account of type `SERVICE_ACCOUNT` with the permissions `iam.token.introspect` and `components.get`
- Create a persistent token for this service account
- **!** Using this token where necessary, create secrets for the remaining services: `audit-log`, `component-orchestrator`, `component-repository`, `flow-repository`, `meta-data-repository`, `secret-service`, `scheduler`, `webhooks` (new yaml file per secret, similar to the IAM secret)
- Ordinarily, each service should have their own service account and token associated with it. However, as security is not as much of a concern for the local installation, a single one can be shared among all services.

### Services
The final step is the deployment of the remaining services. This can happen in any order, but several services require adjustments to their k8s configuration, hence why they are listed individually here.
- **!** Deploy Audit Log (`INTROSPECT_ENDPOINT_BASIC` needs to be adjusted)
- Deploy Component-Orchestrator
- Deploy Component-Repository
- **!** Deploy Flow Repository (`INTROSPECT_ENDPOINT_BASIC` and `ORIGINWHITELIST` need to be adjusted)
- **!** Deploy Metadata Repository (`INTROSPECT_ENDPOINT_BASIC` needs to be adjusted)
- Deploy Scheduler
- **!** Deploy Secret-Service (`INTROSPECT_ENDPOINT_BASIC` needs to be adjusted)
- **!** Deploy Web UI (All `ENDPOINT` values need to be adjusted)
- Deploy Webhooks

### Enter Showcase data
Now that the OIH is deployed, any desired showcase data, such as predefined flows and components, can be entered. Any entered data will persist through shutdowns and restarts of the minikube VM. Data will only be lost once the VM is deleted using `minikube delete`
```

**Comment by philecs** [comment]
The Open Integration Hub can be operated in different ways. One of them is to use the OIH locally.

To set it up locally some steps need to be performed manually prior to the execution of an automation script.

In the following the all needed steps are listed. Steps that need manual actions are marked:

## Minikube setup (manual) ✋ 

First, the minikube virtual machine itself has to be set up. This requires a fairly powerful host machine.

- Create a new Minikube instance. Make certain it has sufficient resources allocated to it, the default values are not sufficient. One configuration that was shown to work was `minikube start --memory 10240 --cpus 6` (assuming sufficient available memory and cpus on the host machine). This step tends to take a rather long time (3+ minutes). This will automatically set the `kubectl` context to minikube.
- Optional: Verify correct startup using `minikube dashboard`

## OIH infrastructure

Next, the basic infrastructure required by the services has to be set up. This must happen in a particular order, as otherwise kubernetes will attempt to access resources that do not yet exit. This largely uses the files found in the `/platform` folder.

- Create namespaces
- Create rabbitmq
- **!** Create Persistent Volume (new yaml file)
- **!** Create Persistent Volume Claim (new yaml file)
- **!** Create local mongodb (needs to have reference to volume claim added)
- **!** Create ingress (Requires different host and rules)
- Create host entry on the host machine pointing towards the ingress
- Alternatively: Forego ingress and access services via `kubectl proxy` instead.

## IAM and secrets (manual) ✋ 

As multiple services require a service account and token to be able to authenticate themselves and their users, the IAM needs to be deployed and configured before any further services can be deployed.

- **!** Deploy IAM secret `iam` (new yaml file; needs to contain mongodb url and admin username/pass)
- Deploy IAM secret `oidc-certs` using procedure documented in IAM readme
- **!** Deploy IAM (`IAM_ORIGINWHITELIST` in k8s deployment needs to contain localhost and host entry)
- Access IAM and log in using default admin account
- Create an account of type `SERVICE_ACCOUNT` with the permissions `iam.token.introspect` and `components.get`
- Create a persistent token for this service account
- **!** Using this token where necessary, create secrets for the remaining services: `audit-log`, `component-orchestrator`, `component-repository`, `flow-repository`, `meta-data-repository`, `secret-service`, `scheduler`, `webhooks` (new yaml file per secret, similar to the IAM secret)
- Ordinarily, each service should have their own service account and token associated with it. However, as security is not as much of a concern for the local installation, a single one can be shared among all services.

## Services

The final step is the deployment of the remaining services. This can happen in any order, but several services require adjustments to their k8s configuration, hence why they are listed individually here.

- **!** Deploy Audit Log (`INTROSPECT_ENDPOINT_BASIC` needs to be adjusted)
- Deploy Component-Orchestrator
- Deploy Component-Repository
- **!** Deploy Flow Repository (`INTROSPECT_ENDPOINT_BASIC` and `ORIGINWHITELIST` need to be adjusted)
- **!** Deploy Metadata Repository (`INTROSPECT_ENDPOINT_BASIC` needs to be adjusted)
- Deploy Scheduler
- **!** Deploy Secret-Service (`INTROSPECT_ENDPOINT_BASIC` needs to be adjusted)
- **!** Deploy Web UI (All `ENDPOINT` values need to be adjusted)
- Deploy Webhooks

## Enter Showcase data

Now that the OIH is deployed, any desired showcase data, such as predefined flows and components, can be entered. Any entered data will persist through shutdowns and restarts of the minikube VM. Data will only be lost once the VM is deleted using `minikube delete`

**Comment by philecs** [comment]
Pending decision: Where to store the config files? 

- In a seperate folder in the monorepo
- In an additional repository

The following configuration files are required at the moment:

- [x] ingress.yaml
- [x] mongodb.yaml
- [x] rabbitmq.yaml
- [x] service .yamls (deployment.yaml & service.yaml) for each service
- [x] namespace.yaml
- [x] service secrets

**Comment by philecs** [comment]
We won't be able to finish the issue this sprint. Therefore it will be moved to the next sprint.

**Comment by philecs** [comment]
Thanks for the good job 👍 @SvenHoeffler

**Comment by livingmine** [comment]
@SvenHoeffler thanks for the documentation for the [local setup ](https://openintegrationhub.github.io/docs/Getting%20Started/LocalInstallationGuide.html). I've successfully followed the instructions up to the point where i want to access the web-ui.localoih.com using the following credentials ```admin@openintegrationhub.com/somestring```, where i failed to log in. The network calls showed everything were 200 OK except for the GET request to http://flow-repository.localoih.com/flows where i received 401 unathorized with the following error message ```Token invalid. Error: Error. Details: Authorization failed"```. Am i missing something? Thanks!

**Comment by philecs** [comment]
@sachmerz not sure which service causes the error but maybe you can also help?

**Comment by sachmerz** [comment]
Hi @livingmine,

are you sure, that the `/flows` requested is sent to `http://flow-repository.localoih.com/flows` and not to `web-ui.localoih.com/flow-api/flows`? If the `ENDPOINT`s aren't configured for the Web-UI via Env vars, then it would normally try to proxy to the dev server, which would return a 401 for any unknown token.

And if the flow endpoint is correct, have you also set the correct `INTROSPECT_ENDPOINT_BASIC` env var for each of your services?

**Comment by SvenHoeffler** [comment]
Hi, @livingmine 

In addition to what @sachmerz already noted, could you check the following:

- While the cluster is running, can you successfully access http://flow-repository.localoih.com/api-docs in your browser?
- Which token did you enter into the secret during the step `Create persistent Service Token`?
- Using postman (or whatever else you used during the setup), can you successfully log in again and send a GET to http://flow-repository.localoih.com/flows ?

**Comment by livingmine** [comment]
Hi @sachmerz @SvenHoeffler thanks for helping out. I ended up restarting the cluster and redo the steps on the documentation and now i'm able to login without any problems. One thing that i notice i did it different with my previous attempt is that i change the username, firstname, lastname, password fields of the request payload of the Create Service Account section, could that be the cause?

**Comment by SvenHoeffler** [comment]
@livingmine 
Those fields technically shouldn't make a difference there, but we'll investigate it further. Thank you for the feedback!

**Comment by ryanlunka** [comment]
Hey guys! I'm actually experiencing the same 401 problem when trying to run OIH locally. I can get it to start up, but when I try to log in to the Web UI, I'm immediately redirected back to the login page with `401` and `Token invalid. Error: Error. Details: Authorization failed` in the browser console. I'm trying to follow the OIH local setup directions verbatim on a Macbook Pro.

I can get this to load, per a previous question: http://flow-repository.localoih.com/api-docs

When I went through the steps under "Create Persistent Service Token", the token I pulled from Postman was all asterisks until the last four characters. That struck me as odd, and possible where this went off track. I'm only guessing though.

Any ideas or help you can provide?

**Comment by SvenHoeffler** [comment]
@ryanlunka 

Hi! Yeah, the issue there is most likely that the value you got for the token was masked. To get its full value you should be able to call to the IAM with a GET on `/tokens` for a list of tokens, and then `/tokens/{id}` to with the id of the specific token you created. That should give you the full, unmasked value for the token, which you can then run through base64, paste into your secret, and re-apply the secret. 

Alternatively, you can simply POST `/login` with your admin username and password and use the token returned from that. It will only be valid for a few hours, but at least it should help you narrow down whether that is the cause.
