### ISSUE TITLE
Tests for Metadata Repository and Secret Service fail at seemingly random intervals

### ISSUE THREAD

**Issue by SvenHoeffler** [openintegrationhub/openintegrationhub#431]
Occasionally, the tests for the Metadata Repository and Secret Service run by CircleCI will fail without apparent cause. Simply running the CircleCI build again, with no changes to any code, will then usually lead to successful tests. Most likely this is related to CircleCI in some way.

Examples for failed builds that worked after running them again:
Secret Service: https://circleci.com/gh/openintegrationhub/openintegrationhub/6240
Metadata Repository: https://circleci.com/gh/openintegrationhub/openintegrationhub/6238

**Comment by philecs** [comment]
@SvenHoeffler still up to date?

**Comment by SvenHoeffler** [comment]
@philecs The issue does not seem to have resurfaced recently. Can be closed.
