### ISSUE TITLE
Change Flow Repository APi to support Component Registry

### ISSUE THREAD

**Issue by pnedelko** [openintegrationhub/openintegrationhub#436]
Since now we have the `Component Registry`, docker image is to be stored there. Therefore some changes in the `Flow Repository` are needed.

## Changes proposal
- start using `componentId` field (no changes required actually)
- remove `command` field
- introduce `function` field (to store a name of a component function to be called)

```js
{
  "id": "step1",
  "componentId": "<Mongo ID>",
  "function": "actionOrTriggerName",
  "name": "string",
  "description": "string",
  "fields": {
    "interval": "minute"
  }
}
```

---

**Acceptance Criteria:**
- [ ] Flow repository API is changed

---

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by SvenHoeffler** [comment]
Changes are implemented and ready, but as they are breaking, they can't yet be merged until the entire integration with the component repository is ready (see #435).

**Comment by philecs** [comment]
@SvenHoeffler and @pnedelko what about this one? It is included now?
