### ISSUE TITLE
Support multiple transports in event-bus lib

### ISSUE THREAD

**Issue by sachmerz** [openintegrationhub/openintegrationhub#440]
As a OIH developer I want to have multiple event-bus transports, to able to use RabbitMQ and ConsoleTransport simultaneously. 

Further description:
Use-Case: An event is published to a queue (maybe more than one) and the same event should also be sent to stdout for a log aggregator.

---

**Acceptance Criteria:**
- [ ] Two ore more transports can be added to an event bus
- [ ] publishing an event triggers all transports

---

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by RobinBrinkmann** [comment]
Backlog clean-up. Closing of outdated issues.
