### ISSUE TITLE
Integration tests for metadata repository

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#444]
As a quality manager I want working integration tests so that I can ensure the plattform is running properly.

Writing the integration tests for the metadata repository
**Further description:**

Tests needed for

- [x] uploading schemas for authenticated user
- [x] requesting schemas for authenticated user
- [x] updating schemas for authenticated user
- [x] deleting schemas for authenticated user
- [x] ... further to do's tbd by @DennisCES 

---

**Acceptance Criteria:**
- [x] All tests written and working 

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by DennisCES** [comment]
https://github.com/openintegrationhub/openintegrationhub/issues/552 - currently postponed

**Comment by philecs** [comment]
Further ToDo's:

- [x] **Put** domain model with given schema : `.../domains/{domainId}/schemas/{uri}`
- [x] **GET** specific domain model by uri and domainID `.../domains/{domainId}/schemas/{uri}`
- [x] Fix test No.25: Import a single domain model **POST** `.../domains/{domainId}/schemas`
- [x] **POST** multiple models `.../domains/{domainId}/schemas/import`
- [x] **Delete** schema by uri `.../domains/{domainId}/schemas/{uri}`

Updated docs: http://metadata.openintegrationhub.com/api-docs/#/

**Comment by philecs** [comment]
Sample data for test no.25:

```json
{
    "data": {
        "name": "test",
        "description": "upload test",
        "value": {
            "$id": "testingPhil",
            "properties": {
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                }
            }
        }
    }
}
```

**Comment by philecs** [comment]
Error occured at metadata repository while testing bulk import:

see #624
