### ISSUE TITLE
Admin UI: connect to flow repository

### ISSUE THREAD

**Issue by sachmerz** [openintegrationhub/openintegrationhub#467]
* Manage flows
* CRUD operations (post payload)

---

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
- [x] User can see all flows
- [x] User can add a new flow (e.g. text field to post a json object)
- [x] User can patch a flow
- [x] User can delete a flow
- [x] User can start a flow
- [x] User can stop a flow

**Comment by falkvoigt** [comment]
To get Flows and Components working on for Web-ui we need CORS Header implemented. In Locals tests all operations works fine

**Comment by philecs** [comment]
Operations tested. Worked fine for me :+1:

**Comment by falkvoigt** [comment]
Thx will Close the Issue then
