### ISSUE TITLE
Admin UI: Role and Permission Management

### ISSUE THREAD

**Issue by sachmerz** [openintegrationhub/openintegrationhub#468]
Custom Roles can be defined and existing permissions can be assigned to global/tenant specific roles.
Tenant-Admin can only assign `COMMON` permissions to her roles.

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
Findings:

- When adding a role and assigning it to a user while removing all other roles, the web ui still displays the user's old role instead of the new one
- It's possible to add "empty" roles for a user (see graphic below)
![image](https://user-images.githubusercontent.com/29949654/63437064-27fbe180-c42a-11e9-8160-04951ac66594.png)

**Comment by philecs** [comment]
1. Currently there is no overview about which roles belongs to which tenant. That should be added. (**Graphic 1**)
2. It is possible to add the same role multiple times for one tenant.  Should only be possible to add a specific role once for a tenant (**Graphic 2**)


**Graphic 1**:

![image](https://user-images.githubusercontent.com/29949654/63767661-8adbf580-c8ce-11e9-936d-7d07d1665476.png)

**Graphic 2**:

![image](https://user-images.githubusercontent.com/29949654/63767702-a515d380-c8ce-11e9-827c-328a0bb487cf.png)

**Comment by philecs** [comment]
A placeholder for the `role dropdown` would make role selection more intuitive (As its implemented for `tenant dropdown`.

See:

![image](https://user-images.githubusercontent.com/29949654/63779792-722c0980-c8e7-11e9-95d7-7ca53c2815c1.png)

**Comment by philecs** [comment]
No more issues found.
