### ISSUE TITLE
Container 'communication-router' keeps crashing: CrashLoopBackOff

### ISSUE THREAD

**Issue by DennisCES** [openintegrationhub/openintegrationhub#47]
Starting the openintegrationhub instance on the kubernetes cluster results in crashing bootloops of the container "communication-router"

Probably false secretKeyRefs, the containers cant send any "isAlive" responses based on a incomplete config file

Further description:
Error message in K8: Pod errors: "0 of 1 updated replica available - CrashLoopBackOff" 

---

**Acceptance Criteria:**
- [ ] Fixed Error 
- [ ] Published on Github

**Comment by zuker** [comment]
Pls try to start again with: 
```shell
kubectl scale deployment --replicas=0 --namespace=platform communication-router
kubectl scale deployment --replicas=1 --namespace=platform communication-router
```
and just after the first crash pls post here output of:

`kubectl --namespace=platform describe pod -lapp=communication-router`
`kubectl --namespace=platform logs -lapp=communication-router`

**Comment by DennisCES** [comment]
@zuker I scaled the replicas, here are the outputs

**Output after "describe pod":**

C:\Users\DennisSteiniger\AppData\Local\Google\Cloud SDK>kubectl --namespace=platform describe pod -lapp=communication-router
Name:           communication-router-6c8b9bb85c-mczds
Namespace:      platform
Node:           gke-oih-v1-default-pool-b46edad5-cw6l/10.156.0.4
Start Time:     Tue, 04 Sep 2018 15:06:20 +0200
Labels:         app=communication-router
                pod-template-hash=2746566417
Annotations:    <none>
Status:         Running
IP:             10.40.2.65
Controlled By:  ReplicaSet/communication-router-6c8b9bb85c
Containers:
  communication-router:
    Container ID:   docker://ea75b59d6a7c763bea85968481a58c661a7f7fc3644afd53a809992c1abae65f
    Image:          openintegrationhub/communication-router:latest
    Image ID:       docker-pullable://openintegrationhub/communication-router@sha256:c27f49adce6a2c73708cbf5ff8499d82e85c88580ad4faf870ffee2ac396044a
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 04 Sep 2018 15:06:45 +0200
      Finished:     Tue, 04 Sep 2018 15:06:46 +0200
    Ready:          False
    Restart Count:  2
    Liveness:       http-get http://:1234/healthcheck delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:1234/healthcheck delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      RABBITMQ_URI:  amqp://guest:guest@rabbitmq-service.platform.svc.cluster.local
      LISTEN_PORT:   1234
      LOG_LEVEL:     trace
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from flows-operator-account-token-9pvzx (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  flows-operator-account-token-9pvzx:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  flows-operator-account-token-9pvzx
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age               From                                            Message
  ----     ------                 ----              ----                                            -------
  Normal   Scheduled              30s               default-scheduler                               Successfully assigned communication-router-6c8b9bb85c-mczds to gke-oih-v1-default-pool-b46edad5-cw6l
  Normal   SuccessfulMountVolume  30s               kubelet, gke-oih-v1-default-pool-b46edad5-cw6l  MountVolume.SetUp succeeded for volume "flows-operator-account-token-9pvzx"
  Normal   Pulling                7s (x3 over 29s)  kubelet, gke-oih-v1-default-pool-b46edad5-cw6l  pulling image "openintegrationhub/communication-router:latest"
  Normal   Pulled                 5s (x3 over 28s)  kubelet, gke-oih-v1-default-pool-b46edad5-cw6l  Successfully pulled image "openintegrationhub/communication-router:latest"
  Normal   Created                5s (x3 over 28s)  kubelet, gke-oih-v1-default-pool-b46edad5-cw6l  Created container
  Normal   Started                5s (x3 over 28s)  kubelet, gke-oih-v1-default-pool-b46edad5-cw6l  Started container
  Warning  Unhealthy              4s                kubelet, gke-oih-v1-default-pool-b46edad5-cw6l  Readiness probe failed: Get http://10.40.2.65:1234/healthcheck: dial tcp 10.40.2.65:1234: getsockopt: connection refused
  Warning  BackOff                1s (x5 over 23s)  kubelet, gke-oih-v1-default-pool-b46edad5-cw6l  Back-off restarting failed container

------------------------------------

**Output after "logs":**

C:\Users\DennisSteiniger\AppData\Local\Google\Cloud SDK>kubectl --namespace=platform logs -lapp=communication-router

> webhooks@1.0.0 start /usr/src/communication-router
> node index.js

{"name":"startup","hostname":"communication-router-6c8b9bb85c-mczds","pid":15,"level":30,"msg":"Starting platform","time":"2018-09-04T13:09:38.381Z","v":0}
{"name":"startup","hostname":"communication-router-6c8b9bb85c-mczds","pid":15,"level":30,"msg":"going to get incluster config","time":"2018-09-04T13:09:38.382Z","v":0}
{"name":"startup","hostname":"communication-router-6c8b9bb85c-mczds","pid":15,"level":50,"err":{"message":"customresourcedefinitions.apiextensions.k8s.io is forbidden: User \"system:serviceaccount:platform:flows-operator-account\" cannot create customresourcedefinitions.apiextensions.k8s.io at the cluster scope: Unknown user \"system:serviceaccount:platform:flows-operator-account\"","name":"Error","stack":"Error: customresourcedefinitions.apiextensions.k8s.io is forbidden: User \"system:serviceaccount:platform:flows-operator-account\" cannot create customresourcedefinitions.apiextensions.k8s.io at the cluster scope: Unknown user \"system:serviceaccount:platform:flows-operator-account\"\n    at http.request (/usr/src/communication-router/node_modules/kubernetes-client/lib/swagger-client.js:269:25)\n    at Request.request [as _callback] (/usr/src/communication-router/node_modules/kubernetes-client/lib/request.js:107:14)\n    at Request.self.callback (/usr/src/communication-router/node_modules/request/request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (/usr/src/communication-router/node_modules/request/request.js:1157:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (/usr/src/communication-router/node_modules/request/request.js:1079:12)\n    at Object.onceWrapper (events.js:313:30)","code":403},"msg":"failed to crate crd","time":"2018-09-04T13:09:38.549Z","v":0}
{"name":"startup","hostname":"communication-router-6c8b9bb85c-mczds","pid":15,"level":50,"err":{"message":"customresourcedefinitions.apiextensions.k8s.io is forbidden: User \"system:serviceaccount:platform:flows-operator-account\" cannot create customresourcedefinitions.apiextensions.k8s.io at the cluster scope: Unknown user \"system:serviceaccount:platform:flows-operator-account\"","name":"Error","stack":"Error: customresourcedefinitions.apiextensions.k8s.io is forbidden: User \"system:serviceaccount:platform:flows-operator-account\" cannot create customresourcedefinitions.apiextensions.k8s.io at the cluster scope: Unknown user \"system:serviceaccount:platform:flows-operator-account\"\n    at http.request (/usr/src/communication-router/node_modules/kubernetes-client/lib/swagger-client.js:269:25)\n    at Request.request [as _callback] (/usr/src/communication-router/node_modules/kubernetes-client/lib/request.js:107:14)\n    at Request.self.callback (/usr/src/communication-router/node_modules/request/request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (/usr/src/communication-router/node_modules/request/request.js:1157:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (/usr/src/communication-router/node_modules/request/request.js:1079:12)\n    at Object.onceWrapper (events.js:313:30)","code":403},"msg":"failed to start platform","time":"2018-09-04T13:09:38.549Z","v":0}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webhooks@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webhooks@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-04T13_09_38_559Z-debug.log

**Comment by philecs** [comment]
@zuker  @DennisCES what is the current status? This issue is part of prototype 0.6 and should be part of the current sprint as end date for prototype 0.6 is already exceeded.

**Comment by anton-kotenko** [comment]
As far as I see, container has not enough privileges to create custom resource definitions in k8s. 
Please look into file https://github.com/openintegrationhub/openintegrationhub/blob/master/platform/platform.yml
for example how roles,rolebingings,service-accounts,... should be configured

**Comment by philecs** [comment]
Thanks for the update @anton-kotenko . 
@DennisCES pls check the comment above.

**Comment by DennisCES** [comment]
@anton-kotenko, actually, I think, this cant work at all right now, cause you havent deposited any secrets yet, did you?

**Comment by anton-kotenko** [comment]
Service account is created in https://github.com/openintegrationhub/openintegrationhub/blob/master/platform/platform.yml#L42
(this service account implicitly creates secret in kubernetes)
And this service account is attached to  services like here https://github.com/openintegrationhub/openintegrationhub/blob/master/platform/platform.yml#L258

Due to this, applications uses implicitly created secret to work with k8s api. This provides identification of pods in k8s api.
Roles and rolebindings in the top of the file https://github.com/openintegrationhub/openintegrationhub/blob/master/platform/platform.yml
explains to k8s api what is allowed for applications that runs with service-account described above.
So I think it should work. At least such configuration works in minikube. And we (e.io) uses same technic in our installation.

**Comment by DennisCES** [comment]
@anton-kotenko Ive checked the platform.yml and it was created by elastic. Can't you or Pavel provide the needed privileges?

**Comment by anton-kotenko** [comment]
Sorry but I don't understand. 
Platform.yml was written as example installation, such that you may take any clean k8s cluster (or minikube as smallest example) deploy platform.yml there, and got working platform, that may be used for dev/test purposes.
So our development process is based on personal installations (minikube). And I can not provide no credentials  for any "real-life" installation.  I suppose that @pnedelko  is in the same situation. 
@philecs do we have some dedicated installation for testing purposes? and who manages it?

**Comment by philecs** [comment]
@anton-kotenko yes we have a installation on the gc for testing purposes. @DennisCES manages it.

**Comment by anton-kotenko** [comment]
Ok, so my understanding of current situation is next:
1) @DennisCES  manages k8s installation, so it's possible for him to do anything he want
2) Current problem is incorrectly configured/missing  k8s descriptors for roles/accounts/...
3) There is example of working  descriptors.
4) Solution: patch example descriptors to make them match testing cluster and apply them to testing cluster.
@DennisCES  @philecs  please correct me if I'm wrong.

**Comment by philecs** [comment]
As I'm not managing the k8s installation I'm not the right person to provide feedback.
@falkvoigt can you provide information as @DennisCES is currently not in the office?

**Comment by falkvoigt** [comment]
when i get this right. Someone needs to apply the platform.yaml to our K8S testcluster. Do we have some Documentation about dependencies which needs to be done before? 
Still i'm not a friend of the Platform.yaml at all. :)

And it seams that the ElasticIO dev need access to the test cluster to get there stuff running.

**Comment by anton-kotenko** [comment]
As far as i understand @DennisCES  tried to install all this to testing cluster and it does not work. As far as i see, the problem is misconfiguration of some k8s descriptors. 
I don't think that somebody from ElastioIO need access to test k8s cluster for development (personally i use minikube and have k8s cluster for experiments in virtual machines on my notebook)
But if it's required I'm able to install scheduler and other services to the cluster (of course if I'll have access there)

**Comment by falkvoigt** [comment]
@anton-kotenko which k8s descriptors you are speaking about? Because the K8S cluster is nearly default (PAAS) from Google Cloud. It could be tricky to change stuff in it's backend. 
If there is configuration needed we should have that as Documentation somewhere in this Repo.

OIH is doing "You Build it, You run it" : the inital setup of the services should be done by the Company providing the Service. As i did for IAM.

**Comment by anton-kotenko** [comment]
Under term "k8s descriptors" I mean descriptors related to our services and it's not required to change something in depth of kubernetes itself. To run service requires next k8s descriptors:
1) service-account for actually service (just to identify service in k8s) 
2) role, cluster role (e.g. sceduler uses it's own custom resource definition so it should a) be able to register custom resource definition b) be able to work with that custom resources)
3) rolebinding + clusterrolebinding (it's required to link role and service account
4) custom resource definition (services uses CRD's to store some data. Actually flow definition is CRD)
5) deployment and service. (Deployment is required to start service as is. Service is required 1) to provide access to REST api in flows-operator 2) To forward external traffic to communication router service)

rabbitmq is required as external dependency. In example file it's started inside k8s just within deployment. In production installation customer may install it anyhow he wants. But deployments need to know how to access rabbitmq (so there is different RABBITMQ_XXXX env vars)
So actually there is only two adjustable parameters required to tune on new installation: RABBITMQ_XXX env vars, and LOG_LEVEL env vars

**Comment by falkvoigt** [comment]
Ok i understand.
But all the things you mentioned are a part of the platform.yam right? 
And that is whats not working for @DennisCES so when he trie's "kubectl apply -f platfom.yaml" he is getting errors. 

Thats why i would say you guys needs access to the Cluster to debug the Problems and perhaps update Documentation or the platform.yaml?

**Comment by anton-kotenko** [comment]
Yes, all those described is parts of platform.yaml.
Also if somebody  gives access privileges to me or @pnedelko, then we find source of problem and fix it. 
anton.kotenko@elastic.io is proper account in google.

**Comment by falkvoigt** [comment]
@DennisCES or @philecs could you please provide the access? Same as Igor has should be sufficient

**Comment by philecs** [comment]
@anton-kotenko I just gave access privileges to you

**Comment by anton-kotenko** [comment]
Thank you. As for now I have access to gcp's console and k8s cluster. Suppose that today in the evening I'll try to install platform.yml

**Comment by anton-kotenko** [comment]
Result of investigation:
Source of problem: platform.yml was not deployed properly (two of descriptors inside of it was not deployed)

Reason of this problem: it's not enough privileges for user (me, and probably @DennisCES)

Lost descriptors contains role and clusterrole for services, this roles provides privileges for services, and without those privileges services fails.

So to fix this it's required, that somebody with clusteradmin privilege deploy platform.yml into cluster. Or deploy descriptors that I've failed to deploy (see below, copy&paste parts from platform.yml)
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flows-operator-role
  namespace: flows
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - get
      - list
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - elastic.io
    resources:
      - flows
      - schedulerrecords
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
```
and 

```yaml
kind: ClusterRole
metadata:
  name: flows-operator-clusterrole
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
```

**Comment by falkvoigt** [comment]
That could be a Problem of the cluster setup :), The google Cloud K8S dose not support some features by default. Thats what i mention with backend changes to K8S. Because role management and so on is part of the Google Cloud Platform. Perhabs we need to give more Permissions to the Node Pool to get that up and running. We should research what to do in GCP to get ROLE AND CLUSTERROLE resource.

**Comment by anton-kotenko** [comment]
Finally find the reason of problem and fix it: 
By default even user recognized as admin in GCP has not enough privileges in k8s cluster.
To really acquire k8s admin  permissions you need to 
```sh
kubectl create clusterrolebinding cluster-admin-binding --clusterrole cluster-admin --user $(gcloud config get-value account) 
```
this gave me enough permissions to deploy plaform.yml and make everything work.
If somebody else need similar permissions -- add yourself  into clusterrolebinding  named `cluster-admin-binding`

**Comment by philecs** [comment]
Thanks @anton-kotenko for your committment. Does this also apply for #48 and #49 ?
If yes, I would mark those issues as done.

**Comment by anton-kotenko** [comment]
Yes, all this issues have same reason.

**Comment by falkvoigt** [comment]
yes have found the same solution this Morning. There was no changes needed to Backend. But we should Document the config you the Cluster needs.

**Comment by falkvoigt** [comment]
If you want to grand access from outside to the Service. Please use the ingress config under platform. there is no auto update involved  for ingress config just apply the file.
