### ISSUE TITLE
Container 'flows-operator' keeps crashing: CrashLoopBackOff

### ISSUE THREAD

**Issue by DennisCES** [openintegrationhub/openintegrationhub#48]
Starting the openintegrationhub instance on the kubernetes cluster results in crashing bootloops of the container "flows-operator"

Probably false secretKeyRefs, the containers cant send any "isAlive" responses based on a incomplete config file

Further description:
Error message in K8: Pod errors: "0 of 1 updated replica available - CrashLoopBackOff" 

---

**Acceptance Criteria:**
- [ ] Fixed Error 
- [ ] Published on Github

**Comment by philecs** [comment]
@drobiazko @DennisCES what is the current status? This issue is part of prototype 0.6 and should be part of the current sprint as end date for prototype 0.6 is already exceeded.

**Comment by anton-kotenko** [comment]
Please see comment https://github.com/openintegrationhub/openintegrationhub/issues/47#issuecomment-432666055
Suppose that the reason of problem is common for all services.

**Comment by philecs** [comment]
@DennisCES pls check the comment above.

**Comment by philecs** [comment]
Solution to this problem see: https://github.com/openintegrationhub/openintegrationhub/issues/47#issuecomment-434609715
