### ISSUE TITLE
Flows status "starting" bug

### ISSUE THREAD

**Issue by DennisCES** [openintegrationhub/openintegrationhub#486]
Currently, after starting a flow the status "starting" never changes, respectively never becomes "active". Therefore, we cannot stop any started flow in the meantime, since they need to be "active" in order to perform this other request.

---

**Acceptance Criteria:**
- [x] flow becomes automatically "active" after being started

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
@DennisCES Can you copy or reference your code here so that one can repoduce the error pls

**Comment by philecs** [comment]
And @DennisCES can you paste a copy a of the flow that causes this error pls

**Comment by DennisCES** [comment]
Bug is solved, TBD: re-writing the "add flow" & "stop flow" tests which include the new component(-requierement)

**Comment by philecs** [comment]
Fixed and done
