### ISSUE TITLE
Add validations for the flows data

### ISSUE THREAD

**Issue by pnedelko** [openintegrationhub/openintegrationhub#489]
At the moment it's quite easy to construct wrong flows, because there are almost no validations.

### My proposal

<img width="527" alt="openintegrationhub 2019-05-16 17-30-22" src="https://user-images.githubusercontent.com/2523461/57867475-84cf7680-7801-11e9-9372-0eb77fef0f69.png">

### Flow graph
- Flow.graph is also required. A flow should have at least 1 node. If a flow has >= 2 nodes, then edges have to be provided.
- Would be nice to check, if `edge.source` and `edge.target` are pointing to existing nodes.
- Length limitation for `node.id`. I would propose 10 chars.
- Length limitation for string properties, which make sense.

---

**Acceptance Criteria:**
- [x] Validations are added

---

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
@SvenHoeffler for tracking reasons:
- [x] User must not be able to post a flow status

**Comment by SvenHoeffler** [comment]
The following validations have been added:
- All fields mentioned in the image are now considered required
- Flows must contain at least one node
- Edge `source` and `target` must point towards an existing node `id`
- If more than one node is present, edges must also exist
- Node `componentId` field must be a valid MongoDB id
- `cron`, if present, must be a valid cron expression. Supports various cron formats
- `status` cannot be set manually
- Maximum string lengths: 10 for `node.id`, `edge.source`, and `edge.target`, 100 for `description` fields,  30 for most other fields

On failure of validation, the flow repo will return with status code 400 and an array of all failures.

**Comment by pnedelko** [comment]
@SvenHoeffler could you use type: `mongoose.types.ObjectId` for `componentId` (now it's implemented via the custom validator) and for the `credentials_id`? Or you used the `String` type there on purpose?

**Comment by pnedelko** [comment]
My concern is that for the `credentials_id ` it's still possible to submit a wrong value e.g. '123', but the Secret Service works with MongoDb ObjectIds AFAIK.

**Comment by SvenHoeffler** [comment]
@pnedelko 
Ah, I wasn't quite certain whether Secret Service worked only with ObjectIds or whether it could allow custom ones. If the former is the case, then of course it's no problem to add the same validation to that field as well.

As for using `ObjectId` as the type directly, I primarily used String and the custom validator to ensure that there's no inadvertent change to the value through the casting process and maintain WYSIWYG between input and the stored value. To my understanding mongoose already uses the same `isValid()` function internally during the casting to check for validity, so using one or the other should make no difference between which values are considered valid and which are refused. Though of course if there's an advantage to directly using the type that I'm not aware of it should be no trouble switching it over.

**Comment by philecs** [comment]
@SvenHoeffler have you changed the specs as discussed above?

Any validation checks missing yet?

**Comment by SvenHoeffler** [comment]
@philecs Yes, the model now uses the ObjectId type directly. That should cover all validations that have been discussed so far.

**Comment by philecs** [comment]
closed
