### ISSUE TITLE
Container 'scheduler' keeps crashing: CrashLoopBackOff

### ISSUE THREAD

**Issue by DennisCES** [openintegrationhub/openintegrationhub#49]
Starting the openintegrationhub instance on the kubernetes cluster results in crashing bootloops of the container "scheduler"

Probably false secretKeyRefs, the containers cant send any "isAlive" responses based on a incomplete config file

Further description:
Error message in K8: Pod errors: "0 of 1 updated replica available - CrashLoopBackOff" 

---

**Acceptance Criteria:**
- [ ] Fixed Error 
- [ ] Published on Github

**Comment by zuker** [comment]
Pls try to start again with: 
```shell
kubectl scale deployment --replicas=0 --namespace=platform scheduler
kubectl scale deployment --replicas=1 --namespace=platform scheduler
```
and just after the first crash pls post here output of:

`kubectl --namespace=platform describe pod -lapp=scheduler`
`kubectl --namespace=platform logs -lapp=scheduler`

**Comment by DennisCES** [comment]
@zuker:

Output after first command:

C:\Users\DennisSteiniger\AppData\Local\Google\Cloud SDK>kubectl --namespace=platform describe pod -lapp=scheduler
Name:           scheduler-5d84c698d4-c2d4k
Namespace:      platform
Node:           gke-oih-v1-default-pool-b46edad5-cw6l/10.156.0.4
Start Time:     Wed, 05 Sep 2018 12:52:56 +0200
Labels:         app=scheduler
                pod-template-hash=1840725480
Annotations:    <none>
Status:         Running
IP:             10.40.2.67
Controlled By:  ReplicaSet/scheduler-5d84c698d4
Containers:
  scheduler:
    Container ID:   docker://61679ed69868be4b88c5f88469a7804d59b4d6781c945353099d540de079c121
    Image:          openintegrationhub/scheduler:latest
    Image ID:       docker-pullable://openintegrationhub/scheduler@sha256:bff9ed10fcd3ec119ab41d9a32618696997dc7ae44808d751c3c5112389c7136
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 05 Sep 2018 12:53:34 +0200
      Finished:     Wed, 05 Sep 2018 12:53:35 +0200
    Ready:          False
    Restart Count:  2
    Liveness:       http-get http://:1234/healthcheck delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:1234/healthcheck delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      RABBITMQ_URI:  amqp://guest:guest@rabbitmq-service.platform.svc.cluster.local
      LISTEN_PORT:   1234
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from flows-operator-account-token-k9dxc (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  flows-operator-account-token-k9dxc:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  flows-operator-account-token-k9dxc
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age               From                                            Message
  ----     ------                 ----              ----                                            -------
  Normal   Scheduled              45s               default-scheduler                               Successfully assigned scheduler-5d84c698d4-c2d4k to gke-oih-v1-default-pool-b46edad5-cw6l
  Normal   SuccessfulMountVolume  45s               kubelet, gke-oih-v1-default-pool-b46edad5-cw6l  MountVolume.SetUp succeeded for volume "flows-operator-account-token-k9dxc"
  Warning  Unhealthy              27s               kubelet, gke-oih-v1-default-pool-b46edad5-cw6l  Readiness probe failed: Get http://10.40.2.67:1234/healthcheck: dial tcp 10.40.2.67:1234: getsockopt: connection refused
  Normal   Pulling                9s (x3 over 45s)  kubelet, gke-oih-v1-default-pool-b46edad5-cw6l  pulling image "openintegrationhub/scheduler:latest"
  Normal   Pulled                 7s (x3 over 43s)  kubelet, gke-oih-v1-default-pool-b46edad5-cw6l  Successfully pulled image "openintegrationhub/scheduler:latest"
  Normal   Created                7s (x3 over 43s)  kubelet, gke-oih-v1-default-pool-b46edad5-cw6l  Created container
  Normal   Started                7s (x3 over 43s)  kubelet, gke-oih-v1-default-pool-b46edad5-cw6l  Started container
  Warning  BackOff                4s (x4 over 26s)  kubelet, gke-oih-v1-default-pool-b46edad5-cw6l  Back-off restarting failed container

-----------------------

Output of second command:

C:\Users\DennisSteiniger\AppData\Local\Google\Cloud SDK>kubectl --namespace=platform logs -lapp=scheduler

> scheduler@1.0.0 start /usr/src/scheduler
> node index.js

{"name":"startup","hostname":"scheduler-5d84c698d4-c2d4k","pid":15,"level":30,"msg":"Starting platform","time":"2018-09-05T10:54:11.831Z","v":0}
{"name":"startup","hostname":"scheduler-5d84c698d4-c2d4k","pid":15,"level":30,"msg":"going to get incluster config","time":"2018-09-05T10:54:11.832Z","v":0}
{"name":"startup","hostname":"scheduler-5d84c698d4-c2d4k","pid":15,"level":50,"err":{"message":"customresourcedefinitions.apiextensions.k8s.io is forbidden: User \"system:serviceaccount:platform:flows-operator-account\" cannot create customresourcedefinitions.apiextensions.k8s.io at the cluster scope: Unknown user \"system:serviceaccount:platform:flows-operator-account\"","name":"Error","stack":"Error: customresourcedefinitions.apiextensions.k8s.io is forbidden: User \"system:serviceaccount:platform:flows-operator-account\" cannot create customresourcedefinitions.apiextensions.k8s.io at the cluster scope: Unknown user \"system:serviceaccount:platform:flows-operator-account\"\n    at http.request (/usr/src/scheduler/node_modules/kubernetes-client/lib/swagger-client.js:269:25)\n    at Request.request [as _callback] (/usr/src/scheduler/node_modules/kubernetes-client/lib/request.js:107:14)\n    at Request.self.callback (/usr/src/scheduler/node_modules/request/request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (/usr/src/scheduler/node_modules/request/request.js:1157:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (/usr/src/scheduler/node_modules/request/request.js:1079:12)\n    at Object.onceWrapper (events.js:313:30)","code":403},"msg":"failed to crate crd","time":"2018-09-05T10:54:11.957Z","v":0}
{"name":"startup","hostname":"scheduler-5d84c698d4-c2d4k","pid":15,"level":50,"err":{"message":"customresourcedefinitions.apiextensions.k8s.io is forbidden: User \"system:serviceaccount:platform:flows-operator-account\" cannot create customresourcedefinitions.apiextensions.k8s.io at the cluster scope: Unknown user \"system:serviceaccount:platform:flows-operator-account\"","name":"Error","stack":"Error: customresourcedefinitions.apiextensions.k8s.io is forbidden: User \"system:serviceaccount:platform:flows-operator-account\" cannot create customresourcedefinitions.apiextensions.k8s.io at the cluster scope: Unknown user \"system:serviceaccount:platform:flows-operator-account\"\n    at http.request (/usr/src/scheduler/node_modules/kubernetes-client/lib/swagger-client.js:269:25)\n    at Request.request [as _callback] (/usr/src/scheduler/node_modules/kubernetes-client/lib/request.js:107:14)\n    at Request.self.callback (/usr/src/scheduler/node_modules/request/request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (/usr/src/scheduler/node_modules/request/request.js:1157:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (/usr/src/scheduler/node_modules/request/request.js:1079:12)\n    at Object.onceWrapper (events.js:313:30)","code":403},"msg":"failed to start platform","time":"2018-09-05T10:54:11.957Z","v":0}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scheduler@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scheduler@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-05T10_54_11_967Z-debug.log

**Comment by philecs** [comment]
@zuker @DennisCES what is the current status? This issue is part of prototype 0.6 and should be part of the current sprint as end date for prototype 0.6 is already exceeded.

**Comment by anton-kotenko** [comment]
Looks like same as here https://github.com/openintegrationhub/openintegrationhub/issues/47#issuecomment-432666055

**Comment by philecs** [comment]
@DennisCES pls check the comment above.

**Comment by philecs** [comment]
Solution to this problem see: https://github.com/openintegrationhub/openintegrationhub/issues/47#issuecomment-434609715
