### ISSUE TITLE
Component visibility issues

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#493]
Steps:

1. Added a new user in IAM
2. Tried to get all user components
3. Got an empty `data` array as response

When trying to get a component by id , the component is received properly.

Note: User has admin rights.

---

**Acceptance Criteria:**
- [x] Admin user can see all workspace components

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by pnedelko** [comment]
@philecs please check again.
- role=ADMIN has access to everything
- role=SERVICE_ACCOUNT has access to everything, if it has needed permissions
- everybody can read every public component

**Comment by philecs** [comment]
Tested and works.
