### ISSUE TITLE
Add multi-tenancy and authorization support in Integration Component Repository

### ISSUE THREAD

**Issue by sachmerz** [openintegrationhub/openintegrationhub#5]
Integration Component Repository (CR) requires multi-tenancy support. As in the [conceptional elaborations](https://github.com/openintegrationhub/Microservices/blob/master/RepositoryManagement/IntegrationComponentRepository.md#conceptional-elaborations) described, the Docker images referenced by the CR can either be on Dockerhub or in a private Docker repository. In both cases, the user/tenant can provide credentials (access token, etc.) to fetch a component from a remote repository.
These credentials need to be stored by OIH in context of a tenant (or even referenced by a flow?).

**Comment by philecs** [comment]
@sachmerz is this one still up-to-date?

**Comment by sachmerz** [comment]
@philecs yes. Unless I missed something.
