### ISSUE TITLE
Delete the Memwatch in the IAM

### ISSUE THREAD

**Issue by DennisCES** [openintegrationhub/openintegrationhub#50]
As a OIH product owner, I want the memwatch in the IAM component to be deleted

---

**Acceptance Criteria:**
- [ ] Deleted memwatch-module

**Comment by philecs** [comment]
@DennisCES Please assign a label if the issue is relating to a specific service. Here: IAM

**Comment by sachmerz** [comment]
@DennisCES memwatch was removed.
