### ISSUE TITLE
IAM & IAM-utils validate the owners array

### ISSUE THREAD

**Issue by sachmerz** [openintegrationhub/openintegrationhub#516]
Discuss and define how all services should handle the owners in context of an organization/tenant.

Further details: Users can create entities in different services, e.g. secrets, flows, components, etc. If the owners array contains only the creator (id & type tuple), then a tenant admin cannot access the list of flows (or other entites) created by her organization directly. The only way to accomplish this would be by quering for each tenant user.

Currently, we have discussed the following approaches, but have not yet defined which one is more suitable for OIH:

* owners array should contain an entry, which cannot be modified by a user
  * this entry would have the id/type of the tenant and could have an additional property apart from *id* and *type*, e.g. *isEditable: Boolean*
  * this allows for authorization based solely on that property (e.g. show all organization flows, although current user is not part of that owners array, but a member of the organization, thus the organization/tenant is also an entry of owners and cannot be removed or modified by a user)
* there is a top-level property on each entity, which contains the tenant id

**Comment by philecs** [comment]
What is the status of this issue ❓
@sachmerz @heggert @pnedelko

**Comment by sachmerz** [comment]
We have discussed this issue in our last review and decided to add `tenant` property on top level of a model. An extra entry in owners array is therefore unnecessary.
