### ISSUE TITLE
Continue development of Integration Layer Service

### ISSUE THREAD

**Issue by SvenHoeffler** [openintegrationhub/openintegrationhub#517]
After the initial sample implementation of the ILS, it can now be expanded and improved to meet the standards of a full microservice specifically for the merging/aggregation functionality.

---

**Acceptance Criteria:**
- [x] A custom schema could be defined in `def` object and then it serves as a validator for the `payload` in the whole chunk object
- [x] Split an object - provide a `splitSchema` object which defines the outgoing object format after splitting 
- [x] Provide technical documentation

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
@SvenHoeffler can you provide some acceptance criteria (possibly after the next meeting with the other guys)?
