### ISSUE TITLE
Admin UI: connect to component repository

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#518]
As a user I want to manage components.

To Do's:

- [x] User can add a component
- [x] User can see all components
- [x] User can patch a component
- [x] User can delete a component

---

**Acceptance Criteria:**
- [x] User can perform all ToDo's via web ui

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
@falkvoigt  I guess everything is done here?

**Comment by falkvoigt** [comment]
The Acceptance is missing should be done from one of your site?

**Comment by philecs** [comment]
Ok - I'll test it today and provide feedback.

**Comment by philecs** [comment]
Was able to perform all steps 👍 

Accepted 👍 @falkvoigt
