### ISSUE TITLE
Add Cors header for web-ui

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#528]
Derived from [#467](https://github.com/openintegrationhub/openintegrationhub/issues/467#issuecomment-501165051): 

`To get Flows and Components working on for Web-ui we need CORS Header implemented. In Locals tests all operations works fine`

---

**Acceptance Criteria:**
- [x] CORS Header added

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by SvenHoeffler** [comment]
CORS headers are now fully functional and the UI can communicate with the Flow Repo
