### ISSUE TITLE
Add CORS Header for component repository

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#529]
Derived from [#467](https://github.com/openintegrationhub/openintegrationhub/issues/467#issuecomment-501165051): 

`To get Flows and Components working on for Web-ui we need CORS Header implemented. In Locals tests all operations works fine`

---

**Acceptance Criteria:**
- [x] CORS Header added

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by pnedelko** [comment]
@philecs done. In Readme.md of the Component Repository there is an env var `CORS_ORIGIN_WHITELIST` that whitelists CORS origins.
