### ISSUE TITLE
[SKM] Document Secure Key Management Concept

### ISSUE THREAD

**Issue by sachmerz** [openintegrationhub/openintegrationhub#53]
Provide a concept similar to that of IAM which describes the idea, architecture and usage.

**Acceptance Criteria:**
- [x] Concept has been published on Github ([Link to concept](https://github.com/openintegrationhub/Microservices/blob/master/SecureAccessControl/SecureKeyManagementConcept.md))

**Comment by hschmidthh** [comment]
I think we can go with this.

**Comment by StephanPfeiffer** [comment]
@drobiazko Please provide your feedback.

**Comment by philecs** [comment]
@sachmerz and @drobiazko any updates on this issue?

**Comment by philecs** [comment]
@sachmerz can you add the following information to the top of the document?

---

**Creator:** Name (@GitHubAlies), Firm <br>
**Last Modified:**  <br>
**Last Modifier:** <br>
**Version:**  <br>

---

**Comment by philecs** [comment]
@sachmerz can you pls create a pull request for this issue and assign @drobiazko? 

That way we can ensure the review request is seen by the reviewer :)

**Comment by philecs** [comment]
Current SWAGGER specifications: https://app.swaggerhub.com/apis/drobiazko/secrets-service/0.0.5

**Comment by philecs** [comment]
Decisions derived from meeting:


- [ ] provide a way to define a `name` for an `auth-client`
- [ ] leave `refreshTokenUrl` inside the `auth-client`
- [ ] supported secret types: `three-legged-oauth1`, `three-legged-oauth2`, `basic` and `mixed`
- [ ] we don't need a specific `/token` path as we can trust the connector even though it will have access to a `refresh_token` inside a secret. A connector won't be able to refresh any tokens as it does not have an access to `client_id` and `client_secret` that are stored in `auth-client`.

**Comment by philecs** [comment]
As we have agreed upon these points and the [API specifications](https://app.swaggerhub.com/apis/drobiazko/secrets-service/0.0.5) for this service I guess we can close it. Is there any further need for discussion? @drobiazko and @sachmerz ?
