### ISSUE TITLE
Bug: patch component in Component Repository is not possible

### ISSUE THREAD

**Issue by DennisCES** [openintegrationhub/openintegrationhub#542]
Currently we cannot patch a component in the component repository

**Further description:**

While trying to update components, this error occurs:

"Errors": "message":"Cannot convert undefined or null to object" [500] (Internal Server Error)
---

**Acceptance Criteria:**
- [ ] Fixed bug, therefore patching is possible/working again

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by pnedelko** [comment]
@DennisCES more details required: request payload, component ID.

**Comment by DennisCES** [comment]
This is the request payload: 

```json
{
      "distribution": {
        "type": "docker",
        "image": "elasticio/timer:ca9a6fea391ffa8f7c8593bd2a04143212ab63f6"
      },
      "access": "public",
      "name": "Timer",
      "description": "My xxx Timer component",
      "descriptor": {
        "actions": [],
        "triggers": []
      },
      "owners": [
        {
          "id": "5bcee3048bbfec0010367bd7",
          "type": "user"
        }
      ]
 }
```

Respond (body): 
"message": "Cannot convert undefined or null to object"

**Comment by philecs** [comment]
@pnedelko and @DennisCES status update?
