### ISSUE TITLE
Audit log handles global IAM events

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#558]
According to GDPR (DSGVO) a user has the right that his/her data is deleted upon request.

Furthermore, if a user or tenant is deleted in IAM, each service that is holding information about this user/tenant has to delete this information.

**To Do's:**

- [ ] ...
- [ ] ...

---

**Acceptance Criteria:**
- [x] Audit log handles IAM global events appropriately 

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by SvenHoeffler** [comment]
Upon user deletion, Audit log will now search through its data set for that user's id and anonymise it.
