### ISSUE TITLE
[SKM] CRUD-API for key-value pairs

### ISSUE THREAD

**Issue by sachmerz** [openintegrationhub/openintegrationhub#56]
As a user, I want to be able to read, modify, delete secrets so that I am able to manage my key pairs.

Further description:
Implement a SKM service, which allows CRUD operations on keys. The keys should be stored in such a way, that they can be later assigned to a tenant or a user. In case of Hashicorp Vault, investigate if we can save the keys with a path like structure e.g. tenant/${tenantId}/secretname

---
**Acceptance Criteria:**
- [x] Secrets can be created, read, updated and deleted

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
@heggert and @sachmerz do we have a new status for this issue?

**Comment by sachmerz** [comment]
@philecs we're on it and currently implementing CRUD operations for secrets and a few predefined secret types. @heggert can probably provide more details. 
We will push the code by the beginning of the next week.
