### ISSUE TITLE
Expand API guidelines

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#584]
Some API docs related things need to be clarified as we haven't specified a standard yet.

**Further description:**

- [x] API versioning (e.g. `api/v1/..`)
- [x]  Should **POST** request body contain the key "data" or should it only contain the actual content of the body
- [x] Define a response body of POST requests

Examples related to the 2nd point:

With `data` keyword (extract metadata repo):

```json
{
  "data": {
    "name": "string",
    "description": "string",
    "value": {
      "$id": "address",
      "required": [
        "street_address",
        "city",
        "state"
      ],
      "properties": {
        "street_address": {
          "type": "string"
        },
```

Without `data` keyword (Extract flow repo):

```json
{
  "name": "My Flow",
  "description": "This flow takes actions at regular invervals based on a set timer.",
  "graph": {
    "nodes": [
      {
        "id": "step_1",
        "componentId": "5ca5c44c187c040010a9bb8b",
```

---

**Acceptance Criteria:**
- [x] Workgroup agreed upon todo's
- [ ] New standards documented within the [serviceAPIguidelines](https://github.com/openintegrationhub/openintegrationhub/blob/master/docs/guidelines/serviceAPIGuidelines.md)

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
@SvenHoeffler

**Comment by SvenHoeffler** [comment]
Results of the call on 18.06:

- API Versioning: Including API version in the path should remain optional for the time being, as we do not have an overall versioning strategy so far

- POST request bodies: The request body of a POST/PUT/PATCH request should only contain the plain object itself, without further wrapping it inside a `data` object or similar. E.g.:
```
{
  "name": "My Flow",
  "description": "This flow takes actions at regular invervals based on a set timer.",
  "graph": {
    "nodes": [
      {
        "id": "step_1",
        "componentId": "5ca5c44c187c040010a9bb8b",
      }
    ]
  }
}
```

- POST response bodies: The response to a POST/PUT/PATCH request that creates or modifies an object should contain the resulting new object. The format of the response should be identical to what the service would return when GETting the same object, i.e. featuring the `data` and `meta` properties. E.g.:
```
data: {
  "name": "My Flow",
  "description": "This flow takes actions at regular invervals based on a set timer.",
  "graph": {
    "nodes": [
      {
        "id": "step_1",
        "componentId": "5ca5c44c187c040010a9bb8b",
      }
    ]
  }
}
meta: {}
```

@pnedelko , @sachmerz , please let me know if I missed anything.

**Comment by philecs** [comment]
Thank you @SvenHoeffler

**Comment by philecs** [comment]
Guideline expanded
