### ISSUE TITLE
Base Implemenation of Conflict Management

### ISSUE THREAD

**Issue by hschmidthh** [openintegrationhub/openintegrationhub#587]
As a developer, I want to have an access to a public `npm` package which functionality could be implemented in an OIH adapter. This package(**CFM**) should be able to resolve potential conflicts between objects.

---

**Acceptance Criteria:**
- [x] A `npm` package is published and available to download on [npmjs](https://www.npmjs.com/).
- [x] CFM successfully resolves a conflict between two objects. The first one is coming from a *Transformer* and the other one is coming from the target application.
- [x] CFM is implemented and tested with an OIH Adapter ([snazzy-adapter](https://github.com/openintegrationhub/snazzy-adapter)).

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
- [x] Reference implementation within [snazzy contacts adapter](https://github.com/openintegrationhub/snazzy-adapter/blob/master/lib/actions/upsertPerson.js#L39)
