### ISSUE TITLE
Identity & Access Management (IAM)

### ISSUE THREAD

**Issue by sachmerz** [openintegrationhub/openintegrationhub#59]
Develop the first working version of IAM which allows to create tenants, service accounts, users and assign the users with a role to multiple tenants. Also provide a mechanism to verify authentication and authorization when interacting with different services supporting our IAM based auth.

**Comment by philecs** [comment]
@sachmerz is this epic finished as #4 and #46 are closed?

**Comment by sachmerz** [comment]
@philecs I've limited the scope of this epic to what we already support, so that the epic can be closed. 
There are still some open question we need to discuss with @drobiazko, e.g. token revocation and the expiration of tokens. Moreover, when we add additional service to OIH which require interaction with IAM, new issues may arise, but they don't necessarily need to be assigned to this epic.
