### ISSUE TITLE
Web-UI: Metadata repository

### ISSUE THREAD

**Issue by sachmerz** [openintegrationhub/openintegrationhub#590]
Connect the metadata repository api to web ui.

**Acceptance Criteria:**
- [x] Local schema can be uploaded (zip file or multiple files?)
- [x] CRUD domains
- [x] CRUD schemas

---

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
Functionality tbd

**Comment by philecs** [comment]
For now we focus on uploading a single file via web ui

**Comment by philecs** [comment]
CRD Schemas possible. Update tbd
