### ISSUE TITLE
Component Repository should emit audit log relevant events

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#597]
Currently, the component repository does not emit any events.
In order to track user activity in the audit log, it should at least emit the following events:

- component.created
- component.updated
- component.deleted

---

**Acceptance Criteria:**
- [ ] Component Repository emitts 

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by RobinBrinkmann** [comment]
Backlog clean-up. Closing of outdated issues.
