### ISSUE TITLE
Update existing service documentation for Secret Service and IAM

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#603]
The current service documentation is outdated and have to be updated.

**Further description:**

- [x] [IAM docs](https://github.com/openintegrationhub/openintegrationhub/tree/master/docs/services/IAM)
- [ ] [SecretService docs](https://github.com/openintegrationhub/openintegrationhub/blob/master/docs/services/SecretService.md)

---

**Acceptance Criteria:**
- [ ] Documentation updated

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by RobinBrinkmann** [comment]
Please publish the new docs in our new developer site repo. 

You can just update these files:
https://github.com/openintegrationhub/openintegrationhub.github.io/blob/master/docs/Services/IdentityManagement.md

https://github.com/openintegrationhub/openintegrationhub.github.io/blob/master/docs/Services/SecretService.md

**Comment by philecs** [comment]
readme.md updated.
missing documentation is covered in #783
