### ISSUE TITLE
Fix attachments storage specs

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#617]
As a _user type_, I want to _task_ so that _goal_.

**Further description:**

- [x] Fix request body batch delte request - remove `id`  and `status`
- [x] Adjust response body batch delte request (conditions array)
- [x] Remove GET messages endpoint from Specs
- [x] Remove `range` parameter from endpoints
- [x] Documented supported ID format for creating a message
- [x] Document possible conditions for batch delete
- [x] Change status code for successful deletion (`DELETE objects/{id}`) to 204 instead of 200
- [x] Change status code for successful batch delete request to 202 instead of 201
- [x] Change status code for getting batch delete request status to 200 instead of 201

---

**Acceptance Criteria:**
- [ ] All todos solved

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by pnedelko** [comment]
@philecs 
- I've checked the UUID support: every existing version is supported. Mentioned it in Swagger.
- Conditions for Batch delete are also documented in Swagger schemas.
