### ISSUE TITLE
Web UI: Update start page

### ISSUE THREAD

**Issue by RobinBrinkmann** [openintegrationhub/openintegrationhub#634]
As a user, I want to see the most relevant information about my data synchronization right when I log in, so I can take actions quickly and don't miss anything.
As a user, I want to be able to jump to important functions from my start screen.

**Further description**

The current start page of the Web UI is empty. It should display all active flows, status report of data flow (what/how much data was processed? what systems are connected? what failed?) and shortcuts to basic functions, getting a flow overview or creating flows. 

---

**Acceptance Criteria:**
- [x] current hero-section is removed
- [x] content for the new start page is defined
- [x] start page is updated

---

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by RobinBrinkmann** [comment]
![Draft WebUi Startpage](https://user-images.githubusercontent.com/34723165/63685846-ab3d7e80-c800-11e9-9d2c-aaabaa9c3c0a.PNG)
![Login Screen](https://user-images.githubusercontent.com/34723165/63685856-b395b980-c800-11e9-8b48-d59fa8d50060.PNG)

**Comment by philecs** [comment]
@RobinBrinkmann @falkvoigt welcoming should also be in english
