### ISSUE TITLE
Test local installation on Mac

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#649]
- [ ] Follow instructions and install local oih version
- [ ] Document Mac specific configurations

---

**Acceptance Criteria:**
- [ ] All Mac specific configurations have been documented

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by SvenHoeffler** [comment]
This issue cannot be tested/verified for the time being, as there is currently an unresolvable conflict between minikube and kubectl on Mac that makes minikube nonfunctional.
