### ISSUE TITLE
Implement cleanup system for component orchestrator

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#650]
This issue was derived from [#561](https://github.com/openintegrationhub/openintegrationhub/issues/561).

Quote:

```
Component Orchestrator stores not full copy of flows, but only [2 fields](https://github.com/openintegrationhub/openintegrationhub/blob/master/services/component-orchestrator/src/models/Flow.js#L4-L7): `graph` and `status`. Therefore it doesn't know whom that flow belongs to and can't properly react on `iam.user.deleted` event.
But we need to implement some cleanup system, so that no orphaned flows would keep running after a user has been deleted. I would propose to make it in the following way:

1. Flow repo could send a `flow.deleted` event when there no more owners left in owner array (or some other condition) and the flow is gonna be deleted. (Or `flow.stopping`, when the flow stays in the DB).
2. Component Orchestrator reacts on this event and stops the corresponding flows and deletes them from the DB.
```

**Further description:**

- [x] Discuss how deletion of flow owners in flow repo should be handled
- [x] Implement mechanims to handle deletion of all flows owners

---

**Acceptance Criteria:**
- [x] Deletion of multiple flow owners is handled by component orchestrator

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by pnedelko** [comment]
@philecs  In order to estimate an effort for Component Orchestrator we need to agree on the messages, which will be published to the event bus. If it's only `flow.stopping` then nothing to be changed in CO. If we introduce a new event, it would be around 8 sp.

**Comment by philecs** [comment]
Discussed with @pnedelko :

Currently the component orchestrator only stores a copy of the flow if a flow ist `active`.
Once the flow is stopped it deletes the copy.

As it is only possible to modify or delete a flow if it is inactive there is no need to implement a cleanup system in the component orchestrator.

E.G.: A flow is stopped --> Component Orchestrator delete its copy --> all owners are removed from the owners array. No need to send any additional event to component orchestrator as it does not store any information about the flow at the time its modified.
