### ISSUE TITLE
Analyze changes in IAM memberships

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#653]
IAM memberships have changed and some review is needed if the other services are affected.

---

**Acceptance Criteria:**
- [ ] tbd

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by pnedelko** [comment]
Services that require changes:
- attachment storage service
- component repository
