### ISSUE TITLE
Add applicationUid to component repo

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#654]
As decided a user/admin creates the applicationUid. Therefore a new attribute is needed in component repository to store this information.

**Further description:**

-

---

**Acceptance Criteria:**
- [ ] Add applicationUid to component repository

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by pnedelko** [comment]
done
