### ISSUE TITLE
Discuss Scope of Hierarchy & Relationship Management

### ISSUE THREAD

**Issue by hschmidthh** [openintegrationhub/openintegrationhub#66]
Document the function of the MS Hierarchy & Relationsship Management

Further description:
This MS ist not documented yet

---

**Acceptance Criteria:**
- [ ] Publish Concept on GitHub
- [ ] Concept reviewed by workgroup
- [ ] Concept accepted

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
Closed in favor of #342
