### ISSUE TITLE
Metadata crashes when an invalid schema is uploaded

### ISSUE THREAD

**Issue by sachmerz** [openintegrationhub/openintegrationhub#667]
**Describe the bug**
UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token < in JSON at position 6
    at JSON.parse (<anonymous>)
    at Object.processContent (/usr/src/app/src/transform/index.js:153:36)
    at /tmp/node_modules/path-loader/index.js:187:19
    at new Promise (<anonymous>)
    at /tmp/node_modules/path-loader/index.js:177:16
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
"  

**To Reproduce**
Upload an invalid JSON(Schema), e.g. in a zip-archive.

**Comment by philecs** [comment]
Now throws an timeout error: 

![image](https://user-images.githubusercontent.com/29949654/63270816-2949d480-c299-11e9-9ca5-ea1880d3e68e.png)

Code: 

https://github.com/openintegrationhub/openintegrationhub/blob/9b8ad7e4232ebf0c4552347f63e795753de6aa0c/services/integrationtests/metadata-repository/test.spec.js#L365-L384
