### ISSUE TITLE
Collect requirements for conflict management

### ISSUE THREAD

**Issue by hschmidthh** [openintegrationhub/openintegrationhub#67]
As a product manager I want requirements from all stakeholders to define the scope of the conflict management (service).

**Further description:**

As a basis to create specs for future implementation we need to collect requirements from all stakeholders. These requirements must be consolidated for further processing.

---

**Acceptance Criteria:**
- [ ] Requirements for conflict management (service= have been consolidated and documented

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
Have we already scheduled an appointment for this discussion?

**Comment by hschmidthh** [comment]
We did have a call with Fraunhofer and talked about their concept. We will define a use case on basis of SnazzyContacts in January.

**Comment by StephanPfeiffer** [comment]
@hschmidthh 

I think we need a overall summary / catalog of possible conflict use cases that can occure in our setup or technical framework.
In a second step we need to assess and prioritize these use cases and identify the attached micro services to these conflicts.
Third step would be a technical specification how these conflicts can be solved by using our micro services framework and also define if we have a central service that provides conflict management features to all other services - or using a distributed approach with local conflict management features at different micro services.

**Comment by hschmidthh** [comment]
> @hschmidthh
> 
> I think we need a overall summary / catalog of possible conflict use cases that can occure in our setup or technical framework.

We are talking about conflicts on data basis, e. g. sync-issues. Your point sounds for me, as if you are talking about technical issues between the services. Or did i misunderstood you?

**Comment by philecs** [comment]
What we had is mind is that we have a clear understanding of the problem that this service tries to resolve. And for this purpose, in our opinion, as a first step, we need to collect possible use cases.

A second step could be e.g. a classification of the conflicts (will be solved by the service or not).

**Comment by philecs** [comment]
Any updates here? Are there any open points that need to be discussed?
