### ISSUE TITLE
Collect and consolidate requirements for Metadata Service Scope

### ISSUE THREAD

**Issue by hschmidthh** [openintegrationhub/openintegrationhub#68]
As a product manager I want requirements from all stakeholders to define the scope of the meta data service.

**Further description:**

As a basis to create specs for future implementation we need to collect requirements from all stakeholders. These requirements must be consolidated for further processing.

---

**Acceptance Criteria:**
- [ ] Requirements for meta data service have been consolidated and documented

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
First conceptional elaborations: https://github.com/openintegrationhub/Microservices/blob/metaDataService/RepositoryManagement/MetaDataService.md

**Comment by philecs** [comment]
PR opened in microservice repo
https://github.com/openintegrationhub/Microservices/pull/43

**Comment by philecs** [comment]
@drobiazko any updates on the meta data service concept review?

**Comment by philecs** [comment]
This service will be discussed after we have an agreement regarding IAM and secret service

**Comment by philecs** [comment]
What is the status here?

**Comment by sachmerz** [comment]
Current state of requirements is here: https://github.com/openintegrationhub/Microservices/blob/metaDataService/RepositoryManagement/MetaDataService.md
There wasn't much new to add, at least at this state of progress.

@drobiazko has also provided a first draft/proposal: https://app.swaggerhub.com/apis/elasticio/metadata-service/0.0.2#/
