### ISSUE TITLE
SDF object validation against a schema from Meta Data Repository 

### ISSUE THREAD

**Issue by shterion** [openintegrationhub/openintegrationhub#680]
As a developer, I want to validate the incoming object from SDF Adapter against a schema from Meta Data Repository. The `valid` property depends on the validation result and the response from ILS should have the following format:
```json
{
  "data": {
    "valid": true
  },
  "meta": {}
}
```
---

**Acceptance Criteria:**
- [x] ILS successfully validates an incoming object against a fetched schema from Meta Data Repository

---

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
Working
