### ISSUE TITLE
Flow repository should stop a flow if the last owner owner has been removed

### ISSUE THREAD

**Issue by pnedelko** [openintegrationhub/openintegrationhub#682]
When a user has been deleted in IAM service Flow Repo receives an event `iam.user.deleted` and removes that user from the `owners` array of flows. In case the flow is active there are still running containers in K8s, but it doesn't make sense, since this integration flow is not interesting for anybody.

## Proposal
Flow repository could stop a flow in such cases by raising the `flow.stopping` event, which will be handled by Component Orchestrator and, therefore, K8s containers will be deleted.

---

**Acceptance Criteria:**
- [x] Flow orchestrator stops a flow when there are no more owners left

---

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by SvenHoeffler** [comment]
Flow Repository now has a function to detect all orphaned flows, which will be automatically used when a user is deleted. For each orphaned flow that is still active, a stopping event will be spawned.
