### ISSUE TITLE
Communication Router authentication & authorization

### ISSUE THREAD

**Issue by sachmerz** [openintegrationhub/openintegrationhub#7]
Webhooks, which the OIH provides for external triggers [(conceptional elaborations)](https://github.com/openintegrationhub/Microservices/blob/master/MessageProcessing/CommunicationRouter.md#conceptional-elaborations), should ideally be secured with credentials/authorization mechanisms provided by IAM or with a HMAC (similar to current elastic platform) managed solely by communication router itself.

**Comment by philecs** [comment]
@sachmerz is this one still up-to-date?
