### ISSUE TITLE
Adapters fail to start up with elasticio-sailor version 2.4.2

### ISSUE THREAD

**Issue by shterion** [openintegrationhub/openintegrationhub#745]
Adapter's dependency ` elasticio-sailor` was updated to version `2.4.2` and after that change, the flow which contains an adapter with this version could not be started.  The error message from pod's logs is the following: 
`Error: ELASTICIO_CONTAINER_ID is missing at throwError (/usr/src/app/node_modules/elasticio-sailor-nodejs/lib/settings.js:76:15)`

**To Reproduce**
1. Update `elasticio-sailor-nodejs` to `2.4.2`
2. Push adapter's image to docker hub
3. Create a new flow
4. Start the flow
5. Look at pod's logs

**Expected behavior**
The flow should start successfully.

**Comment by pnedelko** [comment]
Hi @shterion . It should be fixed after one of the recent PRs to the Component Orchestrator. Could you try it again and give your feedback? Thank you!

**Comment by shterion** [comment]
@pnedelko thank you for the response :+1: It seems to work now!
