### ISSUE TITLE
DataHub should push relevant event to the event bus

### ISSUE THREAD

**Issue by pnedelko** [openintegrationhub/openintegrationhub#753]
Possible events:
- master data record is added
- master data record is updated
- ref is added
- ref is updated

---

**Acceptance Criteria:**
- [ ] Events are published to the event bus

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by RobinBrinkmann** [comment]
Backlog clean-up. Closing of outdated issues.
