### ISSUE TITLE
Deploy Identity and Access Management

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#77]
As a product manager I want all available services to be deployed on a central k8s cluster, so that the team has a central instance for testing and presentation purposes.

**Further description:**
The identity and access management (IAM) must be deployed on our central k8s cluster according to our defined deployment process.

---

**Acceptance Criteria:**
- [x] Walk-through for deployment of identity and access management created
- [x] Walk-through reviewed by workgroup
- [x] IAM deployed on central GCP

**Comment by philecs** [comment]
@falkvoigt do we have some progress here as the service is up and running under: http://iam.openintegrationhub.com/api-docs/ ?

**Comment by falkvoigt** [comment]
Yes the service is deployed. @DennisCES should create the Walk-through with me together. And we need to decide who is the reviewer for that.

**Comment by philecs** [comment]
Great. Thanks for the update :+1:

**Comment by falkvoigt** [comment]
As of #103 we have a detailed Documentation for Deployment. I will add a small part for init the Services

**Comment by falkvoigt** [comment]
Please Review this Ticket

**Comment by philecs** [comment]
@fdegenhr can you review the [build and deployment process guidelines](https://github.com/openintegrationhub/openintegrationhub/blob/6d0b42cde26fddc3745184842c7066e2fa0557de/Guidelines/Build%20and%20deploy%20process%20documentation.md)?

**Comment by fdegenhr** [comment]
reviewed.
Looks good to me!

**Comment by philecs** [comment]
@falkvoigt can you pls create a pull request?

**Comment by philecs** [comment]
@falkvoigt what exactly must be reviewed?

**Comment by falkvoigt** [comment]
Because there where no changes to service just Config and nearly all is done in Kubernetes it makes no sense to go the PR way. 
And i'm sorry but i have pushed the  config changes in the deployment.yaml directly to master :(.

we should take away permissions pushing to master from people like me :) as Ops i have worked at master level all the time and need to lern the PR way of life :)

**Comment by philecs** [comment]
"PR way of life" I like that haha

Okay no problem. If no further review is needed you can move the issue to "done". But pls do not "close" it - we'll do this in the sprint review.
