### ISSUE TITLE
Logging Service base implementation

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#773]
As discussed in the last sprint we agreed on using GrayLog for the logging service.
This service must now be configured.

---

**Acceptance Criteria:**
- [ ] Base implementation logging service finished

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by sachmerz** [comment]
As discussed with Pavel:
* Flow-Id, Step-Id as annotations/labels for each pod
* Reference implementation using GCP Stackdriver API

**Comment by pnedelko** [comment]
API endpoint is exposed through the flow-repository service:
http://flow-repository.openintegrationhub.com/flows/5c9244fc62278a001ad3a831/steps/step_1/logs?pageSize=1

@sachmerz FYI
