### ISSUE TITLE
Adapter Example Component

### ISSUE THREAD

**Issue by RobinBrinkmann** [openintegrationhub/openintegrationhub#780]
In order to make it easier for 3rd parties to develop adapters we need an example adapter that functions as a stub/starting point.

Example: [Elastic.io NodeJS Component](https://github.com/elasticio/petstore-component-nodejs)

---

**Acceptance Criteria:**
- [x] Example uploaded on GitHub
- [x] Example compliant with [QualityGuidelines](https://github.com/openintegrationhub/Connectors/blob/master/QualityCheckTemplate.md)

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
Looks good from my point of view :+1:

**Comment by RobinBrinkmann** [comment]
last minor updates dicussed. issue can be closed.
