### ISSUE TITLE
App directory should check if apps are in use when deleted

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#784]
As an admin, I want to make sure, that an app from app directory is not deleted if it is currently used by an active flow as this would lead to a blank app in the UI.

---

**Further description**

We might need a flow repo endpoint, which returns a list of active flows where a given app is currently used.

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by RobinBrinkmann** [comment]
In the process of streamlining the framework, the App Directory will soon be moved out of the monorepo. It will be kept in a separate repository as a reference and for anyone who wants to continue work on it. There will not be any maintenance by the core dev team.
