### ISSUE TITLE
Controlled error logging for connectors and services

### ISSUE THREAD

**Issue by sachmerz** [openintegrationhub/openintegrationhub#786]
An expected and catched error should be transmitted (e.g. via queue) to a service, which writes the error to a database. This allows users to identify issues with their flows and retrieve relevant info to resolve that issue. Such error entries are ideally automatically deleted via Mongo document TTL.

An error contains a context, e.g. `tenantId` and `flowId` allowing tenant users to filter their errors.

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by RobinBrinkmann** [comment]
Backlog clean-up. Closing of outdated issues.
