### ISSUE TITLE
Create global available domain schemas in test instance

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#789]
In order to make the hub and spoke model work it is necessary that each transformers provides domainId and schemaUri of the model it refences (per action).

The publicly available master data models must be accessible for each user (tenant overwhelming).

**Further description:**

---

**Acceptance Criteria:**
- [ ] Models publicly available

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by sachmerz** [comment]
Path to current available schemas: https://github.com/openintegrationhub/Data-and-Domain-Models/tree/master/src/main/schema

**Comment by RobinBrinkmann** [comment]
In the process of streamlining the framework, the Meta Data Repository will soon be moved out of the monorepo. It will be kept in a separate repository as a reference and for anyone who wants to continue work on it. There will not be any maintenance by the core dev team.
