### ISSUE TITLE
Scheduler should get flows from ICR

### ISSUE THREAD

**Issue by sachmerz** [openintegrationhub/openintegrationhub#8]
As oih operator I want the oih services to interact with each other so that I can properly operate the system.

**Further description:**

Currently the scheduler fetches flows from K8s CRD. (See [FlowsDao.js](https://github.com/openintegrationhub/openintegrationhub/blob/master/services/scheduler/src/FlowsDao.js#L16))

- [ ] Receive Flows from ICR instead of K8s CRD

---

- [ ] Flows are received from ICR

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by pnedelko** [comment]
@philecs this issue is going to be solved by https://github.com/openintegrationhub/openintegrationhub/issues/286. Could we close this one?
