### ISSUE TITLE
Auto update component docker images

### ISSUE THREAD

**Issue by RobinBrinkmann** [openintegrationhub/openintegrationhub#802]
The images on dockerhub should be updated whenever OIH components (adpaters/transofrmers) are updated on GitHub to always have the latest version available on Open Integration Hub deployments. 

This build pipeline should also include automated quality checks / tests. We need a guideline for this.

---

**Acceptance Criteria:**
- [ ] Decide on tooling e.g. dockerhub
- [ ] Guidelines of testing / qs are in place
- [ ] All existing components are setup and update automatically 

---

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by shterion** [comment]
- [x] Contacts adapter template
- [x] Contacts transformer template
- [x] SnazzyContacts adapter
- [x] SnazzyContacts transformer
- [x] WiceCRM adapter
- [x] WiceCRM transformer
- [x] dreamrobot adapter
- [x] dreamrobot transformer
- [x] github adapter
- [x] XWorks365 adapter
- [x] XWorks365 transformer
- [x] getMyInvoice adapter
- [x] getMyInvoice transformer
- [x] msoffice adapter
- [x] msoffice transformer
- [x] openhandwerk adapter
- [x] openhandwerk transformer
- [x] dropscan adapter
- [x] dropscan transformer
