### ISSUE TITLE
Review IAM API and provide feedback

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#82]
As a development lead I want my microservice to be reviewed, so that I know if it meets the needs of the open integration hub framework.

Further description:

Basaas wrote a [**concept for IAM**](https://github.com/openintegrationhub/Microservices/blob/master/SecureAccessControl/IAMConcept.md) and implemented the [**Identity and Access Management**](https://github.com/openintegrationhub/openintegrationhub/tree/master/services/iam). In order to make sure that the developed service meets the requirements of all partners and thus the oih framework it must be reviewed.

- [ ] Review API for IAM
- [ ] Provide feedback 

---

**Acceptance Criteria:**
- [ ] Feedback was provided

**Comment by philecs** [comment]
Do we already have an agreement for IAM service?

**Comment by philecs** [comment]
@drobiazko and @sachmerz do we already have an agreement for IAM service?

**Comment by philecs** [comment]
@drobiazko  will provide a list of required endpoints for elastic.io

**Comment by philecs** [comment]
What is the status here as we planned to release this service at 31.12.18

**Comment by drobiazko** [comment]
I'm still working on finalizing our version of the Swagger spec. However the we have now a good understanding on how the service API might look like to be generic and so suitable for everyone. The 1st draft was already provided to Basaas.

**Comment by drobiazko** [comment]
Here is the next version which might need some minor updates/fixes but in general we can consider it as final.

https://app.swaggerhub.com/apis/drobiazko/iam/0.0.2#/

**Comment by sachmerz** [comment]
Hi @drobiazko . We could extend the current IAM API without breaking much to achieve this: https://app.swaggerhub.com/apis/basaas5/oih-iam/1.1.0#/
Let us discuss the details in the next review.
