### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by bixmatech** [openintegrationhub/openintegrationhub#835]
**Describe the bug**
Error when installing

**To Reproduce**
openintegrationhub-master\minikube>kubectl apply -f ./2-IAM
secret/iam unchanged
service/iam unchanged
error: unable to recognize "2-IAM\\deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"

**Comment by RobinBrinkmann** [comment]
Sorry for this and thanks for letting us know. We will look into it.
@SvenHoeffler can you help?

**Comment by SvenHoeffler** [comment]
Hi, I'm currently trying to reproduce it, will let you know once I have success with that. However, one thing that does stand out is the part with 
```
secret/iam unchanged
service/iam unchanged
```
This suggests that there is already an instance of the IAM existing on your cluster. Have you tried installing the OIH on this cluster before? If so, completely deleting that cluster (via `minikube delete`) and starting from the top might work.

**Comment by SvenHoeffler** [comment]
Found the cause: Minikube updated recently, and the most recent version no longer supports the kubernetes API specified in some of the deployments. Porting those should not be too much of an issue, I will let you know once that is done. Thank you for the feedback!

**Comment by bixmatech** [comment]
We believe we found the problem and tested it and it worked. We used minikube v 1.3.1 instead of the latest and all worked well. Most likely that the higher versions of minikube started using Kubernetes v 1.16 as default 1, which possibly requires changes in yaml files like ""apiVersion: extensions/v1beta1" as it is not supported in Kubernetes v 1.16.

Let us know if any furthur tunings are required as we are just starting to check the platform and certainly not be fully aware of how it works.

**Comment by SvenHoeffler** [comment]
Yes, that's exactly the one. Changing the `apiVersion` to the newer `apps/v1`, and adjusting the syntax of the rest of the file to match, will make it work in the new version 1.5 of minikube. We're currently testing backwards compatibility of the new Kubernetes API, and as long as that doesn't cause too many issues we'll be switching over to `apps/v1' going forward.

**Comment by SvenHoeffler** [comment]
The new apiVersion appears to be backwards compatible to at least kubernetes version 1.11.10, so this should not cause any trouble. The k8s definitions used in the minikube installation have now been migrated to be compatible with the new api version and as such should also work with the most recent minikube version.
