### ISSUE TITLE
SetUp TravisCI for openintegrationhub

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#84]
Further description:
We need further investigation on how to use TravisCI with GitHub

- [x] Read through TravisCI docs
- [x] Setup TravisCI for OIH

---

**Acceptance Criteria:**
- [ ] TravisCI setup for OIH

**Comment by philecs** [comment]
How is the status here? All checkboxex have been marked as `done`.

**Comment by falkvoigt** [comment]
I would say that Ticket is done from Technical perspective. But needs some Documentation. Documentation is done by Dennis in the mail Ticket related Build/deployment Pipeline. So this Ticked could be closed.

**Comment by falkvoigt** [comment]
What is the Process here? Someone get a look on it?

**Comment by philecs** [comment]
I'll move the issue in the right section.
Output will be discussed at the sprint review on 1st of October.
