### ISSUE TITLE
Update triggers to be able to determine the type of operation

### ISSUE THREAD

**Issue by shterion** [openintegrationhub/openintegrationhub#852]
As a _user type_, I want to _task_ so that _goal_.

**Further description:**

---

**Acceptance Criteria:**
- [ ] Criteria 1
- [ ] Criteria 2
- [ ] Criteria N

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
@shterion So you want the triggers to recognize the type of operation (C-U-D) by itself?
Sounds like a good feature... but how will you incorporate into the existing flow architecure where you explicitly have to specify the operation (or at least define upsert or delete)?

**Comment by shterion** [comment]
@philecs this was the initial idea but now Data Hub is able to determine the operation type.

**Comment by philecs** [comment]
@shterion thanks, I remember now :)
