### ISSUE TITLE
Adjust connectors to receive AppUid and schemaUri from the outside

### ISSUE THREAD

**Issue by SvenHoeffler** [openintegrationhub/openintegrationhub#870]
Instead of hard-coding appUid and schemaUri inside a transformer, it should instead be able to receive it from the outside, e.g. the flow configuration.

---

**Acceptance Criteria:**
- [ ] Criteria 1
- [ ] Criteria 2
- [ ] Criteria N

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
The transformer explicitly refers to a cetain schema. 
I guess it will stay the same. If the underlying schema changes, the mapping must be adjusted as well and the hardcoded schemaUri could be changed.

Is there an advantage of adding it dynamically instead of hard coding it?

**Comment by SvenHoeffler** [comment]
@philecs 
We've now got the app directory, works as the source of truth for metadata surrounding a certain app and its connector, including the connected schema(s) and its appUid. As one schema may end up being located under different URIs at various points in time (e.g. across different OIH implementations, separate tenants, etc.), it now makes more sense to pass that data in from the outside.
