### ISSUE TITLE
Clicking some of the GitHub profile links in CONTRIBUTING.md don't lead you to the corresponding profile

### ISSUE THREAD

**Issue by jhorbulyk** [openintegrationhub/openintegrationhub#88]
**Describe the bug**
Clicking some of the GitHub profile links in CONTRIBUTING.md don't lead you to the corresponding profile

**To Reproduce**
1. Visit the file [CONTRIBUTING.md](https://github.com/openintegrationhub/openintegrationhub/blob/master/CONTRIBUTING.md)
2. Click on the handles for `@sachmerz` or either of the links for `@philecs`.

**Expected behavior**
You are on the GitHub profile of either `@sachmerz` or `@philecs`.

**Additional context**
[Problem is clear if you look at the .md source](https://github.com/openintegrationhub/openintegrationhub/blame/master/CONTRIBUTING.md#L37-L38)

**Comment by philecs** [comment]
links fixed
