### ISSUE TITLE
Kubernetes secrets are not being deleted

### ISSUE THREAD

**Issue by sachmerz** [openintegrationhub/openintegrationhub#915]
**Describe the bug**

**To Reproduce**
1. Setup ...
2. Start ...
3. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by blaggacao** [comment]
This is expected kubernetes behaviour. `kusomize live init` creates a custom resouce to maintain a handle on all created objects. If on a subsequent apply some of them are.missing, they will be purged. I'm implementing `kustomize` support in #1041

**Comment by RobinBrinkmann** [comment]
Backlog clean-up. Closing of outdated issues.
