### ISSUE TITLE
container-repository 401 Unauthorized

### ISSUE THREAD

**Issue by mlb5000** [openintegrationhub/openintegrationhub#916]
**Describe the bug**
After getting OIH deployed, I am able to access `web-ui` and login as admin. When I navigate to the Components page the component-repository API returns a 401 error, even though I'm logged in as Admin, with the admin role applied.

**To Reproduce**
1. Login to web-ui as admin
2. Navigate to Components
3. web-ui logs you out

The message from the component-repository Pod logs is

```
{"name":"component-repository","hostname":"component-repository-7c48dc7cb7-wvpn2","pid":28,"level":40,"status":401,"message":"Token invalid. Error: Error. Details: Authorization failed","msg":"Responding with error","time":"2020-01-14T22:03:57.935Z","v":0}
```

Component-Repository's IAM service account has the following permissions:

```
            "iam.token.introspect",
            "components.get"
```

**Comment by mlb5000** [comment]
On a whim, I added the following to the `component-repository/k8s/deployment.yaml` file and it started working.

```
    env:
        - name: INTROSPECT_ENDPOINT_BASIC
          value: "http://iam.mydomain.com/api/v1/tokens/introspect"
```

I also needed to add an entry for `CORS_ORIGIN_WHITELIST`

**Comment by RobinBrinkmann** [comment]
Thanks for letting us know! @SvenHoeffler, please double check and add the snippets to the genral file if needed.

**Comment by SvenHoeffler** [comment]
Yeah, the current .yaml is indeed missing the Introspection endpoint. It works on our current dev cluster because the endpoint defaults to it when not otherwise specified, but obviously that's unsuitable for deployments elsewhere. I'll adjust it today.

Thanks for the catch, @mlb5000 !

**Comment by SvenHoeffler** [comment]
The yaml now contains the necessary environment variables by default, making the procedure for changing them more visible. Changes have been merged.
