### ISSUE TITLE
secret-service API Documentation is broken

### ISSUE THREAD

**Issue by mlb5000** [openintegrationhub/openintegrationhub#917]
If you visit http://skm.openintegrationhub.com/api-docs the details for the individual requests results in an error message at the top of the Swagger page. The current Docker image does the same thing.

**Comment by RobinBrinkmann** [comment]
Assigned to Selim. Please check.

**Comment by sachmerz** [comment]
Thanks @mlb5000 for pointing that out. An updated version is now live.

**Comment by mlb5000** [comment]
This looks good now. Thanks @sachmerz
