### ISSUE TITLE
Additional custom deployment missing env variables

### ISSUE THREAD

**Issue by mlb5000** [openintegrationhub/openintegrationhub#922]
I mentioned a couple of these in #916 but here are the other options I had to add to add to get the deployment "fully" set up (in quotes because I'm still testing the deployment):

**secret-service**

I'm not 100% sure about these. I was troubleshooting some issues and saw that there were several environment variables defaulting to `openintegrationhub.com` domains that were not in the K8S configuration, so I added them to the deployment.yaml file.

```
        - name: IAM_API_BASE
          value: http://iam.domain.com/api/v1
        - name: INTROSPECT_ENDPOINT_OIDC
          value: http://iam.domain.com/op/userinfo
        - name: IAM_TOKEN_API
          value: http://iam.domain.com/api/v1/tokens/ephemeral
        - name: REDIRECT_URI
          value: http://skm.domain.com/hook
```

**web-ui**

```
        - name: ENDPOINT_APP_DIRECTORY
          value: http://app-directory.domain.com/api/v1
        - name: ENDPOINT_METADATA
          value: http://metadata.domain.com/api/v1
        - name: REPORTS_UI
          value: http://grafana.domain.com/d/apSj8axZk/overview?orgId=1
```

There also seems to be a mix of instances where configured URLs do or don't end with `/api/v1`. The `ENDPOINT_SECRETS` option in the YAML doesn't end with `/api/v1`, but the Secrets API does need that to function correctly (otherwise I would get a 404).

**Comment by RobinBrinkmann** [comment]
@sachmerz seems to be in your realm ;)

**Comment by sachmerz** [comment]
Appreciate your feedback and time, @mlb5000! We will update the missing or outdated parts in the yamls and docs. 

Almost all services rely on the IAM-utils library, which performs token introspection. This library requires at least following env vars to function properly (otherwise it defaults to openintegrationhub.com)

```
    process.env.IAM_API_BASE, // defaults to 'http://iam.openintegrationhub.com/api/v1'
    process.env.IAM_TOKEN,
    process.env.INTROSPECT_ENDPOINT_BASIC // default: 'http://iam.openintegrationhub.com/api/v1/tokens/introspect',
```
Some services like Secret Service and IAM use /api/v1 base, with a few exceptions (ie. /login /logout in IAM, healthchecks, docs, etc.)
