### ISSUE TITLE
Question on Adding Secrets on Web-UI

### ISSUE THREAD

**Issue by mlb5000** [openintegrationhub/openintegrationhub#924]
How is the Secrets UI on WebUI meant to work? As you can see in this video, the option for OA2_Authorization_Code leads to a blank form in the dialog, whereas "Mixed" just expects a raw JSON document like other places. Presumably, if I were using the Web UI, I would take one of the various auth-client Schemas from [The SKM API Docs](http://skm.openintegrationhub.com/api-docs) and enter it into the form for "Mixed"? Is that correct?

 [Video](https://drive.google.com/open?id=17sRCfBSX2ymdHdX0cnff-CvyVy0cijPo)

**Comment by RobinBrinkmann** [comment]
HI Matthew, that UI feature is kind of a first draft and far from perfect. Adding it via the API / in the flow is probabaly easier for now. 
@sachmerz maybe you can elaborate a bit on the question rg "mixed" and any additions you have planned for the future.

**Comment by mlb5000** [comment]
@RobinBrinkmann @sachmerz Ya I started adding Secrets directly using the API. Unfortunately I had to consult the `.spec` files directly to find valid examples, since the API Docs don't actually match the schemas expected by the service.

**Comment by sachmerz** [comment]
Hi @mlb5000,
you are right, the `OA2_Authorization_Code` is empty because there is no `AuthClient`. The AuthClients are stored in the Secret-Service `auth-clients` collection and have the following structure (example with Microsoft):

```
{
  "predefinedScope" : "offline_access",
  "endpoints" : {
    "auth" : "https://login.microsoftonline.com/common/oauth2/v2.0/authorize?prompt=select_account&scope={{scope}}&response_mode=query&state={{state}}&redirect_uri={{redirectUri}}&response_type=code&client_id={{clientId}}",
    "token" : "https://login.microsoftonline.com/common/oauth2/v2.0/token",
    "userinfo" : "https://login.microsoftonline.com/common/openid/userinfo"
  },
  "clientId" : "${YOUR_MS_CLIENT_ID}",
  "clientSecret" : "${YOUR_MS_CLIENT_SECRET}",
  "redirectUri" : "https://${YOUR_WEB_UI_URL}/hook",
  "mappings" : {
    "externalId" : {
      "source" : "access_token",
      "key" : "unique_name"
    },
    "scope" : {
      "key" : "scope"
    }
  },
  "__t" : "A_OA2_AUTHORIZATION_CODE",
  "type" : "OA2_AUTHORIZATION_CODE",
  "name" : "Microsoft oAuth2",
  "owners" : [
  ]
}
```
Same goes for a `OA1_THREE_LEGGED`, but we tested it only with Trello so far.

We use `MIXED` for an arbitrary JSON secrets. For simple username/password secrets one could also use the `SIMPLE` type with `username` and `passphrase` properties.

I will add the example later to the repository. Thanks for the feedback!

**Comment by mlb5000** [comment]
@sachmerz You are correct. I realized these were popping up when I started adding `auth-client` entries. It's much more useful triggered from an external system anyway :). I'll close this one.
