### ISSUE TITLE
Component orchestrator unable to retrieve flow secrets

### ISSUE THREAD

**Issue by mlb5000** [openintegrationhub/openintegrationhub#927]
I have a flow with nodes that reference a secret stored in the secrets service, but when the component docker instance calls back into the the orchestrator with its Basic auth of `iam_token:token`, the secret service rejects the API call with a CORS error. It looks like #594 was meant to make this work, but I don't see any commits referencing that ticket to follow along with the work.

I explicitly added an `origin` header in that call in `SecretsDao` that matches the host configured in `config/default.json`, and added that host to the whitelist on the Secret Service, and now I'm getting a 403. The service account for the `component-orchestrator` has the three permissions mentioned in the setup guide (https://openintegrationhub.github.io/docs/Getting%20Started/GCPInstallationGuide.html#create-a-service-account), but I'm guessing it's not enough to be able to access secrets not owned by the service account:

```
        "permissions": [
            "components.any.read",
            "iam.token.create",
            "iam.token.delete"
        ],
```

```
  {
    "name": "component-orchestrator",
    "hostname": "component-orchestrator-ffc57649c-kwbqf",
    "pid": 29,
    "service": "HttpApi",
    "flowId": "5e2cf08a3f2de6001b3c1b66",
    "stepId": "step_3",
    "level": 10,
    "secretId": "5e2caaffa0bb940012d83d39",
    "msg": "About to get secret by ID",
    "time": "2020-01-26T01:52:24.195Z",
    "v": 0
  },
  {
    "name": "component-orchestrator",
    "hostname": "component-orchestrator-ffc57649c-kwbqf",
    "pid": 29,
    "secretId": "5e2caaffa0bb940012d83d39",
    "level": 10,
    "opts": {
      "url": "http://secret-service.oih-dev-ns.svc.cluster.local:3000/api/v1/secrets/5e2caaffa0bb940012d83d39",
      "json": true,
      "timeout": 5000,
      "headers": {
        "authorization": "Bearer {{the component-orchestrator service account IAM token}}",
        "origin": "api-service.oih-dev-ns.svc.cluster.local"
      }
    },
    "msg": "Fetching the secret",
    "time": "2020-01-26T01:52:24.195Z",
    "v": 0
  },
  {
    "name": "component-orchestrator",
    "hostname": "component-orchestrator-ffc57649c-kwbqf",
    "pid": 29,
    "secretId": "5e2caaffa0bb940012d83d39",
    "level": 10,
    "statusCode": 403,
    "body": {
      "message": ""
    },
    "msg": "Failed to get the secret",
    "time": "2020-01-26T01:52:24.431Z",
    "v": 0
  },
  {
    "name": "component-orchestrator",
    "hostname": "component-orchestrator-ffc57649c-kwbqf",
    "pid": 29,
    "service": "HttpApi",
    "level": 50,
    "err": {
      "message": "Failed to fetch the secret 5e2caaffa0bb940012d83d39",
      "name": "Error",
      "stack": "Error: Failed to fetch the secret 5e2caaffa0bb940012d83d39\n    at OIHSecretsDao.findById (/usr/lib/component-orchestrator/services/component-orchestrator/src/dao/SecretsDao.js:39:15)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
    },
    "msg": "Node info request failed",
    "time": "2020-01-26T01:52:24.431Z",
    "v": 0
  }

```

Is there a way to grant access to the service account via permissions, or will I need to explicitly mark the Orchestrator service account as an owner on all secrets that need to be referenced by components in flows?

**Comment by mlb5000** [comment]
OK, I added the Orchestrator service account as an "owner" on both secrets used in this flow and the request is no longer denied, but now I get a 500 error `error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length`:

```
  {
    "name": "component-orchestrator",
    "hostname": "component-orchestrator-ffc57649c-kwbqf",
    "pid": 29,
    "secretId": "5e2caaffa0bb940012d83d39",
    "level": 10,
    "opts": {
      "url": "http://secret-service.oih-dev-ns.svc.cluster.local:3000/api/v1/secrets/5e2caaffa0bb940012d83d39",
      "json": true,
      "timeout": 5000,
      "headers": {
        "authorization": "Bearer {{orchestrator service account IAM_TOKEN}}",
        "origin": "api-service.oih-dev-ns.svc.cluster.local"
      }
    },
    "msg": "Fetching the secret",
    "time": "2020-01-27T14:09:13.426Z",
    "v": 0
  },
  {
    "name": "component-orchestrator",
    "hostname": "component-orchestrator-ffc57649c-kwbqf",
    "pid": 29,
    "secretId": "5e2caaffa0bb940012d83d39",
    "level": 10,
    "statusCode": 500,
    "body": {
      "message": "error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length"
    },
    "msg": "Failed to get the secret",
    "time": "2020-01-27T14:09:13.529Z",
    "v": 0
  },
  {
    "name": "component-orchestrator",
    "hostname": "component-orchestrator-ffc57649c-kwbqf",
    "pid": 29,
    "service": "HttpApi",
    "level": 50,
    "err": {
      "message": "Failed to fetch the secret 5e2caaffa0bb940012d83d39",
      "name": "Error",
      "stack": "Error: Failed to fetch the secret 5e2caaffa0bb940012d83d39\n    at OIHSecretsDao.findById (/usr/lib/component-orchestrator/services/component-orchestrator/src/dao/SecretsDao.js:39:15)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
    },
    "msg": "Node info request failed",
    "time": "2020-01-27T14:09:13.529Z",
    
```

**Comment by mlb5000** [comment]
Turns out the `secret-service` `CRYPTO_KEY` environment variable/secret is completely missing from all documentation, but is very important to set. Otherwise as soon as your `secret-service` restarts once all of your Secrets are now indecipherable. 

Worse, you can't actually set `CRYPTO_KEY`, because the config in the `service/secret-service/src/conf/index.js` overrides the settings in `lib/secret-service/src/conf/index.js`, and the former doesn't set `crypto.key` at all. That also explains why none of the Logging options seem to work. The key applied by `service` is `logging`, whereas `lib` expects `log`.

**Comment by sachmerz** [comment]
Hi @mlb5000,

the CRYPTO_KEY was added later on and apparently forgotten in the docs and not updated in the `deployment.yaml`. I'll create a PR with the update and try to update the docs. They are indeed outdated. You can also disable crypto via `CRYPTO_DISABLED` (Bool) env var.

For service accounts, we use persistent tokens, which are stored in the iam `tokens` collection.
If you want a service account to read the raw and unencrypted secret, it must have the `secrets.secret.readRaw` permission either on it's account or in the tokens collection (each token references the owner via `accountId`).

Here is an example of a persistent token:
```
{
    "type" : "PERSISTENT",
    "permissions" : [ 
        "components.get", 
        "iam.token.create", 
        "iam.token.delete"
    ],
    "accountId" : ObjectId("5cd4004d4faf3e00111af6a8"),
    "inquirer" : ObjectId("5bcee3048bbfec0010367bd7"),
    "description" : "Your description",
    "token" : "A9uvBXOEQGdhclrPLD5yMOqVmn0bfVZqoOlEkibP0WQuiGgnmxTSS241mQbNoUKsBQPwH9w",
    "initiator" : ObjectId("5bcee3048bbfec0010367bd7"),
    "tokenLifeSpan" : "-1"
}
```
Hope this helps. Let me know if I missed anything.

**Comment by mlb5000** [comment]
@sachmerz Interesting, I didn't see Persistent tokens mentioned in the setup documentation. Just to create a user of type `SERVICE_ACCOUNT` and call the token API for each of them.

**Comment by mlb5000** [comment]
@sachmerz My fork has this issue with the `CRYPTO_KEY` fixed. Because I have so much checked in and I don't currently have the time to pull individual things out into pull requests I'm just dropping references to my fixes throughout my tickets:

https://github.com/mlb5000/openintegrationhub/blob/mlb5000-wip/services/secret-service/src/conf/index.js (specifically Line 35)

**Comment by blaggacao** [comment]
fyi &mdash; I'm currently working on a better devops handel onto the deployment manifests at #1041 which should help oih developers to keep things more in sync.

**Comment by RobinBrinkmann** [comment]
Backlog clean-up. Closing of outdated issues.
