### ISSUE TITLE
attachment-storage-service NPM module missing

### ISSUE THREAD

**Issue by mlb5000** [openintegrationhub/openintegrationhub#928]
The `@openintegrationhub/attachment-storage-service` module referenced in `services/attachment-storage-service/package.json` isn't published to the NPM repository. Is someone able to get that deployed?

**Comment by pnedelko** [comment]
Hi @mlb5000. Yes, it's possible to publish it to the NPM.
But if you want to run the service on your local machine, you could use `yarn run start:dev` and will work, because of `yarn workspaces` feature.

**Comment by pnedelko** [comment]
Published the package: https://www.npmjs.com/package/@openintegrationhub/attachment-storage-service
