### ISSUE TITLE
Cleanup icr service

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#93]
As a quality manager I want a properly structured repository, so that I can start the build process.

**Further description:**
In order to pass the build process we need to restructure the icr service folder:

- [x] Delete mongo folder from services/integration-content-repository folder
- [x] Delete nginx-reverse-proxy folder from services/integration-content-repository folder
- [x] Delete nginx-server folder from services/integration-content-repository folder
- [x] Delete ubuntu-base folder from services/integration-content-repository folder
- [x] Move all files from icr-api folder one level up
- [x] Add yarn

---

**Acceptance Criteria:**
- [x] All todos fulfilled

**Comment by falkvoigt** [comment]
Build on Travis would work if useing the correct Docker image:
Step 1/11 : FROM icr_ubuntubase
pull access denied for icr_ubuntubase, repository does not exist or may require 'docker login'
child_process.js:645
    throw err;
    ^

**Comment by falkvoigt** [comment]
As defined in Call @hschmidthh will update dockerfile and commit other changes later on
