### ISSUE TITLE
Secret Service "successUrl"

### ISSUE THREAD

**Issue by mlb5000** [openintegrationhub/openintegrationhub#932]
I have a question about how the `successUrl` provided to `start-flow` is meant to be used when executing an Auth Flow. Right now, when you complete the loop on an OAuth2 flow using the secret service's `callback` endpoint, it returns an object like this:

```
{
    "data": {
        "successUrl": "",
        "secretId": ""
    }
}
```

However, wouldn't it make more sense for that function to perform a `302` redirect to the configured `successUrl` with the `secretId` as a query parameter instead? Otherwise the end user is going to be left staring at this raw JSON response.

On a somewhat related note, I updated my local copy of `secret-service` to do just this, however the `services/secret-service` code refers to `lib/secret-service` via an NPM package instead of packaging the local codebases together during their Docker build like other services do (e.g. `component-orchestrator`). Basically, this makes it impossible to deploy changes to things in `lib/secret-service` unless you have access to publish an updated NPM package.

**Comment by RobinBrinkmann** [comment]
@sachmerz please check.

**Comment by mlb5000** [comment]
@RobinBrinkmann @sachmerz I actually did this in my fork here and it does what I would expect as an end user: https://github.com/mlb5000/openintegrationhub/blob/mlb5000-wip/lib/secret-service/src/route/callback/index.js

**Comment by blaggacao** [comment]
Can this be closed since there is a referenced accepted pull request?
