### ISSUE TITLE
Starting a Cron flow loses all fields

### ISSUE THREAD

**Issue by mlb5000** [openintegrationhub/openintegrationhub#933]
Steps to recreate:

1. Create a new flow that has the `cron` field set.
1. Start the flow

The flow will lose all properties except for a handful, including the all important `status` field. This is due to the Scheduler service having an incomplete definition for the Schema of a `Flow`. When I brought the schema definition over from `flow-repository` this issue does not happen **but** another one still does. 

The `name` and `description` fields also get blown away when `flow.starting` is sent out, I believe by both the Webhooks and Component-Orchestrator services. Each has an incomplete schema for `Flow`, and each listens for `flow.starting` and eventually manipulates the Flow object.

All in, the Component-Orchestrator, Webhooks, Flow-Repository, and Scheduler services all need to have agreement on what the `Flow` schema looks like, as it does not look like Mongoose understands "incomplete" schemas. If there is a way to configure Mongoose to patch in _only_ what keys exist in the local instance of the object that would be fine too. Otherwise shared schemas should be collected somewhere and referenced as needed.

**Comment by pnedelko** [comment]
@mlb5000 the `flow-repository` is the only source of truth and has a complete definition of the Flow schema. Component orchestrator, scheduler and webhooks store only the data they require for processing. For example, they don't care about `name` and `description` fields. Webhooks service is not interested in `cron` field. So this is all intentional.

**Comment by SvenHoeffler** [comment]
Is this on a local installation using minikube? We used to have an issue where a misconfigured secret there lead to services accidentally overwriting one another's documents, but that ought to have been fixed as of https://github.com/openintegrationhub/openintegrationhub/pull/759

**Comment by mlb5000** [comment]
@pnedelko **You can either read this or read the next paragraph since that's the real issue in my configuration** I figured that was the intent of the sparse schemas, but I'm only describing what I witnessed. I was only able to resolve this issue and keep things from destroying keys in Flow objects they themselves were not aware of by removing the "partial" definitions of Flow across those services, and replacing it with the full schema. The other services even remove the `dueExecution` key, which causes a cron service to never be executed.

@SvenHoeffler No this is a full K8S deployment, but wait...each service is supposed to have its **own** database? My services are all sharing the same mongodb connection string (and therefore database). I don't recall seeing this mentioned anywhere in the GCP installation documentation. Is it in there and I just overlooked it?

**Comment by SvenHoeffler** [comment]
@mlb5000 
Ah yes, they do need their own databases. They can share a single MongoDB deployment, but each service's connection string should point to a separate internal database. E.g. the Flow Repository could point to `mongodb://[user]:[password].[your-namespace].svc.cluster.local:27017/flowRepository`, while the Scheduler would point to `mongodb://[user]:[password].[your-namespace].svc.cluster.local:27017/scheduler`.

This is necessary to guarantee a clean encapsulation and make certain that separate services cannot not accidentally write into each other's data, which is what appears to have happened here. 

But you are of course correct that this is not sufficiently documented. Thank you for catching that!

**Comment by mlb5000** [comment]
@SvenHoeffler ok great, I'll make that repair to my secrets files and get my environment updated!

**Comment by RobinBrinkmann** [comment]
@mlb5000 I hope this is solved now. Can I close the issue or do you need further support on this topic?
