### ISSUE TITLE
Question for setup of openintegration

### ISSUE THREAD

**Issue by sanketsak** [openintegrationhub/openintegrationhub#942]
Hi,

I am trying to setup openintegration on my Ubuntu 18.04.3 (LTS) x64 on Digital ocean server.
i changed the url with my domain in ingress.yaml
I am done with setup kubectl apply -f ./1-Platform and also host rule setup.

I used my own domain to host setup as below

echo "$(minikube ip) app-directory.abc.com iam.abc.com skm.abc.com flow-repository.abc.com auditlog.abc.com metadata.abc.com component-repository.abc.com dispatcher-service.abc.com webhooks.abc.com attachment-storage-service.abc.com data-hub.abc.com ils.abc.com web-ui.abc.com" | sudo tee -a /etc/hosts

is the setup will work ok?

becuase i am trying to setup access service account and its says url doesn't exist means request doesn't send on iam.abc.com/login so may i know what i need to be change or correct to work?

**Comment by SvenHoeffler** [comment]
Hi! Have you run `kubectl apply -f ./2-IAM` yet? If you have, try `minikube dashboard` and see whether the IAM service is actually live and reachable.

**Comment by sanketsak** [comment]
i execute both but still IAM service is still not reachable.
![image](https://user-images.githubusercontent.com/16351265/79848514-ccca2680-83de-11ea-8873-02dfbab19ed5.png)

here you see the image which i execute the command and what responde it but service is not lived yet.
i am trying to login request but it can not reach the url.

**Comment by sanketsak** [comment]
What can i do further now?

**Comment by blaggacao** [comment]
fyi &mdash; I'm currently working on a better devops handel onto the deployment manifests at #1041
