### ISSUE TITLE
Cors errors in component repository swagger

### ISSUE THREAD

**Issue by jkopen** [openintegrationhub/openintegrationhub#952]
When using the swagger documentation of the component repository some calls never succeed, because of a CORS configuration problem.

**To Reproduce**
1. Login with Token
2. Get component uid
3. Try to update the component
    
**Expected behavior**
Component will not be updated. Endpoint will return the error message "Not allowed by CORS"

**Comment by RobinBrinkmann** [comment]
Backlog clean-up. Closing of outdated issues.
