### ISSUE TITLE
Move example component images to OIH docker hub

### ISSUE THREAD

**Issue by heggert** [openintegrationhub/openintegrationhub#955]
As a developer, I want to move the example component docker images to OIH docker hub so that we control changes and availability.

**Acceptance Criteria:**
- [ ] Component "timer" moved
- [x] Component "node js code" moved

---

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by RobinBrinkmann** [comment]
closing issue as the timer component is not crucial to the framework anymore as its functionality can be covered by other services/components.
