### ISSUE TITLE
Include on-Premise applications in an hybrid scenario

### ISSUE THREAD

**Issue by tboehle** [openintegrationhub/openintegrationhub#958]
Many enterprise applications are running on-Premise due to security or legacy reasons. The task is to create and document a solution for including those applications.
First the ferryman npm package has to be adopted to one targeted programming language, in this case Java, to create a runtime environment for connectors.
* https://github.com/openintegrationhub/openintegrationhub/tree/master/lib/ferryman
* https://github.com/elasticio/sailor-jvm

The task is to adapt the SOAP component and create a database component to access on-Premise applications.

* https://github.com/openintegrationhub/soap-component
* https://github.com/openintegrationhub/jdbc-component

**Comment by blaggacao** [comment]
It looks like it opens the door for apache camel based workflows?

**Comment by RobinBrinkmann** [comment]
Backlog clean-up. Closing of outdated issues.
