### ISSUE TITLE
Update local installation guide 

### ISSUE THREAD

**Issue by RobinBrinkmann** [openintegrationhub/openintegrationhub#961]
The new setup srcipt needs to be properly documented in the minikube folder and general installation guide.

---

**Acceptance Criteria:**
- [x] https://github.com/openintegrationhub/openintegrationhub/tree/master/minikube is updated
- [x] https://github.com/openintegrationhub/openintegrationhub.github.io is updated

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by blaggacao** [comment]
I added a generator for dev environment (not minikube) in #1041 which builds configuration overlays from (trusted) sources in `./services.*` &rarr; `just deploy/generate-config oih-dev-ns overlays/dev` &mdash; with this overlay approach of #1041 , it's very hard to get out of sync.
