### ISSUE TITLE
Review & update currently used libraries / open source tools in existing services 

### ISSUE THREAD

**Issue by RobinBrinkmann** [openintegrationhub/openintegrationhub#964]
All existing services need to be checked for outdated dependencies and updated if needed.

---

**Acceptance Criteria:**
- [x] IAM checked
- [x] Secret-Service checked
- [x] Component Orchestrator checked
- [ ] Meta Data Repository checked
- [ ] App Directory checked
- [ ] Logging Service checked

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by blaggacao** [comment]
`request-promise` seems deprecated - `unfetch` seems like what we want &mdash; as seen in example adaper + transformer.

**Comment by heggert** [comment]
I agree that we should replace `request-promise`. But I would prefer the use of `node-fetch`.

**Comment by blaggacao** [comment]
@heggert Sounds perfect. It might bring in a little added comfort and size might not be the biggest concern.

**Comment by RobinBrinkmann** [comment]
Will be taken care of with #1082
