### ISSUE TITLE
Update minikube local setup for development

### ISSUE THREAD

**Issue by weberjm** [openintegrationhub/openintegrationhub#977]
As a Developer, I want to have a scripted development environment setup so that my working environment is repeatable and allows for viewing my changes while developing for the framework.

Further description:
The current [Local Installation Guide](https://openintegrationhub.github.io//docs/Getting%20Started/LocalInstallationGuide.html) provides a good starting point for getting a running version of the OIH framework to deploy on a local system. However, it relies on only deploying from published containers rather than local source files. 

Building on the work already done by @heggert, the minikube setup will be modified to support live development and the installation guide will be updated.
...

---

**Acceptance Criteria:**
- [x] Minkube setup can be deployed from a single script
- [x] Developer can choose which services to deploy from public containers and which to deploy from local source
- [x] The instructions and scripts are set to work in both Mac and Windows environments.
- [x] The local installation guide is updated to reflect the new changes and instructions.

---

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by blaggacao** [comment]
Superseded by #1006 - I might do a PR in the following days, no worries.

**Comment by blaggacao** [comment]
I'd add: welcome the magic.of nix-shell `shell.nix` - unix only

and justfile (like makefile) leveraging any convenient scripting language for the few remaining bits and pieces (after skaffold)
