### ISSUE TITLE
Create docker-compose setup for local development 

### ISSUE THREAD

**Issue by weberjm** [openintegrationhub/openintegrationhub#979]
As a Developer, I want to have a scripted development environment setup in Docker so that my working environment is repeatable and allows for viewing my changes while developing for the framework.

Further description:
The current [Local Installation Guide](https://openintegrationhub.github.io//docs/Getting%20Started/LocalInstallationGuide.html) provides a good starting point for getting a running version of the OIH framework to deploy on a local system using minikube. However, it relies on only deploying from published containers rather than local source files. Some developers would also prefer to use docker-compose to the minikube deployment. 

Building on the work already done by @heggert, the docker-compose setup will allow for live development and the installation guide will be updated.

---

**Acceptance Criteria:**
- [x] Docker setup can be deployed from a single script
- [x] The instructions and scripts are set to work in both Mac and Windows environments.
- [x] The local installation guide is updated to reflect the new changes and instructions.

---

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by blaggacao** [comment]
Superseded by #1006 (can be made available with k3d) - a better alternative
