### ISSUE TITLE
Component Orchestrator Flows missing ELASTICIO_PUBLISH_MESSAGES_TO

### ISSUE THREAD

**Issue by mlb5000** [openintegrationhub/openintegrationhub#985]
It may be that the latest Component Orchestrator code (in Master) is not yet ready for production, but whenever I launch flows with the updated version, I get a failure inside the step node saying complaining about missing environment variables `ELASTICIO_CONTAINER_ID` or `ELASTICIO_PUBLISH_MESSAGES_TO`. I see that that former was commented out here: https://github.com/openintegrationhub/openintegrationhub/blob/master/services/component-orchestrator/src/drivers/kubernetes/KubernetesDriver.js#L309, but I don't see where `PUBLISH_MESSAGES_TO` is supposed to originate. I upgraded the node to the latest version of Sailor to see if that would fix it, but it did not.

Digging further, it appears that this commit (https://github.com/openintegrationhub/openintegrationhub/commit/b94462d89b5f2dcbea76b386f2b350a0dd51ad46) commented out that value from `createQueuesForFlowNode`, so it no longer got sent to the nodes.

https://github.com/openintegrationhub/openintegrationhub/blame/cf38bd64f19041c612c92a33cea391f2023300c2/lib/backend-commons-lib/src/QueueCreator.js#L313 

For the record, the reason I need the updated codebase is so I have the ability to increase resource allocation to different nodes, since we've had some get `OOMKilled`, as well as some other bugs that we've encountered that are not yet deployed to Docker hub.

**Comment by mlb5000** [comment]
Even after uncommenting out that line the components now complain about `ELASTICIO_DATA_ROUTING_KEY` not being set

**Comment by mlb5000** [comment]
It looks like `DATA_ROUTING_KEY` was renamed to `OUTPUT_ROUTING_KEY` on July 19 (https://github.com/openintegrationhub/openintegrationhub/commit/f2e2a5f078c309064c514ae565baafadaec27d7f#diff-882d413d60ac2d2ca92b241ccba18a64) but that would seem to make this incompatible with ElasticIO/Sailor components?

**Comment by RobinBrinkmann** [comment]
@heggert please check

**Comment by heggert** [comment]
Please use *ferryman* as component lib instead of *sailor*. Most of the supplied env vars got obsolete by the new orchestrator token.
