### ISSUE TITLE
Describe notification and event bus

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#99]
As a development lead I want to understand the  lnotification and event bus service, so that I am able to build the services according to the specifications.

**Further description:**

This service is not documented yet.

Template for the service concept: [MicroserviceDescriptionTemplate](https://github.com/openintegrationhub/Microservices/blob/master/MicroserviceDescriptionTemplate.md)

If a decision was made against this service in #100 the output of this issue should be a statement why this service is not needed any longer.

---

**Acceptance Criteria:**
- [x] Publish first draft of concept/statement on GitHub

**Comment by philecs** [comment]
@hschmidthh any updates on this issue?

**Comment by hschmidthh** [comment]
Here is the first draft of the concept:
https://github.com/openintegrationhub/Microservices/blob/MessageandEventBusConcept/MessageProcessing/MessageandEventBus.md
