### ISSUE TITLE
Secrets are not unmasked if the starting user does not have rawRead

### ISSUE THREAD

**Issue by mlb5000** [openintegrationhub/openintegrationhub#998]
Based on [this block of code](https://github.com/openintegrationhub/openintegrationhub/blob/e6b07671f3ea55f8222121d69f980c5d306da411/lib/component-orchestrator/src/ComponentOrchestrator.js#L157) it looks like the flow's behavior will change depending on who **started it**. If the user who started the flow does not have the `secrets.secret.readRaw` permission, the per-component token used to read the secrets will not have enough permission to get an unmasked one from Secret service. 

To recreate, just create any user who has 

```
"permissions": [
            "components.get",
            "flows.read",
            "flows.write",
            "flows.control"
        ],
```

And then, as that user, start a flow whose components have credentials associated with them. The downstream nodes will only receive masked secrets, not the expected plaintext ones.

For security reasons, in my cluster the only account that has the `readRaw` permission is the component orchestrator (and Admin, obviously).

**Comment by mlb5000** [comment]
Upon further digging in the code, how you want the temporary flow token to be associated with the starting user, and destroyed on teardown, I'm guessing that how secrets are passed is something that will be changing in the near future (I feel like @heggert mentioned this somewhere). So what I did was give my service account `secrets.secret.readRaw`, but leave it off the token that is used externally. Because you use `forceNew` on the token call, it shouldn't interfere with the token I'm already using.

**Comment by russojrv-zz** [comment]
Hi Matthew, we have fixed this issue with the connected [PR](https://github.com/openintegrationhub/openintegrationhub/issues/1404). We added the customPermissions parameter to the createToken method. Now, we don't need to assign to the user the readRaw permission to the user that starts the flow.

Thanks for your comments!
