### ISSUE TITLE
Locally Run Connectors which send data fail to send correctly

### ISSUE THREAD

**Issue by weberjm** [openintegrationhub/openintegrationhub#999]
As locally run connectors continue to use sailor.js inside of the ferryman, any steps which send data from local connectors calls the following:
https://github.com/openintegrationhub/openintegrationhub/blob/2238305ff9dbfdd52553f8bb36e26554dbaa6c9a/lib/ferryman/lib/sailor.js#L358

However, this function has been commented out in amqp.js
https://github.com/openintegrationhub/openintegrationhub/blob/2238305ff9dbfdd52553f8bb36e26554dbaa6c9a/lib/ferryman/lib/amqp.js#L261-L268

Also, switching to the ferryman method of calling sendBackChannel() will not work, because the local components using sailor do not send on the orchestratorToken, so the Component Orchestrator cannot process the message correctly.

Additionally, uncommenting the sendData() function will not work, because the components no longer are sent the DATA_ROUTING_KEY.

Please let us know (originally reported by @mlb5000) what the plan is moving forward with the ferryman, and look at how to fix this issue in the short term.

**Comment by SvenHoeffler** [comment]
Will need some further input form @heggert , but to my understanding the idea is that both local and global connectors will eventually just use the same overall message infrastructure. To that end, the sailor.js will eventually just be deprecated entirely, and both local and global flows can and will use ferryman.js

**Comment by heggert** [comment]
I agree, we have to take this opportunity to reduce complexity. Global and local components should use ferryman the same way.

**Comment by RobinBrinkmann** [comment]
this should be resolved by now with the latest architecture decisions. As discussed earlier @weberjm please double check and close.

**Comment by weberjm** [comment]
With the removal of Sailor as an option to run components locally, this Issue is no longer valid. Component creators will have to ensure that they are using only ferryman going forward. Older components will need to be updated to support this.
